### ISSUE TITLE
How to get presence's status element

### ISSUE THREAD

**Issue by tolgatanriverdi** [robbiehanson/XMPPFramework#10]
Hello
I want to get the status element of presence so for doing it I've added a category to XMPPPresence class like shown in below and it worked fine 

@implementation XMPPPresence (AddStatus)

-(void) addStatus:(NSString *)status
{
    //NSXMLElement *showElement = [NSXMLElement elementWithName:@"show" stringValue:@"online"];
    NSXMLElement *statusElement = [NSXMLElement elementWithName:@"status" stringValue:status];
    //[self addChild:showElement];
    [self addChild:statusElement];
}

@end

However when I tried to retrieve it on the receiving side with using

   XMPPUserCoreDataStorageObject *user = [self.fetchedResultsController objectAtIndexPath:indexPath];
    cell.textLabel.text = user.displayName;
    cell.detailTextLabel.text = user.primaryResources.status;

it crashes and I've checked the user.primaryResources  and it was nil , I've also checked the size of resources and it was 0.

Does anyone have any idea about how can I get the status for presence  all I want to accomplish is showing the presence status in the subtitle of a cell (like in whatsapp)

P.S : I'm using open fire as xmpp server

**Comment by pmehul55** [comment]
@robbiehanson : Here i am setting my XMPPPresence when app goes to background mode but how to get this info from other any stanza request ?
 
            let presence = XMPPPresence(type: "unavailable")
            let priority = DDXMLElement.element(withName: "priority", stringValue: "42") as! DDXMLElement
            let status =   DDXMLElement.element(withName: "status", stringValue: "\(self.getCurrentMillis())") as! DDXMLElement
            let away =   DDXMLElement.element(withName: "show", stringValue: "away") as! DDXMLElement
            
            presence?.addChild(status)
            presence?.addChild(priority)
            presence?.addChild(away)
            xmppStream?.send(presence)

Help please.
