### ISSUE TITLE
File transfer using XEP -0234 jingle File transfer

### ISSUE THREAD

**Issue by shraddha-patel-1891** [robbiehanson/XMPPFramework#1006]
Hello,
i am using jingle for file transfer . but it's give me error :
"503 user session not available".
i am sending following stanza for image sending :
1)
`<iq type="set" to="2222@192.165.89.23/139528219733921739421510728162921096" from="1111@192.165.89.23l/phone"><jingle sid="ntiislh60c" initiator="1111@192.165.89.23/phone" action="session-initiate" xmlns="urn:xmpp:jingle:1"><content name="l5hfq2g2oi" creator="initiator" senders="initiator"><description xmlns="urn:xmpp:jingle:apps:file-transfer:5"><file><size>47754</size><name>7eddceba-ac85-4e61-b42d-844be1a62969.jpg</name></file></description><transport sid="mpb88nsur0" xmlns="urn:xmpp:jingle:transports:s5b:1"/></content></jingle></iq>`

2)
`<iq type="set" to="2222@192.165.89.23/139528219733921739421510728162921096" from="1111@192.165.89.23/phone"><jingle sid="ntiislh60c" initiator="1111@192.165.89.23/phone" action="transport-info" xmlns="urn:xmpp:jingle:1"><content name="l5hfq2g2oi" creator="initiator" senders="initiator"><transport sid="mpb88nsur0" xmlns="urn:xmpp:jingle:transports:s5b:1"><candidate-error/></transport></content></jingle></iq>`

3)
`<iq type="set" to="2222@192.165.89.23/139528219733921739421510728162921096" from="1111@192.165.89.23/phone"><jingle sid="ntiislh60c" initiator="1111@192.165.89.23/phone" action="transport-replace" xmlns="urn:xmpp:jingle:1"><content name="l5hfq2g2oi" creator="initiator" senders="initiator"><transport sid="i970cavkvg" block-size="8192" xmlns="urn:xmpp:jingle:transports:ibb:1"/></content></jingle></iq>`

4)
`<iq type="set" to="2222@192.165.89.23/139528219733921739421510728162921096" from="1111@192.165.89.23/phone"><jingle sid="ntiislh60c" initiator="1111@192.165.89.23/phone" action="session-info" xmlns="urn:xmpp:jingle:1"><checksum name="a-file-offer" creator="initiator" xmlns="urn:xmpp:jingle:apps:file-transfer:5"><file><hash algo="sha-1" xmlns="urn:xmpp:hashes:2">nfJMXoOsYBHzb/tM0RvmIdq+SWA=</hash></file></checksum></jingle></iq>`

So, Anyone have solution for file transfer using jingle protocol then please help me.

Thank you.

**Comment by vitalyster** [comment]
can you show replies to these stanzas?

**Comment by shraddha-patel-1891** [comment]
Hello vitalyster,

i am getting following response on  ejabbered log,
 
<<"<iq from='1111@192.165.89.23/phone' to='2222@192.165.89.23/139528219733921739421510728162921096' type='error'><jingle xmlns='urn:xmpp:jingle:1' action='session-initiate' initiator='1111@192.165.89.23/phone' sid='C04B8C23-416E-4056-9A05-AE90DA3E874A'><content name='image-transfer' creator='initiator' senders='initiator'><description xmlns='urn:xmpp:jingle:apps:file-transfer:5' image='media'><file xmlns='http://jabber.org/protocol/si/profile/file-transfer' name='img123.png' size='40742'/></description><transport xmlns='urn:xmpp:jingle:transports:s5b:1' sid='56508159-83A3-47A2-8832-54FA29EBDB70'/></content></jingle><error code='503' type='cancel'><service-unavailable xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/><text xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>User session not found</text></error></iq>">>

any other response required then please message me .
Thanks

**Comment by shoaibhassanWhizpool** [comment]
i am also facing same response for voip,any solution @shraddha-patel-1891  , @vitalyster  will be highly appreciated.

**Comment by shraddha-patel-1891** [comment]
Hello shoaibhassan,
i resolved issue using following steps:

1) send image using this code :- 
`public func sendimage(_image :UIImage)
    {
        data = UIImageJPEGRepresentation(_image,1.0)
        let imageSize: Int = data!.count
        let SizeString = String(imageSize)


        // Client requests a slot on the upload service

        let iq = DDXMLElement.element(withName: "iq") as! DDXMLElement
        iq.addAttribute(withName: "id", stringValue: generateBoundaryString())
        iq.addAttribute(withName: "to", stringValue: Constants.KxmppUploadServer)
        iq.addAttribute(withName: "type", stringValue: "get")


        let request = DDXMLElement.element(withName: "request") as! DDXMLElement
        request.addAttribute(withName: "xmlns", stringValue: "urn:xmpp:http:upload")

        let filename = DDXMLElement.element(withName: "filename") as! DDXMLElement
        filename.stringValue = "111newssssss11.png"
        request.addChild(filename)

        let sizeimg = DDXMLElement.element(withName: "size") as! DDXMLElement
        sizeimg.stringValue = SizeString
        request.addChild(sizeimg)

        let contenttype = DDXMLElement.element(withName: "content-type") as! DDXMLElement
        contenttype.stringValue = "image/png"
        request.addChild(contenttype)

        iq.addChild(request)

        self.xmppStream?.send(iq)
    }`

above code response get one url. After that using alamofire  or afnetworking upload image on this url using .put method.

2) upload image on url code using alamofire :-
`func createMultipart(imgurl: String,filename:String,senderid:String ,callback: @escaping (Bool) -> Void)
    {

        let headers = [
            "Content-Type": "image/jpeg"
        ]

        // presignedUrl is a String
        Alamofire.upload(data!, to: strimageurl!, method: .put, headers: headers)
            .uploadProgress
            { progress in // main queue by default
                print("Upload Progress: \(progress.fractionCompleted)")
                print("Upload completedUnitCount: \(progress.completedUnitCount)")
                
            }
            .responseData
            {
                response in

                if response.response == nil
                {

                    return
                }
                else
                {

                   
                    self.sendmessage(msgstr: self.strimageurl!,senderID: senderid)
                }

        }


        //let filename = "\(UUID().uuidString).jpg"
    }` 

if response success then simply send message using xmpp. In message send link that given in 1st step. Display image based on URL.

3) send message using xmpp(link send in message) :- 
`let body = DDXMLElement.element(withName: "body") as! DDXMLElement
            body.stringValue = msgstr
        
            let completeMessage = DDXMLElement.element(withName: "message") as! DDXMLElement
            completeMessage.addAttribute(withName: "type", stringValue: "chat")
            completeMessage.addAttribute(withName: "to", stringValue: senderID)
            completeMessage.addAttribute(withName: "from", stringValue: jabberID!)
            completeMessage.addAttribute(withName:  "id", stringValue: generateBoundaryString())
            completeMessage.addAttribute(withName:  "timestamp", stringValue: dateString)
            
            //completeMessage.addChild(timestamp)
            completeMessage.addChild(body)
        
            self.xmppStream?.send(completeMessage)`

if any query then ask me.
Thank you.

**Comment by shoaibhassanWhizpool** [comment]
@shraddha-patel-1891  thanks for your response,actually i am not transferring a files just need to exchange session description using jingle nodes, here is my example code for iq


> `<iq type=\"set\" to=\"toNumber@Domain.net\" from=\"fromNumber@Domain.net/119077661396518911058242\" id=\"xkVPpBeI5Z\"><jingle xmlns=\"urn:xmpp:jingle:1\" action=\"session-initiate\" initiator=\toNumber@Domain.net/119077661396518911058242\" sid=\"a73sjjvkla37jfea\"><content creator=\"initiator\" name=\"voice\"><description xmlns=\"urn:xmpp:jingle:apps:rtp:1\" media=\"audio\"><payload-type name=\"speex\" clockrate=\"8000\" id=\"97\"/></description><transport xmlns=\"urn:xmpp:jingle:transports:ice-udp:1\"/></content></jingle></iq>`


but receiving response like this


<iq xmlns="jabber:client" lang="en" to="oNumber@Domain.net/119077661396518911058242" from="fromNumber@Domain.net" type="error" id="xkVPpBeI5Z"><jingle xmlns="urn:xmpp:jingle:1" action="session-initiate" initiator="toNumber@Domain.net/119077661396518911058242" sid="a73sjjvkla37jfea"><content creator="initiator" name="voice"><description xmlns="urn:xmpp:jingle:apps:rtp:1" media="audio"><payload-type name="speex" clockrate="8000" id="97"/></description><transport xmlns="urn:xmpp:jingle:transports:ice-udp:1"/></content></jingle><error code="503" type="cancel"><service-unavailable xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/><text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" lang="en">No module is handling this query</text></error></iq>.

**Comment by shraddha-patel-1891** [comment]
Hello shoaibhassan,

First i tried using jingle protocol but it's not working that's why i am using file transfer protocol .

if i will find any solution then given to you.
 Thank You.

**Comment by ashokt** [comment]
Hi

> Hello shoaibhassan,
> i resolved issue using following steps:
> 
> 1. send image using this code :-
>    `    public func sendimage(_image :UIImage)
>    {
>    data = UIImageJPEGRepresentation(_image,1.0)
>    let imageSize: Int = data!.count
>    let SizeString = String(imageSize)
>    ```
>     let iq = DDXMLElement.element(withName: "iq") as! DDXMLElement
>     iq.addAttribute(withName: "id", stringValue: generateBoundaryString())
>     iq.addAttribute(withName: "to", stringValue: Constants.KxmppUploadServer)
>     iq.addAttribute(withName: "type", stringValue: "get")
>    
>    
>     let request = DDXMLElement.element(withName: "request") as! DDXMLElement
>     request.addAttribute(withName: "xmlns", stringValue: "urn:xmpp:http:upload")
>    
>     let filename = DDXMLElement.element(withName: "filename") as! DDXMLElement
>     filename.stringValue = "111newssssss11.png"
>     request.addChild(filename)
>    
>     let sizeimg = DDXMLElement.element(withName: "size") as! DDXMLElement
>     sizeimg.stringValue = SizeString
>     request.addChild(sizeimg)
>    
>     let contenttype = DDXMLElement.element(withName: "content-type") as! DDXMLElement
>     contenttype.stringValue = "image/png"
>     request.addChild(contenttype)
>    
>     iq.addChild(request)
>    
>     self.xmppStream?.send(iq)
>    ```
>    }`
> 
> above code response get one url. After that using alamofire or afnetworking upload image on this url using .put method.
> 
> 1. upload image on url code using alamofire :-
>    `      func createMultipart(imgurl: String,filename:String,senderid:String ,callback: @escaping (Bool) -> Void)
>    {
>    ```
>     let headers = [
>         "Content-Type": "image/jpeg"
>     ]
>    
>     // presignedUrl is a String
>     Alamofire.upload(data!, to: strimageurl!, method: .put, headers: headers)
>         .uploadProgress
>         { progress in // main queue by default
>             print("Upload Progress: \(progress.fractionCompleted)")
>             print("Upload completedUnitCount: \(progress.completedUnitCount)")
>             
>         }
>         .responseData
>         {
>             response in
>    
>             if response.response == nil
>             {
>    
>                 return
>             }
>             else
>             {
>    
>                
>                 self.sendmessage(msgstr: self.strimageurl!,senderID: senderid)
>             }
>    
>     }
>    
>    
>     //let filename = "\(UUID().uuidString).jpg"
>    ```
>    }`
> 
> if response success then simply send message using xmpp. In message send link that given in 1st step. Display image based on URL.
> 
> 1. send message using xmpp(link send in message) :-
>    `      let body = DDXMLElement.element(withName: "body") as! DDXMLElement
>    body.stringValue = msgstr
>    ```
>         let completeMessage = DDXMLElement.element(withName: "message") as! 
>         DDXMLElement
>         completeMessage.addAttribute(withName: "type", stringValue: "chat")
>         completeMessage.addAttribute(withName: "to", stringValue: senderID)
>         completeMessage.addAttribute(withName: "from", stringValue: jabberID!)
>         completeMessage.addAttribute(withName:  "id", stringValue: generateBoundaryString())
>         completeMessage.addAttribute(withName:  "timestamp", stringValue: dateString)
>         
>         //completeMessage.addChild(timestamp)
>         completeMessage.addChild(body)
>     
>         self.xmppStream?.send(completeMessage)`
>    ```
> 
> if any query then ask me.
> Thank you.
@shraddha-patel-1891 do you fully functional code ios xmpp chat in swift.
if it is there can you please upload to drop box and paste here the link

Thanks in Advance

**Comment by HB-Dimple** [comment]
Any update on this?
