### ISSUE TITLE
Close Socket

### ISSUE THREAD

**Issue by gmochid** [robbiehanson/XMPPFramework#1012]
I am now using ejabberd for my XMPP server and having trouble to switch my app to Push Mode the the iPhone app is going to background. On the `ProcessOne - Mobile XMPP Stack` documentation, it is said that to activate the push mode I have to send the close stream tag `</stream:stream>` and close the socket. 

But until right now I dont know how to close the socket without closing the XMPPStream. Is there anyone here that could help me?

**Comment by vitalyster** [comment]
that is the purpose of push notifications - you will receive it when stream is closed (because you can’t have socket/stream in the background)
