### ISSUE TITLE
Pod installation issue.

### ISSUE THREAD

**Issue by shravanteegala** [robbiehanson/XMPPFramework#1013]
I using  Xcode 9.1.  and pod version 1.3.0. 

when I try to install the XMPPFramework. by pod file  I got  below error in terminal.

 
[!] Unable to satisfy the following requirements:

- `XMPPFramework (~> 3.7.0)` required by `Podfile`

Specs satisfying the `XMPPFramework (~> 3.7.0)` dependency were found, but they required a higher minimum deployment target.

Any one can find solution plz help me.

**Comment by shravanteegala** [comment]
![screen shot 2017-11-20 at 1 55 35 pm](https://user-images.githubusercontent.com/13646977/33008928-0b3d3bce-cdfb-11e7-9364-8f3991e6073e.png)
I solved to change the Deployment version 10.0.

**Comment by shraddha-patel-1891** [comment]
hello shravanteegala ,
i have same issue and and also change Deployment Target 10.0 but it give me following error :- 
"Cannot find protocol declaration for 'XMPPStreamDelegate" in projectname-swift.h file.
how can i resolved?
thank you
