### ISSUE TITLE
Logged in user avatar and status?

### ISSUE THREAD

**Issue by avaidyam** [robbiehanson/XMPPFramework#104]
I can't seem to access them.... xmppRoster's myUser and myPresence don't work, and xmppStream's myJID doesn't work either. Any help?

**Comment by TheEngineerz** [comment]
@avaidyam  how did  you resolve the issue?

**Comment by avaidyam** [comment]
My solution was to not use the framework unfortunately.

**Comment by TheEngineerz** [comment]
I am also using some external API to handle all of this.
