### ISSUE TITLE
Any plans to release a new version anytime soon

### ISSUE THREAD

**Issue by jelenadj** [robbiehanson/XMPPFramework#1041]
It's been a long time from the last stable release, and I am just wondering do you have some estimate when we can expect another one that includes some updates and improvements from master?

**Comment by chrisballinger** [comment]
Have you been using master? It's pretty stable at this point, but I haven't
had the time to put out a release.

**Comment by chrisballinger** [comment]
There isn't too much activity on master. I mainly am just unsure if there is any major public API cleanup left to be done before pushing a stable v4.0. 

Btw you can pin to a specific commit in your Podfile like `00c1101`

**Comment by jelenadj** [comment]
Thanks.
