### ISSUE TITLE
Cant connect

### ISSUE THREAD

**Issue by alocket2** [robbiehanson/XMPPFramework#1058]
Using the framework I can do the following

- willConnectToStream
- socketDidConnect
- negotiationDidStart

Console output from below is

- Attempting to connect...
- Connected socket
- Negotiation started..

nothing after this happens

Can someone help me out?

`
let jId = XMPPJID(string: "lokett@35.197.96.175")

ChatManager(jID: jId!, host: "35.197.96.175", password: "anthony0")
`

`
public final class ChatManager: NSObject {

    var stream: XMPPStream!
    var jID: XMPPJID
    let host: String
    let port: UInt16
    let password: String

    init(jID: XMPPJID, host: String, port: UInt16 = 5223, password: String) {

        self.jID = jID
        self.host = host
        self.port = port
        self.password = password

        // Setup the XMPPStream
        stream = XMPPStream()

        stream.hostName = self.host
        stream.hostPort = self.port
        stream.myJID = self.jID

        super.init()

        stream.addDelegate(self, delegateQueue: DispatchQueue.main)

        connect()
    }
    
    private func connect(){
        if !self.stream.isDisconnected {
        }
        
        let timeoutInterval: TimeInterval = 5.0
        do {
            try stream.connect(withTimeout: XMPPStreamTimeoutNone)
        } catch {}
        
    }
    
}

extension ChatManager: XMPPStreamDelegate {
    
    public func xmppStreamDidSecure(_ sender: XMPPStream) {
        print("Secured...")
    }
    
    public func xmppStreamDidStartNegotiation(_ sender: XMPPStream) {
        print("Negotiation Started..")
        
    }
    
    public func xmppStream(_ sender: XMPPStream, willSecureWithSettings settings: NSMutableDictionary) {
        print("Will secure...")
        print("Settings: \(settings)")
    }
    
    public func xmppStream(_ sender: XMPPStream, didReceive trust: SecTrust, completionHandler: @escaping (Bool) -> Void) {
        print("Recieved trust")
    }
    
    public func xmppStreamWillConnect(_ sender: XMPPStream) {
        print("Attempting to connect...")
    }
    
    public func xmppStreamDidConnect(_ sender: XMPPStream) {
        print("Connected")
        try! stream.authenticate(withPassword: password)
    }
    
    public func xmppStreamConnectDidTimeout(_ sender: XMPPStream) {
        print("Connection timeout")
    }
    
    public func xmppStreamWasTold(toAbortConnect sender: XMPPStream) {
        print("Abortion connect")
    }
    
    public func xmppStreamDidAuthenticate(_ sender: XMPPStream) {
        print("Stream: Authenticated")
    }
    
    public func xmppStream(_ sender: XMPPStream, didNotAuthenticate error: DDXMLElement) {
        print("Stream: Not Authenticated")
    }
    
    public func xmppStream(_ sender: XMPPStream, socketDidConnect socket: GCDAsyncSocket) {
        print("Connected socket")
    }
    
}
`

**Comment by YouZoudeFish** [comment]
I haven't use Swift yet,but OC's default port is 5222
