### ISSUE TITLE
iOS,How to get offline message!?

### ISSUE THREAD

**Issue by YouZoudeFish** [robbiehanson/XMPPFramework#1061]
Currently,I can connect to server,and can receive message (online).But as the title says ,how can i get the offline message....
Help!!!!!!!

**Comment by alocket2** [comment]
@YouZoudeFish  How are you connecting? I am unable to connect can you share? Are you using Swift or Obj-C

**Comment by rahul-apple** [comment]
@YouZoudeFish : After Successful XMPP Authentication we will be setting our Presence to Online(available)
```
func goOnline(){
        let presence = XMPPPresence()
        send(presence)
    }
```

Likewise, you need to set the presence to offline when the app goes to background or Terminated state

```
func goOffline(){
        let presence = XMPPPresence(type: "unavailable")
        send(presence)
        disconnectAfterSending()
    }
```
In such offline cases ,you will get a Push from XMPP Server if you register for the Push (ejabberd saas server) , when you came back to Online the Same Message will be delivered via **xmppstream**

**Comment by YouZoudeFish** [comment]
@alocket2 sorry about reply now, cause just start working....

**Comment by YouZoudeFish** [comment]
@rahul-apple 
<img width="587" alt="image" src="https://user-images.githubusercontent.com/13774334/39556300-f511e844-4eb1-11e8-80f2-d13cccfaab61.png">
I'm using OC,the code like this...
but can be the same with your Swift code.
Although,it doesn't work.(can't receive offline message)

**Comment by YouZoudeFish** [comment]
@rahul-apple  server-worker of the company is a newer in XMPP
he uses Openfire to establish the server,then uses Spark to test the function himself,can receive offline message he says
but i'm not sure it is correct.....

**Comment by YouZoudeFish** [comment]
Already fixed the problem.just a low-level error.....
my server-side told me he wrote a script that can send the offline message.I think he must observe the online property,if an user change online into offline,the script will send the message automatically....
Actually innocent....hahahaha.....

change anything with my code,can receive now
and thanks for replying @alocket2  @rahul-apple
