### ISSUE TITLE
Message delayed in iOS devices

### ISSUE THREAD

**Issue by rv7284** [robbiehanson/XMPPFramework#1067]
I'm working with ejabberd server and up until now was testing in the simulator and everything is working fine. But today I tried to run the application on an actual device and everything went haywire.

I'll try and explain the situation so someone might figure out what's wrong here. 
-between simulators, everything works fine and there is no delay.
- If I send messages from simulator to device, messages are delivered but the Received receipt from device won't be delivered to the simulator.
-Message from device to the simulator doesn't get delivered on time. sometimes it takes up to 2 mins to get delivered and sometimes it gets lost.

`
if let session = XMPP_CONTROLLER.xmppOneToOneChat.session(forUserJID: user.jid){ 
        session.sendMessage(withBody: message)
        counter = Int(INACTIVE_TIME_INTERVAL) + 1
    } else {
         showAlertMessage("Could not start chat session")
}
`

this is the code I'm using to send the message in my app.

**Comment by Elshad** [comment]
Did you found reason of this delay?
