### ISSUE TITLE
setLastDisconnect:lastHandledByClient:forStream: has nullable date

### ISSUE THREAD

**Issue by rnapier** [robbiehanson/XMPPFramework#1073]
In `XMPPStreamManagement`, `setLastDisconnect:...` is declared with a non-nullable date:

```
- (void)setLastDisconnect:(NSDate *)date
      lastHandledByClient:(uint32_t)lastHandledByClient
                forStream:(XMPPStream *)stream;
```

However, in `processReceivedAck:`, it can be called with a nil Date.

```
		else // edge case
		{
			[storage setLastDisconnect:disconnectDate
			       lastHandledByClient:lastHandledByClient
			       lastHandledByServer:lastHandledByServer
			    pendingOutgoingStanzas:pending
			                 forStream:xmppStream];
		}
```

There is nothing that ensures that `disconnectDate` has been initialized at this point, and in our program we're seeing it called with nil during launch (which crashes in Swift). I suspect the correct solution is to check for nil here, and pass `[NSDate date]`, but the correct solution may be to make it nullable.

**Comment by chrisballinger** [comment]
Thanks for the report! Would you mind submitting a PR marking nullable and adding nil checks?

**Comment by rnapier** [comment]
By "adding nil checks" I assume you mean in any existing implementations of this delegate method? If it's marked nullable, then I believe there's nothing that needs nil-checking in this method (and all current implementors will need to modify their signatures).

**Comment by chrisballinger** [comment]
Ah ok I didn't read closely enough. I think we should check if disconnectDate is not nil and pass [NSDate date] otherwise.

**Comment by rnapier** [comment]
The more I dig into this, the more I think `disconnectDate` should be nullable. If you look at `XMPPStreamManagementMemoryStorage`, it treats the value as nullable (in `removeAllForStream` it sets `lastDisconnect` to nil). A nil there just indicates that it has never accidentally disconnected.

Changing that does change the interface for Swift users, but I expect this is very rarely implemented (this is my first time in a project that implemented this protocol, and I don't think we needed to). I'm going to send a PR making the nullable change, and I can change the PR if you disagree.

**Comment by chrisballinger** [comment]
I think you're right. Thank you for looking in to it!
