### ISSUE TITLE
"Block implicitly retains 'self'" warnings

### ISSUE THREAD

**Issue by rnapier** [robbiehanson/XMPPFramework#1077]
Currently there are over 1000 warnings of "Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior."

These generally are intentional, but the warnings are problematic. It can be resolved either by adding `self->` to each case with a fix-it, or by turning off the warning. I'm happy to provide a PR for either.

**Comment by chrisballinger** [comment]
I prefer the explicitness of `self->`. Would love a PR!

**Comment by rnapier** [comment]
I just noticed that this project has some files w/ tabs and some with spaces (which creates a little bit of a mess with fix-its). Is one or the other preferred? I'm suspecting tabs, but the project defaults are currently spaces.

**Comment by chrisballinger** [comment]
Hahaha oh brother. This project has seen so many authors I think you can use whatever you want, either tabs or 4 spaces.
