### ISSUE TITLE
Memory Leak in [GCDAsyncSocket createReadAndWriteStrewm]

### ISSUE THREAD

**Issue by kingdomrain002** [robbiehanson/XMPPFramework#1090]
![wechatimg894](https://user-images.githubusercontent.com/40626581/44771298-2d1eab80-ab9d-11e8-91cc-611108cd97a7.jpeg)

**Comment by developertina** [comment]
how to resolve?

**Comment by zhanghuiDev** [comment]
Hello, has this problem been solved?

**Comment by kingdomrain002** [comment]
**参考github上 robbiehanson/XMPPFramework 上demo的工程，其在退出之后需要将清除掉之前创建的流。**

- (void)teardownStream{
    [self.xmppStream removeDelegate:self];
    [self.xmppReconnect removeDelegate:self];
    [self.xmppAutoPing removeDelegate:self];
    [self.xmppStreamManagement removeDelegate:self];
    [self.xmppRoster removeDelegate:self];
    [self.vCardTempModule removeDelegate:self];
    [self.vCardAvatarModule removeDelegate:self];
    [self.xmppMessageArchiving removeDelegate:self];
    [self.xmppMUC removeDelegate:self];

    [self.xmppReconnect    deactivate];
    [self.xmppAutoPing  deactivate];
    [self.xmppStreamManagement deactivate];
    [self.xmppRoster       deactivate];
    [self.vCardTempModule deactivate];
    [self.vCardAvatarModule deactivate];
    [self.xmppMessageArchiving deactivate];
    [self.xmppMUC deactivate];
    
    [self.xmppStream disconnect];
    
    self.xmppStream = nil;
    self.xmppReconnect = nil;
    self.xmppAutoPing = nil;
    self.storage = nil;
    self.xmppStreamManagement = nil;
    self.xmppRosterMemoryStorage = nil;
    self.xmppRoster = nil;
    self.vCardCoreDataStorage = nil;
    self.vCardTempModule = nil;
    self.vCardAvatarModule = nil;
    self.xmppMessageArchivingCoreDataStorage = nil;
    self.xmppMessageArchiving = nil;
    self.xmppMUC = nil;
}
