### ISSUE TITLE
App Store refused application: The app references non-public selectors

### ISSUE THREAD

**Issue by fmatosic** [robbiehanson/XMPPFramework#1138]
App store refuses to accept application as  with  explanation:
The app references non-public selectors in <YOUR APP>
activate:, addBody:, addDelegate:delegateQueue:, attributeForName:, connectedHost, elementID, from, setBucket:, setHostName:, setLevel:forClass:, setPlaceholderColor

Searching through the Workspace found that most of these are used by XMPPFramework.
As the app relies on the framework we cannot remove it.
Maybe someone also reported this?

**Comment by chrisballinger** [comment]
Sounds like a false positive. Try resubmitting again, or escalating to Apple Developer Support

**Comment by fmatosic** [comment]
I deintegrated and re initialised the pods, clean build and it uploaded fine.

**Comment by fmatosic** [comment]
Seems it was a false positive. Apps passed review
