### ISSUE TITLE
Add Swift Package Manager support

### ISSUE THREAD

**Issue by karimhm** [robbiehanson/XMPPFramework#1176]
Related to #1149

> The following PRs need to be merged first before being able to add a `Package.swift` manifest to `XMPPFramework`
> - KissXML: [#119](https://github.com/robbiehanson/KissXML/pull/119)
> - libidn-framework: [#6](https://github.com/chrisballinger/libidn-framework/pull/6)

**Comment by chrisballinger** [comment]
This is also blocked on Xcode 12 because XMPPFramework includes resources, which requires SPM 5.3. See [SE-0271](https://github.com/apple/swift-evolution/blob/master/proposals/0271-package-manager-resources.md) for more details.

https://github.com/robbiehanson/XMPPFramework/blob/9d625f5c12020a7edd5f533000404a249c8216f7/XMPPFramework.podspec#L37

**Comment by karimhm** [comment]
> This is also blocked on Xcode 12 because XMPPFramework includes resources, which requires SPM 5.3. See [SE-0271](https://github.com/apple/swift-evolution/blob/master/proposals/0271-package-manager-resources.md) for more details.
> 
> https://github.com/robbiehanson/XMPPFramework/blob/9d625f5c12020a7edd5f533000404a249c8216f7/XMPPFramework.podspec#L37

We could add Swift PM support but let the user to copy all assets needed by `XMPPFramework`, until Xcode 12 rolls out to production.

**Comment by karimhm** [comment]
@chrisballinger I believe it is possible to use `XMPPFramework` without Core Data extensions (but nothing will persist).

**Comment by karimhm** [comment]
@chrisballinger is it ok to migrate the Core Data object model from **`xcdatamodel` bundle** to code?

**Comment by chrisballinger** [comment]
@karimhm It would probably be better to leave the model definitions as-is to avoid breaking changes if possible. Really appreciate your work on the SPM support, it's been on my mind for a while and you did an awesome job getting all the pieces in place.
