### ISSUE TITLE
cannot build desktop demo source code https://github.com/robbiehanson/XMPPFramework

### ISSUE THREAD

**Issue by ghost** [robbiehanson/XMPPFramework#142]
I have cloned a xmpp framework source code from https://github.com/robbiehanson/XMPPFramework
but I cannot build  this because xcode say

Can you give me a working project ( Desktop) ?
Thanks,

Ld /Users/xcodev/Library/Developer/Xcode/DerivedData/XMPPStream-ecpdmrjydsqgikgwpcfabjwrgtkp/Build/Products/Debug/XMPPStream.app/Contents/MacOS/XMPPStream normal x86_64
    cd /Users/xcodev/Downloads/XMPPFramework-master/Xcode/DesktopXMPP
    setenv MACOSX_DEPLOYMENT_TARGET 10.7
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -L/Users/xcodev/Library/Developer/Xcode/DerivedData/XMPPStream-ecpdmrjydsqgikgwpcfabjwrgtkp/Build/Products/Debug -L/Users/xcodev/Downloads/XMPPFramework-master/Xcode/DesktopXMPP/../../Vendor/libidn -F/Users/xcodev/Library/Developer/Xcode/DerivedData/XMPPStream-ecpdmrjydsqgikgwpcfabjwrgtkp/Build/Products/Debug -filelist /Users/xcodev/Library/Developer/Xcode/DerivedData/XMPPStream-ecpdmrjydsqgikgwpcfabjwrgtkp/Build/Intermediates/XMPPStream.build/Debug/XMPPStream.build/Objects-normal/x86_64/XMPPStream.LinkFileList -mmacosx-version-min=10.7 -fobjc-arc -fobjc-link-runtime -framework CoreLocation -lidn -framework Cocoa -framework SystemConfiguration -lxml2 -lresolv -framework Security -o /Users/xcodev/Library/Developer/Xcode/DerivedData/XMPPStream-ecpdmrjydsqgikgwpcfabjwrgtkp/Build/Products/Debug/XMPPStream.app/Contents/MacOS/XMPPStream

ld: warning: ignoring file /Users/xcodev/Downloads/XMPPFramework-master/Vendor/libidn/libidn.a, missing required architecture x86_64 in file /Users/xcodev/Downloads/XMPPFramework-master/Vendor/libidn/libidn.a (3 slices)
Undefined symbols for architecture x86_64:
  "_stringprep", referenced from:
      +[LibIDN prepNode:] in LibIDN.o
      +[LibIDN prepDomain:] in LibIDN.o
      +[LibIDN prepResource:] in LibIDN.o
  "_stringprep_nameprep", referenced from:
      +[LibIDN prepDomain:] in LibIDN.o
  "_stringprep_xmpp_nodeprep", referenced from:
      +[LibIDN prepNode:] in LibIDN.o
  "_stringprep_xmpp_resourceprep", referenced from:
      +[LibIDN prepResource:] in LibIDN.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by aklesh123** [comment]
i have i problem creating libidn.a for arm64 support. any help?
