### ISSUE TITLE
Bug in XMPPRoomCoreDataStorage causing duplicate messages

### ISSUE THREAD

**Issue by Reefaq** [robbiehanson/XMPPFramework#156]
Just found that in XMPPRoomCoreDataStorage under method "handleIncomingMessage:room:"

it was mistakenly written "room.roomJID" instead of "room.myRoomJID" which fails the condition below it.

Due to this mistake whenever you send a message it add the message in CoreData again hence cause duplicate message.

Note: Its perfectly written in XMPPRoomHybridStorage and XMPPRoomMemoryStorage.

**Comment by parthpatel1105** [comment]
Hello robbiehanso,
I am stuck in date issue while send and receive XMPP message. If i have to send messages to user who is living in USA and i am in India. So how can manage exact message send date?

**Comment by Kayoto1** [comment]
I cconverted the date to the local machine date.

**Comment by parthpatel1105** [comment]
ya but it is impossible for different time zone. So any idea for Get UTC time from Openfire server??
