### ISSUE TITLE
MUC / Group Chat room - Create / Rejoin

### ISSUE THREAD

**Issue by iphoneAppleIos** [robbiehanson/XMPPFramework#259]
Hi Friends,

I am working on chat based app, Am successfully implemented single chat. I dont know how to create a chat room and re-join to the same chat room in case of connection lost.

Please help me how to implement this.

Regards,

**Comment by hiteshtrivedi** [comment]
Hi Friends,
I am looking for the same. Can you please share your code.

**Comment by Satishpatel** [comment]
Hello Dear,
Please visit following link
http://stackoverflow.com/questions/19268629/xmppframework-implement-group-chat-muc
Hope this help
