### ISSUE TITLE
GCDMulticastDelegate shouldn't always call async

### ISSUE THREAD

**Issue by malhal** [robbiehanson/XMPPFramework#266]
Because GCDMulticastDelegate is always using dispatch_async this means that when delegate methods are called from the main thread their invocation gets delayed until the next run loop, the same behavior as performSelector afterDelay:0. To fix this and make the methods fire when they are called you need to check if the queue is the main queue and then call the method synchronously. E.g.

```
        //begin fix
        if(node.delegateQueue == dispatch_get_main_queue()){
            [dupInvocation invokeWithTarget:nodeDelegate];
        }else{
        //end fix
            dispatch_async(node.delegateQueue, ^{ @autoreleasepool {

                [dupInvocation invokeWithTarget:nodeDelegate];

            }});
        }
```

**Comment by Amitmundra** [comment]
Hi,
I am getting exception in GCDDelegate class when going to remove object node in removeDelegate at line **[delegateNodes removeObjectAtIndex:(i-1)];**. Can you please help me to avoid this exception?

What may be the reason of causing exception?

Please help me to resolve the issue.
