### ISSUE TITLE
Unable to connect to xmppFramework for chatting IOS

### ISSUE THREAD

**Issue by zelin** [robbiehanson/XMPPFramework#269]
I am trying to connect to my openFire server with IOS XMPP. The code is from example of XMPP.

When i do [self connect]

The server Path is `"192.xxx.xxx.xx"`

the server port is `"9090"` // that's what my dev has placed it

for username i am doing `xx@192.xxx.xxx`

Now after firing [self connect] it first takes me 

```
 - (void)xmppStream:(XMPPStream *)sender socketDidConnect:(GCDAsyncSocket *)socket
```

and then after 3-5 seconds 
- (void)xmppStreamDidDisconnect:(XMPPStream *)sender withError:(NSError *)error

Error being 

```
Error Domain=GCDAsyncSocketErrorDomain Code=4 "Read operation timed out" UserInfo=0x17e49bf0 {NSLocalizedDescription=Read operation timed out}
```

if I place `http://` infront of serverPath i get 

```
Error Domain=kCFStreamErrorDomainNetDB Code=8 "nodename nor servname provided, or not known" UserInfo=0x16d73b90 {NSLocalizedDescription=nodename nor servname provided, or not known}
```

 This is occurring when trying to connect first time. What is the problem in following code. 

> ```
>  - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
>     {     
>       [DDLog addLogger:[DDTTYLogger sharedInstance]];
>         myLocationCtrl = [[MyCLController alloc] init];
>         [myLocationCtrl.locationManager startUpdatingLocation];
> 
>         // Setup the XMPP stream
> 
>       [self setupStream];
> 
>           return YES;
>     }
> 
>     - (void)dealloc
>     {
>       [self teardownStream];
>     }
> 
> 
>     - (NSManagedObjectContext *)managedObjectContext_roster
>     {
>       return [xmppRosterStorage mainThreadManagedObjectContext];
>     }
> 
>     - (NSManagedObjectContext *)managedObjectContext_capabilities
>     {
>       return [xmppCapabilitiesStorage mainThreadManagedObjectContext];
>     }
> 
> 
>     - (void)setupStream
>     {
>       NSAssert(xmppStream == nil, @"Method setupStream invoked multiple times");
> 
>       // Setup xmpp stream
>       //
>       // The XMPPStream is the base class for all activity.
>       // Everything else plugs into the xmppStream, such as modules/extensions and delegates.
> 
>       xmppStream = [[XMPPStream alloc] init];
> 
>     #if !TARGET_IPHONE_SIMULATOR
>       {
>           // Want xmpp to run in the background?
>           //
>           // P.S. - The simulator doesn't support backgrounding yet.
>           //        When you try to set the associated property on the simulator, it simply fails.
>           //        And when you background an app on the simulator,
>           //        it just queues network traffic til the app is foregrounded again.
>           //        We are patiently waiting for a fix from Apple.
>           //        If you do enableBackgroundingOnSocket on the simulator,
>           //        you will simply see an error message from the xmpp stack when it fails to set the property.
> 
>           xmppStream.enableBackgroundingOnSocket = YES;
>       }
>     #endif
> 
>       // Setup reconnect
>       //
>       // The XMPPReconnect module monitors for "accidental disconnections" and
>       // automatically reconnects the stream for you.
>       // There's a bunch more information in the XMPPReconnect header file.
> 
>       xmppReconnect = [[XMPPReconnect alloc] init];
> 
>       // Setup roster
>       //
>       // The XMPPRoster handles the xmpp protocol stuff related to the roster.
>       // The storage for the roster is abstracted.
>       // So you can use any storage mechanism you want.
>       // You can store it all in memory, or use core data and store it on disk, or use core data with an in-memory store,
>       // or setup your own using raw SQLite, or create your own storage mechanism.
>       // You can do it however you like! It's your application.
>       // But you do need to provide the roster with some storage facility.
> 
>       xmppRosterStorage = [[XMPPRosterCoreDataStorage alloc] init];
>         //    xmppRosterStorage = [[XMPPRosterCoreDataStorage alloc] initWithInMemoryStore];
> 
>       xmppRoster = [[XMPPRoster alloc] initWithRosterStorage:xmppRosterStorage];
> 
>       xmppRoster.autoFetchRoster = YES;
>       xmppRoster.autoAcceptKnownPresenceSubscriptionRequests = YES;
> 
>       // Setup vCard support
>       //
>       // The vCard Avatar module works in conjuction with the standard vCard Temp module to download user avatars.
>       // The XMPPRoster will automatically integrate with XMPPvCardAvatarModule to cache roster photos in the roster.
> 
>       xmppvCardStorage = [XMPPvCardCoreDataStorage sharedInstance];
>       xmppvCardTempModule = [[XMPPvCardTempModule alloc] initWithvCardStorage:xmppvCardStorage];
> 
>       xmppvCardAvatarModule = [[XMPPvCardAvatarModule alloc] initWithvCardTempModule:xmppvCardTempModule];
> 
>       // Setup capabilities
>       //
>       // The XMPPCapabilities module handles all the complex hashing of the caps protocol (XEP-0115).
>       // Basically, when other clients broadcast their presence on the network
>       // they include information about what capabilities their client supports (audio, video, file transfer, etc).
>       // But as you can imagine, this list starts to get pretty big.
>       // This is where the hashing stuff comes into play.
>       // Most people running the same version of the same client are going to have the same list of capabilities.
>       // So the protocol defines a standardized way to hash the list of capabilities.
>       // Clients then broadcast the tiny hash instead of the big list.
>       // The XMPPCapabilities protocol automatically handles figuring out what these hashes mean,
>       // and also persistently storing the hashes so lookups aren't needed in the future.
>       //
>       // Similarly to the roster, the storage of the module is abstracted.
>       // You are strongly encouraged to persist caps information across sessions.
>       //
>       // The XMPPCapabilitiesCoreDataStorage is an ideal solution.
>       // It can also be shared amongst multiple streams to further reduce hash lookups.
> 
>       xmppCapabilitiesStorage = [XMPPCapabilitiesCoreDataStorage sharedInstance];
>         xmppCapabilities = [[XMPPCapabilities alloc] initWithCapabilitiesStorage:xmppCapabilitiesStorage];
> 
>         xmppCapabilities.autoFetchHashedCapabilities = YES;
>         xmppCapabilities.autoFetchNonHashedCapabilities = NO;
> 
>       // Activate xmpp modules
> 
>       [xmppReconnect         activate:xmppStream];
>       [xmppRoster            activate:xmppStream];
>       [xmppvCardTempModule   activate:xmppStream];
>       [xmppvCardAvatarModule activate:xmppStream];
>       [xmppCapabilities      activate:xmppStream];
> 
>       // Add ourself as a delegate to anything we may be interested in
> 
>       [xmppStream addDelegate:self delegateQueue:dispatch_get_main_queue()];
>       //[xmppRoster addDelegate:self delegateQueue:dispatch_get_main_queue()];
> 
>       // Optional:
>       //
>       // Replace me with the proper domain and port.
>       // The example below is setup for a typical google talk account.
>       //
>       // If you don't supply a hostName, then it will be automatically resolved using the JID (below).
>       // For example, if you supply a JID like 'user@quack.com/rsrc'
>       // then the xmpp framework will follow the xmpp specification, and do a SRV lookup for quack.com.
>       //
>       // If you don't specify a hostPort, then the default (5222) will be used.
> 
>         //    [xmppStream setHostName:@"talk.google.com"];
>         //    [xmppStream setHostPort:5222];
> 
>         [xmppStream setHostName:SERVER_HOST];
>         [xmppStream setHostPort:SERVER_PORT];
>       // You may need to alter these settings depending on the server you're connecting to
>       allowSelfSignedCertificates = YES;
>       allowSSLHostNameMismatch = YES;
>     }
> 
>     - (void)teardownStream
>     {
>       [xmppStream removeDelegate:self];
>       [xmppRoster removeDelegate:self];
> 
>       [xmppReconnect         deactivate];
>       [xmppRoster            deactivate];
>       [xmppvCardTempModule   deactivate];
>       [xmppvCardAvatarModule deactivate];
>       [xmppCapabilities      deactivate];
> 
>       [xmppStream disconnect];
> 
>       xmppStream = nil;
>       xmppReconnect = nil;
>         xmppRoster = nil;
>       xmppRosterStorage = nil;
>       xmppvCardStorage = nil;
>         xmppvCardTempModule = nil;
>       xmppvCardAvatarModule = nil;
>       xmppCapabilities = nil;
>       xmppCapabilitiesStorage = nil;
>     }
> 
>     // It's easy to create XML elments to send and to read received XML elements.
>     // You have the entire NSXMLElement and NSXMLNode API's.
>     //
>     // In addition to this, the NSXMLElement+XMPP category provides some very handy methods for working with XMPP.
>     //
>     // On the iPhone, Apple chose not to include the full NSXML suite.
>     // No problem - we use the KissXML library as a drop in replacement.
>     //
>     // For more information on working with XML elements, see the Wiki article:
>     // https://github.com/robbiehanson/XMPPFramework/wiki/WorkingWithElements
> 
>     - (void)goOnline
>     {
>       XMPPPresence *presence = [XMPPPresence presence]; // type="available" is implicit
> 
>       [[self xmppStream] sendElement:presence];
>     }
> 
>     - (void)goOffline
>     {
>       XMPPPresence *presence = [XMPPPresence presenceWithType:@"unavailable"];
> 
>       [[self xmppStream] sendElement:presence];
>     }
> 
>     - (BOOL)connect
>     {
>       if (![xmppStream isDisconnected]) {
>           return YES;
>       }
> 
>       NSString *myJID = [[NSUserDefaults standardUserDefaults] stringForKey:@"userId"];
>       NSString *myPassword = [[NSUserDefaults standardUserDefaults] stringForKey:@"password"];
>         myJID = [NSString stringWithFormat:@"%@@%@", myJID, SERVER_HOST];
>       //
>       // If you don't want to use the Settings view to set the JID,
>       // uncomment the section below to hard code a JID and password.
>       //
>       // myJID = @"user@gmail.com/xmppframework";
>       // myPassword = @"";
> 
>       if (myJID == nil || myPassword == nil) {
>           return NO;
>       }
> 
>       [xmppStream setMyJID:[XMPPJID jidWithString:myJID]];
>       password = myPassword;
> 
>       NSError *error = nil;
>       if (![xmppStream connectWithTimeout:XMPPStreamTimeoutNone error:&error])
>       {
>           UIAlertView *alertView = [[UIAlertView alloc] initWithTitle:@"Error connecting"
>                                                               message:@"See console for error details."
>                                                              delegate:nil
>                                                     cancelButtonTitle:@"Ok"
>                                                     otherButtonTitles:nil];
>           [alertView show];
> 
>           DDLogError(@"Error connecting: %@", error);
> 
>           return NO;
>       }
> 
>       return YES;
>     }
> 
>     - (void)disconnect
>     {
>       [self goOffline];
>       [xmppStream disconnect];
>     }
> 
> 
>     - (void)applicationDidEnterBackground:(UIApplication *)application
>     {
>       // Use this method to release shared resources, save user data, invalidate timers, and store
>       // enough application state information to restore your application to its current state in case
>       // it is terminated later.
>       //
>       // If your application supports background execution,
>       // called instead of applicationWillTerminate: when the user quits.
> 
>       DDLogVerbose(@"%@: %@", THIS_FILE, THIS_METHOD);
> 
>     #if TARGET_IPHONE_SIMULATOR
>       DDLogError(@"The iPhone simulator does not process background network traffic. "
>                  @"Inbound traffic is queued until the keepAliveTimeout:handler: fires.");
>     #endif
> 
>       if ([application respondsToSelector:@selector(setKeepAliveTimeout:handler:)])
>       {
>           [application setKeepAliveTimeout:600 handler:^{
> 
>               DDLogVerbose(@"KeepAliveHandler");
> 
>               // Do other keep alive stuff here.
>           }];
>       }
>     }
> 
>     - (void)applicationWillEnterForeground:(UIApplication *)application
>     {
>       DDLogVerbose(@"%@: %@", THIS_FILE, THIS_METHOD);
>     }
> 
> 
>     - (void)xmppStream:(XMPPStream *)sender socketDidConnect:(GCDAsyncSocket *)socket
>     {
>       DDLogVerbose(@"%@: %@", THIS_FILE, THIS_METHOD);
>     }
> 
>     - (void)xmppStream:(XMPPStream *)sender willSecureWithSettings:(NSMutableDictionary *)settings
>     {
> 
>     }
> 
>     - (void)xmppStreamDidSecure:(XMPPStream *)sender
>     {
>       DDLogVerbose(@"%@: %@", THIS_FILE, THIS_METHOD);
>     }
> 
>     - (void)xmppStreamDidConnect:(XMPPStream *)sender
>     {
>       DDLogVerbose(@"%@: %@", THIS_FILE, THIS_METHOD);
> 
>       isXmppConnected = YES;
> 
>       NSError *error = nil;
> 
>       if (![[self xmppStream] authenticateWithPassword:password error:&error])
>       {
>           DDLogError(@"Error authenticating: %@", error);
>       }
>     }
> 
>     - (void)xmppStreamDidAuthenticate:(XMPPStream *)sender
>     {
>       DDLogVerbose(@"%@: %@", THIS_FILE, THIS_METHOD);
> 
>       [self goOnline];
>     }
> 
>     - (void)xmppStream:(XMPPStream *)sender didNotAuthenticate:(NSXMLElement *)error
>     {
>       DDLogVerbose(@"%@: %@", THIS_FILE, THIS_METHOD);
>     }
> 
>     - (BOOL)xmppStream:(XMPPStream *)sender didReceiveIQ:(XMPPIQ *)iq
>     {
>       DDLogVerbose(@"%@: %@", THIS_FILE, THIS_METHOD);
> 
>       return NO;
>     }
> 
>     - (void)xmppStream:(XMPPStream *)sender didReceiveMessage:(XMPPMessage *)message
>     {
> 
>     }
> 
>     - (void)xmppStream:(XMPPStream *)sender didReceivePresence:(XMPPPresence *)presence
>     {
> 
> 
>     }
> 
>     - (void)xmppStream:(XMPPStream *)sender didReceiveError:(id)error
>     {
>       DDLogVerbose(@"%@: %@", THIS_FILE, THIS_METHOD);
>     }
> 
>     - (void)xmppStreamDidDisconnect:(XMPPStream *)sender withError:(NSError *)error
>     {
>       DDLogVerbose(@"%@: %@", THIS_FILE, THIS_METHOD);
> 
>       if (!isXmppConnected)
>       {
>           DDLogError(@"Unable to connect to server. Check xmppStream.hostName");
>       }
>     }
> ```

**Comment by habiburrahuman** [comment]
Hi,

Thanks for your XMPP Framework. 
I am facing same issue.. Server is ejabberd.. running in macbook pro same machine. trying this 
application in simulator. 
Error Domain=kCFStreamErrorDomainNetDB Code=8 "nodename nor servname provided, or not known" UserInfo=0x7fd7c8511b90 {NSLocalizedDescription=nodename nor servname provided, or not known}
facing this issue..

[xmppStream setHostName:@"habiburs-macbook-pro.local"];
	[xmppStream setHostPort:5222];
i have gave a correct hostname and port

is it XMPP wont work in simulator??


Thanks

**Comment by chinnuios** [comment]
@zelin  @ObjColumnist  I'M also facing same issue but i 'm using 5222 port still some times my app is not connecting how to reconnect again

**Comment by shashank-rps** [comment]
HI,

I am disconnecting chat connection when my goes to background and reconnecting when it comes to foreground. But if I do this background foreground task one after other quickly, my app crashes everytime at:  
`- (id)initWithRosterStorage:(id <XMPPRosterStorage>)storage dispatchQueue:(dispatch_queue_t)queue  
{  
	NSParameterAssert(storage != nil);  
        //.................code continues..............//  
}`  

Somehow `xmppRosterStorage = [[XMPPRosterCoreDataStorage alloc] init];` is returning nil. Any help? @ObjColumnist  @zelin
