### ISSUE TITLE
Slow initial connection

### ISSUE THREAD

**Issue by NasserAlmanji** [robbiehanson/XMPPFramework#303]
Connecting the iPhone demo to a local OpenFire takes 7-10 seconds?
Is this natural or does it trigger un-necessary steps (at least for testing purposes)?

**Comment by hermannkuschke** [comment]
Hi, 

We have the same problem but the host name has been set. Any other ideas? Thank you in advance.

**Comment by Usman4Github** [comment]
Hi we are having same connection time 7-8 seconds....
host name is set...
can you please suggestion any thing



```
xmppStream.hostName = "host_name_added"
            xmppStream.myJID = XMPPJID.init(string: jabberID)
            
            do {
                try xmppStream.connect(withTimeout: XMPPStreamTimeoutNone)
                print("Connection request sent")
              
                return true
            } catch {
                print("Something went wrong!")
                
                return false
            }
```
