### ISSUE TITLE
kCFStreamErrorDomainSSL error -9809 on setup

### ISSUE THREAD

**Issue by hohl** [robbiehanson/XMPPFramework#315]
Connecting has worked for a while, but now I get the following error message without having changed anything: 

`Error Domain=kCFStreamErrorDomainSSL Code=-9809 "The operation couldn’t be completed. (kCFStreamErrorDomainSSL error -9809.)" UserInfo=0x16e2b950 {NSLocalizedRecoverySuggestion=Error code definition can be found in Apple's SecureTransport.h}`

The error is passed to `xmppStreamDidDisconnect:withError:` nearly instantly after setup and without calling any other delegate method.

I'm connecting to a self-hosted Openfire 3.9.1 XMPP server (using SSL with a VeriSign trusted SSL certificate) which should work fine since connecting with other XMPP clients (like Adium) works fine.

Any idea what is going wrong?

**Comment by awanglilong** [comment]
I have the same problem

**Comment by eigar6815** [comment]
[self.xmppStream startTLSPolicy];

- (void)xmppStream:(XMPPStream *)sender willSecureWithSettings:(NSMutableDictionary *)settings
{
    [settings setObject:@YES forKey:(NSString *)GCDAsyncSocketManuallyEvaluateTrust];
}
