### ISSUE TITLE
How to ensure the XMPP message sent to the server?

### ISSUE THREAD

**Issue by shenqiliang** [robbiehanson/XMPPFramework#34]
I am building an iOS app based on XMPP. When I send an XMPP message form client via XMPPFramework, I found the message of the delegate called instantly.
- (void)xmppStream:(XMPPStream *)sender didSendMessage:(XMPPMessage *)message

But my message contains lots of data, I am sure it can not send so fast. Then the user put the app to background, and the message is lost. How to solve this problem? Please help me.

**Comment by rocxteady** [comment]
Bot 0184 and 0085 are irrelevant to the question. Both are client based protocols.

I could not find any protocol to handle this situation and I wonder how the other applications do this. When a client send a message, if the receive is not online yet, how will the client know the status of the message? I receive if it fails but I also want to get notified if the message is successfully sent to the server.

😞

**Comment by Jeyhey** [comment]
The solution is easy: use stream management:
- enable stream management
- set request ack for every message sent `(automaticallyRequestAcksAfterStanzaCount(1,` orTimeout: 10))
- implement func `xmppStreamManagement(sender: XMPPStreamManagement!, didReceiveAckForStanzaIds ids: NSArray) {}` in your connection delegate
- when this function is called mark message with id in `ids` as sent to server

**Comment by manishvpatel** [comment]
hello jeyhey,

didReceiveAckForStanzaIds is calling repeatedly when I call a automaticallyRequestAcksAfterStanzaCount once a message has sent.

Do we need to call this message every time when sending message? If so then why does it's delegate gets calls repeatedly.

Can you please let me know how exactly do I need to code?

Thanks in advanced.

**Comment by Rajai-Sunnyclock** [comment]
> The solution is easy: use stream management:
> 
> * enable stream management
> * set request ack for every message sent `(automaticallyRequestAcksAfterStanzaCount(1,` orTimeout: 10))
> * implement func `xmppStreamManagement(sender: XMPPStreamManagement!, didReceiveAckForStanzaIds ids: NSArray) {}` in your connection delegate
> * inside this function mark message with id in `ids` as sent to server

@Jeyhey How do I know which ID belongs to which message?
