### ISSUE TITLE
How to fix namespace warning xmlns uri vcard-temp is not absolute?

### ISSUE THREAD

**Issue by leolicai** [robbiehanson/XMPPFramework#345]
Aways log out this message.
namespace warning xmlns uri vcard-temp is not absolute

Who known how to fix it?

Thanks

**Comment by githubdbbest** [comment]
this string logging on this string self.vCardTempRel.vCardTemp = vCardTemp;

**Comment by L05t** [comment]
When I want to get a vCard from XMPP, it appears this problem, and the callback is not executed.

**Comment by hermannkuschke** [comment]
L05t I have the same problem as you. Does anyone have an elegant solution for this? I will keep digging. It seems like I can't just ignore it because the vcard for the user doesn't get retrieved when that happens.

**Comment by JDModi** [comment]
Same Problem Any Solution?

**Comment by shravanteegala** [comment]
Iam Faceing same problem .
Any  one give solution

**Comment by lechium** [comment]
You can build your own libxml2.a file after making some minor modifications to parser.c, or you can use my fork of libxml and use my prebuilt version OR build it yourself from afformention fork

https://github.com/lechium/libxml2/blob/master/README.IOS

if you are curious of the nitty gritty of what i did (which you should be!) 

https://github.com/lechium/libxml2/commit/9d503154e1cce1c3db68a0ccda49ed71860d992b
