### ISSUE TITLE
XEP-0016 not able to delete privacy list

### ISSUE THREAD

**Issue by jslim89** [robbiehanson/XMPPFramework#346]
I'm using the function [here](https://github.com/robbiehanson/XMPPFramework/blob/master/Extensions/XEP-0016/XMPPPrivacy.h#L147) by setting the **items** to `nil`

``` obj-c
- (void)unblockUser:(NSString *)jid
{
    if (_xmppPrivacy == nil) return;

    NSString *listName = @"BlockList";

    NSArray *existingItems = [_xmppPrivacy listWithName:listName];
    NSMutableArray *items = [NSMutableArray array];
    int itemCount = existingItems == nil ? 0 : (int)[existingItems count];

    if (itemCount > 0) {
        for (NSXMLElement *item in existingItems) {
            NSString *pid = [item attributeForName:@"value"].stringValue;
            if ([jid isEqualToString:pid]) continue;

            [items addObject:[item copy]];
        }
    }
    if ([items count] > 0) {
        [_xmppPrivacy setListWithName:listName items:items];
        [_xmppPrivacy setDefaultListName:listName];
        [_xmppPrivacy setActiveListName:listName];
    } else {
        [_xmppPrivacy setListWithName:listName items:nil]; // THIS LINE
    }
    [_xmppPrivacy retrieveListWithName:listName];
}
```

If there are 2 blocked users, I unblock 1 of them, then it works. The problem is I want to remove the **last user** in the list, then I should remove the whole list. Unfortunately it not works.

Is this a bug?

**Comment by alessioarsuffi** [comment]
Hi, i'm having same problem, firstly i do:

    [_privacy setActiveListName:nil];

to decline use of active list, than:

    [_privacy setListWithName:kDefaultPrivacyListName items:nil];

to delete list, but it is not working, any ideas why?

**Comment by vishaldeshai** [comment]
@jslim89 Can you paste Block user code?

thanks in advance.

**Comment by jslim89** [comment]
@vishaldeshai sorry about that, the code is no longer with me. It has been 2 years+ already, I can't really remember how I did that.
