### ISSUE TITLE
XEP-0313 Extension Request

### ISSUE THREAD

**Issue by diegostamigni** [robbiehanson/XMPPFramework#348]
This support remote server message archiving. It works, I mean, the messages will be archived on a server that support this features. But what about the sync between the local archive and server one ?

**Comment by licx** [comment]
+1

**Comment by nguyenchiencong** [comment]
Anything new on this?

**Comment by neste2015** [comment]
Want this feature too. Has anybody tried to implement it?

**Comment by Arslan007** [comment]
Any Progress on this ?

**Comment by chrisballinger** [comment]
Fixed in #733
