### ISSUE TITLE
Can't get user nickname by XMPPUserCoreDataStorageObject

### ISSUE THREAD

**Issue by xieweizhi** [robbiehanson/XMPPFramework#353]
Hey guys , i got problem getting user's nickname by the following code:

```
XMPPUserCoreDataStorageObject *user = [chatDelegate.xmppRosterStorage userForJID:[XMPPJID jidWithString:userJID ]
                                                                          xmppStream:chatDelegate.xmppStream
                                                   managedObjectContext:[chatDelegate managedObjectContext_roster]];
```

The XMPPStream  is  connected and userJID is correct , then why i got  nil `user` ?

Thanks in advance? : ]

**Comment by jay12345** [comment]
Hello ,
    I am not getting nickname. All data are download completely.
    Please help me out.
    
    Code is here :
    XMPPUserCoreDataStorageObject *user = [[self fetchedResultsController] objectAtIndexPath:indexPath];
    
    NSLog(@"status: %@",[[user primaryResource] status]);
    NSLog(@"user  nickname: %@",[user nickname]);

**Comment by ObjColumnist** [comment]
If you look at the roster item that comes back for that user are you sure it has a nickname?

**Comment by JoseTovar94** [comment]
Hi, to get the list of friends I am using the following.

` func xmppRosterDidEndPopulating(_ sender: XMPPRoster) {
        if let jids = xmppRoster.xmppRosterStorage.jids(for: stream) as? [XMPPJID] {
            print("JIDS: \(String(describing: jids))")
            for item in jids {
                print(item.user)
            }
        }
    }`

get the user, but I want to get my friend's Nickname.

how can I do?
