### ISSUE TITLE
How to know the message has been saved to database ?

### ISSUE THREAD

**Issue by sharp** [robbiehanson/XMPPFramework#382]
I can not fetch the new message from database in `- (void)xmppStream:(XMPPStream *)sender didReceiveMessage:(XMPPMessage *)message;`, and I need sleep some seconds to fetch the latest records.

**Comment by marioacarvalho** [comment]
@sharp @ObjColumnist I need to do this but I can't for some reason.

Wrote this down but nothing 'fires':

`[[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(contextSaved:) name:NSManagedObjectContextDidSaveNotification object:[self.messageArchivingStorage mainThreadManagedObjectContext]];`

**Comment by ObjColumnist** [comment]
I haven't used the XMPPFramework for a while but the main thread context never saves, just the worker one.
