### ISSUE TITLE
How get Nickname and picture implementing XEP-0054

### ISSUE THREAD

**Issue by KeyideasGlobal** [robbiehanson/XMPPFramework#389]
Hi,
    Plz tell me how i get my friends nic name and picture in when they are offline also in obj c

Thanks in Adv
Mahendra

**Comment by GPF253904828** [comment]
![135e123a-a03e-40bb-aea0-7a906e005c43](https://cloud.githubusercontent.com/assets/8220675/15465044/2a87d470-2105-11e6-9c25-5205fec18b63.png)
I use the [xmppvCardTempModule myvCardTemp], did not enter the delegate methods ,
