### ISSUE TITLE
XMPPStream:didReceiveMessage hangs forever when running on iPhone 5S, ios 7.1.2

### ISSUE THREAD

**Issue by mikewang23** [robbiehanson/XMPPFramework#422]
When receiving a message from someone, XMPPStream:didReceiveMessage hangs due to the call of the following:

```objc
XMPPUserCoreDataStorageObject *user = [xmppRosterStorage userForJID:[message from]
		                                                         xmppStream:xmppStream
		                                               managedObjectContext:[self managedObjectContext_roster]];
```
Looking at the following call stack, it seems the UI is blocked due to waiting for the storageQueue, and so is Thread 17 waiting for storageQueue.  Thread 9 is in the storageQueue and wait for the moduleQueue.  After printing moduleQueue: it shows that the moduleQueue is locked = 1.  In the call stack, there is no thread showing running in the moduleQueue, so not sure why it is locked.  This can only reproduce in iphone 5s, iOS 7 .1.2.  It is fine when running in the simulator.  
```
po moduleQueue
<OS_dispatch_queue: XMPPRoster[0x1700dfc60] = { xrefcnt = 0x6, refcnt = 0x2, suspend_cnt = 0x0, locked = 1, target = com.apple.root.default-overcommit-priority[0x191cbfcc0], width = 0x0, running = 0x0, barrier = 1 }>



Thread1
main-thread:
*trap and wait for the storageQueue
[XMPPCoreDataStorage myJIDForXMPPStream:]
[XMPPRosterCoreDataStorage userforJID:]
[xmppStream:didReceiveMessage]


Thread 9:
Queue:XMPPRosterCoreDataStorage
*trap and wait for the moduleQueue and running in the storageQueue
[XMPPRoster allowRosterlessOperation]
[XMPPRosterCoreDataStorage handlePresence]
[XMPPCoreDataStorage scheduleBlock:]


Thread 17
Queue:XMPPRoster
*trap and wait for the storage Queue
[XMPPCoreDataStorage executeBlock:]
[XMPPRoster CoreDataStorage userExistsWithJID:]
[XMPPRoster xmppStream:didReceivePresence:[
``

**Comment by maradkar** [comment]
Hey Hi , actually in my app i was trying to fetch roster using xmppframework , but app getting hang each time when it trying to execute following line of code 
- (NSManagedObjectContext *)mainThreadManagedObjectContext
{
	// NSManagedObjectContext is NOT thread-safe.
	// Therefore it is VERY VERY BAD to use this managedObjectContext outside the main thread.
	// 
	// You should NOT remove the assert statement below!
	// 
	// When you want a managedObjectContext of your own for non-main-thread use,
	// you should create your own using the public persistentStoreCoordinator.
	// 
	// If you even comtemplate ignoring this warning,
	// then you need to go read the documentation for core data,
	// specifically the section entitled "Concurrency with Core Data".
	// 
	NSAssert([NSThread isMainThread], @"Context reserved for main thread only");
	// 
	// Do NOT remove the assert statment above!
	// Read the comments above!
	// 
	
	if (mainThreadManagedObjectContext)
	{
		return mainThreadManagedObjectContext;
	}
	
	NSPersistentStoreCoordinator *coordinator = [self persistentStoreCoordinator]; (app get hang on this line).
Can you please help me to solve that ...... Many many thanks
