### ISSUE TITLE
Socket closed by remote peer error ios 8

### ISSUE THREAD

**Issue by ilosqut** [robbiehanson/XMPPFramework#438]
I am tried to connect to jabber.org server, so I setup in a iPhoneXMPP example:
 [xmppStream setHostName:@"jabber.org"]; and started app on the iPhone 5s.

On the server side I see logs:
Connection accepted,
but after that I see error @"GCDAsyncSocketErrorDomain" - code: 7 : "Socket closed by remote peer"
in the:

``` objc
- (void)xmppStreamDidDisconnect:(XMPPStream *)sender withError:(NSError *)error.
```

I tried to setup AutoPing, Ping but nothing helps.

**Comment by Lorelei89** [comment]
Hi 
I'm having the same issue,I've verified my JID and the password if they are correct and it seems that they are ,but i get the same error.I'm connected to an HostName with IP, few days ago it was working but right now the XMPP server is disconnecting even if i put the right parameeter to connect to the server.Is anyone have any idea about this issue? Did something change on XMPP?
Kind regards
