### ISSUE TITLE
cocoapods

### ISSUE THREAD

**Issue by hansaaaaa** [robbiehanson/XMPPFramework#474]
Is this library suitable for cocoapods? if so, it would be really nice to make it available via this option!

Cheers,

C

**Comment by nikitaUnii** [comment]
@hansaaaaa how did you do it? Even I want the same thing..

**Comment by hansaaaaa** [comment]
Unfortunately, I don't remember, and I don't have the project anymore, we have migrated to quickblox/parse as a back-end.

Maybe try installing it the "non-cocoapods-way" (https://github.com/robbiehanson/XMPPFramework/wiki/GettingStarted_iOS). I think that worked for me. If you want it for Mac, not iOS, try https://github.com/robbiehanson/XMPPFramework/wiki/GettingStarted_Mac.

Good Luck!

**Comment by nikitaUnii** [comment]
done! thanks!
