### ISSUE TITLE
Cannot use this library because of circular dependency

### ISSUE THREAD

**Issue by Ricardo1980** [robbiehanson/XMPPFramework#478]
Hello!
My pod file is 
'''
inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'XMPPFramework', '~> 3.6'
'''
However when I try to launch "pod update" I receive:
"[!] There is a circular dependency between XMPPFramework/Utilities and XMPPFramework/Core"

Do you know how I can fix that?
Thanks

**Comment by ObjColumnist** [comment]
I would have a look at this thread http://stackoverflow.com/questions/26810872/cocoapods-circular-dependency-issue

We don't own/maintain/officially support Cocoa Pods for the XMPPFramework though.
