### ISSUE TITLE
Do you know if XMPP server store the single conversations messages? (one-one conversation)

### ISSUE THREAD

**Issue by MoralAlberto** [robbiehanson/XMPPFramework#484]
I know that rooms' messages are saved In XMPP Server, because when I connect on my server and I query about my persistent rooms, the server gives me a response with all the items (rooms). Then I join them again and I automatically receive the last 50 messages.

But, is there any way to get the last X messages of all my single conversations? 

Thanks in advance!

**Comment by ObjColumnist** [comment]
Depends on the server configuration, they might support XEP- 0136 http://xmpp.org/extensions/xep-0136.html and/or XEP-0313 http://xmpp.org/extensions/xep-0313.

Typically most public servers don't though.

**Comment by MoralAlberto** [comment]
Thanks a lot!
