### ISSUE TITLE
namespace warning : xmlns: URI vcard-temp is not absolute

### ISSUE THREAD

**Issue by zhangyuchang1** [robbiehanson/XMPPFramework#487]
I try to get one user's vcard ,sometimes it happens :

namespace warning : xmlns: URI vcard-temp is not absolute
<vCard xmlns="vcard-temp"><PHOTO><TYPE>image/jpeg</TYPE><BINVAL>iVBORw0KGgoAAAAN
                         ^

**Comment by stpeter** [comment]
Yeah, we created that XML namespace name in the ancient days before we understood the xmlns constraints. :(

**Comment by ObjColumnist** [comment]
Duplicate of #100
Duplicate of #345
