### ISSUE TITLE
How to reference XMPPRoomCoreDataStorage instance?

### ISSUE THREAD

**Issue by dimefim** [robbiehanson/XMPPFramework#489]
Good morning. This is not an issue really, but I've faced tiny problem with XMPPRoomCoreDataStorage instances. We have there two initializers: sharedInstance and by fileName with storeOptions. I need to perform request to core data storage. I understand I am going to use mainThreadObjectContext. But how to get the storage I've created at past? With UIManagedDocument we have method like "openFileWithCompletionHandler...". Any similar function in this case or am I missing something? By the way, in case of singleton database file is rewritten every time an app launches although the default value  autoRemovePreviousDatabaseFile is NO as per docs. Am I missing something again? Thank you in advance.

**Comment by dimefim** [comment]
Any thoughts on this? I am sure this is quite simple to solve.

**Comment by dimefim** [comment]
Any thoughts on this? I am sure it's pretty easy to solve...

**Comment by ObjColumnist** [comment]
I haven't used `XMPPRoomCoreDataStorage` myself, but it clears all occupants for a room in `didCreateManagedObjectContext`, which is separate to `autoRemovePreviousDatabaseFile` 

```objc
- (void)didCreateManagedObjectContext
{
	XMPPLogTrace();
	
	[self clearAllOccupantsFromRoom:nil];
} 
```
This is strictly correct as an occupant leaves a room upon becoming unavailable.

In terms of getting the same storage you created in the past, you just need to supply the same path to the initializer.

**Comment by dimefim** [comment]
@ObjColumnist , thank you for response!
>In terms of getting the same storage you created in the past, you just need to supply the same path to the initializer.

Did you mean the path to actual SQLite file? I did not get "initializer" word.

**Comment by ObjColumnist** [comment]
Yeah, the databaseFileName

**Comment by dimefim** [comment]
@ObjColumnist ,but the question is how am I going to **open** previously created database file in order to get mainThreadManagedObjectContext? I see only initializers in XMPPCoreDataStorage.h. Some sort of     
       `XMPPCoreDataStorage *storage  = [XMPPCoreDataStorage openWithDatabaseFilename: (NSString*)filename];?`

**Comment by dimefim** [comment]
You see, I want user's data to be persistent, I can't create every time new database which will work only for one lifecycle of an app. I thought of singleton but sharedInstance creates new database from launch to launch. Even if autoRemovePreviousDatabaseFile specified to NO.

**Comment by ObjColumnist** [comment]
This is because it internally it `clearAllOccupantsFromRoom` as you have gone unavailable and the specification says:

```
An occupant exits a room by sending presence of type "unavailable" to its current <room@service/nick>.
```

I understand that this might not be what you want in your app but it is obeying the specification, whereby as soon as you become unavailable you leave a room. I don't know enough about MUC to know if making this optional would cause any other issues.

**Comment by dimefim** [comment]
@ObjColumnist You absolutely right as this is the behavior I did not expect and did not want. Nevertheless, I found a workaround for this. One last question: I can't find anywhere in XEP description what would happen if all occupants left a room? The room must be destroyed then? Or it will stay on server because ? Thank you in advance.

**Comment by ObjColumnist** [comment]
You have persisted and non persisted rooms. If it's a non persistent room, it is destroyed upon the last person leaving.

How persisted rooms are configured is entirely up a server though, so they can handle situation however they want.

**Comment by dimefim** [comment]
Alright, I appreciate your help very much, it solved my another issue. Thank you.
