### ISSUE TITLE
GCDAyncSocket - socket alive for 10 mins

### ISSUE THREAD

**Issue by guptatarun84** [robbiehanson/XMPPFramework#493]
Want to keep alive the socket connection during reading and writing of a chat session for 10 mins. Any help would be helpful. I am using Xep-0096 for chats transfers along with files.

Regards,
Tarun Gupta

**Comment by ObjColumnist** [comment]
What problem are you seeing currently? The socket should stay alive indefinitely, assuming the Internet connection persists.

**Comment by guptatarun84** [comment]
I dont want the SI message to transfer everytime, while sending chats. To restrict this I want the GCDAsynSocket which is already created to stay alive for 10 mins before closing the connection. So this will read the source everytime and write it to the destination.

**Comment by ObjColumnist** [comment]
You would need to design your own transfer protocol, as this solution wouldn't be compatible with SI.

The socket is only disconnected because it is required by the protocol.

**Comment by guptatarun84** [comment]
is there any other mechanism for restricting SI query to be sent again and again once connection is established?

**Comment by ObjColumnist** [comment]
Not to my knowledge.

**Comment by jonstaff** [comment]
Depending on my understanding of what you're trying to accomplish, the answer is one of two things:

1. You wish to send actual chat messages using the file transfer system—which is wrong.  You should just use the chat functionality built in the core part of the XMPPFramework.
2. You wish to send multiple files without sending multiple SI offers—which is also wrong.  The sender and recipient need to agree on the size of each file transferred and the method by which it will be transferred.

**Comment by guptatarun84** [comment]
Thanks for correcting me jon! I would like you to suggest me the XEP used for P2P chat transfers. That would be really helpful in the course of implementation I am involved in.

**Comment by jonstaff** [comment]
Could you define a *P2P chat transfer*?

**Comment by guptatarun84** [comment]
Simple chat messaging with online users

**Comment by guptatarun84** [comment]
As you suggested to implement chat functionality built in the core part of the XMPPFramework. But I could not able to send P2P chat via this. I know about the Xep-0166(Jingle) but I want to restrict myself to use it for simple P2P messaging. Any help over this is helpful.

**Comment by jonstaff** [comment]
If all you want to do is send a simple chat message with online users, just use the features already built [in the core](https://github.com/robbiehanson/XMPPFramework/tree/master/Core) of the library.

This is pretty well documented in the sample applications.  There's no reason to use Jingle or file transfer XEPs.

**Comment by guptatarun84** [comment]
But i doubt, if built in the core chat messaging support P2P communication.

**Comment by jonstaff** [comment]
If you're looking for instruction or help using some of the components, I recommending posting in the [XMPPFramework Google Group](https://groups.google.com/forum/#!forum/xmppframework) rather than opening an issue.  StackOverflow might also be a better option.

**Comment by guptatarun84** [comment]
Thanks for the extended support! I could able to manage the timeout using readDataWithTimeout:-1. Closing this issue.
