### ISSUE TITLE
In background mode, XMPPAutoPing does not work when pressed home button on device

### ISSUE THREAD

**Issue by monkeyfdude** [robbiehanson/XMPPFramework#498]
* I am trying to make my app work in background with XMPPFramework, but I am not succeeding.
* I am using iOS 7.1/8.1
* I have VOIP enabled
* I have self.xmppStream.enableBackgroundingOnSocket = YES for device
* In foreground, I get logs (it does not allow me write logs as is here)

SEND: ping xmlns="urn:xmpp:ping"
RECV: iq XML="jabber:client" from="user@server.com" to="user@server.com/iPhone" id="some_id" type="result"

But when I press home button on device, I XMPPAutoping stops meaning I dont see anything in logs.
* What else is missing that needs to be done for app to receive messages in background mode.

All of this code is in setupStream provided by the XMPPFramework.

    self.xmppAutoping =  [[XMPPAutoPing alloc]    initWithDispatchQueue:dispatch_get_main_queue()];
    self.xmppAutoping.pingInterval = 25.f; // default is 60
    self.xmppAutoping.pingTimeout = 10.f; // default is 10
    [self.xmppAutoping addDelegate:self delegateQueue:dispatch_get_main_queue()];
    [self.xmppAutoping activate:self.xmppStream];

    self.xmppReconnect = [[XMPPReconnect alloc] init];
    [self.xmppReconnect         activate:self.xmppStream];

Can you please guide me to resolve this issue?

**Comment by monkeyfdude** [comment]
* Please help me understand. I notice on device AutoPing happens at an interval of 10 mins whereas I set pingInterval to 25.f and pingTimeout to 10.
* Also, with setKeepAliveTimeout, I do get network connection lost as I do not receive messages from Server. For eg. in some runs, the stream is not fully connected back.
* But in the next setKeepAliveTimeout run, the stream again gets connected and I start getting messages. Can you please me what could be the reason for this.

Please provide pointers

**Comment by ObjColumnist** [comment]
This is expected behaviour.

When you enable "background socket" mode on XMPPStream, it tells the OS that this is a VoIP Socket and therefore it should not be closed when the app is put to the background, but the app is suspended so AutoPing cannot run.

I'm guessing 10 minutes corresponds to the keepalive interval that you set, which is when the app is next able to execute as it is briefly brought out of its suspended state.

**Comment by monkeyfdude** [comment]
Thank you so much for your response. I have  1 more issue to solve. If you could shed some light on it.

So every 10 mins, I disconnect and re-connect. I see it happening in setKeepAliveTimeout handler.

* I observe intermittently, XMPPStream is not fully connected back. Even though logs say that stream has connected and authenticated but it can not receive messages when sent from another client. However, in the next cycle of setKeepALiveTime, stream is connected properly and I can receive messages.

Would you know what will cause this and how to fix it?

What would the ideal code for setKeppAliveTimeout handler to keep XMPPStream up. Riight now I do

[self disconnect] and inside xmmpDidDisconnect I do [self connect]

Can I improve on this?

Thanks again for everything!!!!

**Comment by ObjColumnist** [comment]
That's odd that the XMPPFramework is reporting its in the wrong state.

My only suggestion would be to create a background task (using the API on UIApplication) when you call connect, then end the background task after the stream has authenticated. This means that all of the stanzas should of been sent/received and it should be in a consistent state. I suggest this as the authentication process is asynchronous (as it involves the network) so the app might be suspending during this.

**Comment by monkeyfdude** [comment]
Thank you so much for all your suggestions!

**Comment by guptatarun84** [comment]
I followed what you mentioned! Could able to get the stream connected on background expiration, but that works when the device is connected to Xcode. While the app running standalone, it still disconnects in 3 minutes and no connection is made after. I am not supporting any background mode, but would like to stay connected with server for longer duration. Any suggestions?

**Comment by ObjColumnist** [comment]
@guptatarun84 the backgrounded rules are slightly different when a device is plugged in because it has access to infinite power, hence why it works when connected to Xcode.

If you are not using a background mode you won't be allowed to run in the background for longer than a background task, which is measured in seconds.

**Comment by guptatarun84** [comment]
So just to stay connected to server to receive incoming file transfers, I need to enable background mode?  My app don't have support for VoIP. Is there any running mechanism, where I can reconnect XMPP stream while the application is in background state.?

**Comment by ObjColumnist** [comment]
If you need to stay connected while in the background then yes you need to enable a background mode, but as you alluded to Apple will reject your app if you use the VoIP Background Mode without having VoIP in your app.
