### ISSUE TITLE
Deleting database files when user leaves a room

### ISSUE THREAD

**Issue by kartikthapar** [robbiehanson/XMPPFramework#504]
In my setup, I use separate database files for separate rooms (as advised by the guidelines as well). Currently, when the user leaves the room, the database file still persists for some reason. This can be verified by re-inviting the user to the same room. The `initWithDatabaseFileName:storageOptions` method then returns `nil`.

Is this a bug or am I doing something wrong?

**Comment by ObjColumnist** [comment]
It is possibly a bug, but the XMPPCoreDataStorage should unregister the name when it is deallocated (there is code to prevent multiple XMPPCoreDataStorage objects from referencing the same file).

```objc
- (void)dealloc
{
	[[NSNotificationCenter defaultCenter] removeObserver:self];
	
	if (databaseFileName)
	{
		[[self class] unregisterDatabaseFileName:databaseFileName];
	}
	
	#if !OS_OBJECT_USE_OBJC
	if (storageQueue)
		dispatch_release(storageQueue);
	#endif
}
```

```objc
+ (void)unregisterDatabaseFileName:(NSString *)dbFileName
{
	@synchronized(databaseFileNames)
	{
		[databaseFileNames removeObject:dbFileName];
	}
}
```

**Comment by kartikthapar** [comment]
I think the `xmppRoomStorage` object is still being utilized somewhere so it's never really released in the system which is why the unregisterDatabaseFileName internal method is never called in my tests. Not sure if I would treat this as a bug but one would hope that the XMPPRoom's dealloc actually nullifies the memory at `xmppRoomStorage`. Again, not too sure.

**Comment by ObjColumnist** [comment]
Sounds like a bug to me if that is the case, Im guessing it is the room that isn't getting dealloc'd.

**Comment by kartikthapar** [comment]
Yup, looks like the room is not getting deallocated.

**Comment by kartikthapar** [comment]
I am just putting out here as I am wondering if you are somebody has seen something like this —

`dealloc` is not being called for my XMPPRoom object. I have weak references everywhere; I am creating an XMPPRoom object inside a AFNetworking POST call which might be some how retaining its own reference.

1. When I leave the room and assign room=nil, the dealloc for room isn't called.
2. When I leave the room and call deactivate on this room and then assign room=nil, something terribly goes wrong.

**Comment by ObjColumnist** [comment]
So you would need to call deactivate as the XMPPStream retains XMPPModules (the AFNetworking request might also be retaining it).

What happens when you call deactivate?

**Comment by kartikthapar** [comment]
I populate a tableview using ESXMPPRoomCoreDataObject instances (not available as part of the framework) but they are basic abstractions to save room information.

When I don't call deactivate or removeDelegate:, the row disappears just fine (but as we know, the instance is somehow retained somewhere given that the dealloc in XMPPModule is never called.

When I call deactivate or removeDelegate:, the row in the table view doesn't disappear (as if it's some how maintaining a reference to the actual ESXMPPRoomCoreDataStorageObject which is now even more weird).

**Comment by kartikthapar** [comment]
I have understand partly whats going on in part 2 — when I call deactivate and removeDelegate:.

So the issue is: when the user leaves the room, he sends out a presence but then the room deactivates and it never receives that presence. I read the description method for the deactivate API and as it clearly says that: "When this method returns, no further delegate methods on this module will be dispatched."

I believe that in my case, the presence delegate (didReceivePresence) is getting dispatched after this method has returned; as it never breaks after I call leaveRoom on the room object.

**Comment by kartikthapar** [comment]
Thanks Spencer. You may close this (if need be). It looks like that the bug is with my implementation of how I create or leave the room as I have made some adjustments with the original XEP-0045 standard.

**Comment by ObjColumnist** [comment]
OK, glad you got it working :smile:
