### ISSUE TITLE
XML change codification with Special Characters (i.e &#xEB;)

### ISSUE THREAD

**Issue by MoralAlberto** [robbiehanson/XMPPFramework#508]
I'm adding new users to my Roster calling this method:

```- (void)addUser:(XMPPJID *)jid withNickname:(NSString *)optionalName;```

The issue is, when I'm trying to add an user with a special character, the name is codified in the next way:

```
SEND: 
<iq type="set">
<query xmlns="jabber:iq:roster">
<item jid="albertomoral@server.com" name="Alb&#xEB;rto Mor&#xE1;l"/>
</query></iq>
```

I know exactly the point where this happens, within ```XMPPRoster.m``` in method: 

```- (void)addUser:(XMPPJID *)jid withNickname:(NSString *)optionalName groups:(NSArray *)groups subscribeToPresence:(BOOL)subscribe;```

In this snippet, when the attributed name is assigned, the value is codified to hex code

```if (optionalName) {
	[item addAttributeWithName:@"name" stringValue:optionalName];
}```

```optionalName``` has the correct name, but is changed to hex code when item is created.

The correct value name is ```Albërto Morál```, but has been changed to ```Alb&#xEB;rto Mor&#xE1;l```
is there a way to send the correct name or to wrap this value to avoid be modified?

Thanks in advance,

**Comment by ObjColumnist** [comment]
Hi Alberto,

No it has to be encoded to be UTF-8 and XML compliment, but when you retrieve the value it should be automatically decoded?

**Comment by MoralAlberto** [comment]
Hi! There is no problem when I receive an XML from XMPP Server, because as you say it's correctly decoded, the issue is when I add a new user to my Roster with special characters in his/her name, for example when I add an user in my Roster with method:

```- (void)addUser:(XMPPJID *)jid withNickname:(NSString *)optionalName groups:(NSArray *)groups subscribeToPresence:(BOOL)subscribe;```

```optionalName``` has the correct name ```Albërto Morál```, then when I create the ```item```,  with ```[item addAttributeWithName:@"name" stringValue:optionalName];```  the value name has changed. (it's encoded)

an example:
```<item jid="albertomoral@windbox.zyncro.com" name="Alb&#xEB;rto Mor&#xE1;l"></item>```

So, when the server has received this item, it adds this user to my Roster but with not decoded name.  ```Alb&#xEB;rto Mor&#xE1;l```.

When I receive my Roster, I receive this item:

```<item name="Alb&amp;#xEB;rto Mor&amp;#xE1;l" jid="albertomoral@windbox.zyncro.com" subscription="both"/>```

is it a server problem?

thanks in advance!

**Comment by ObjColumnist** [comment]
I would guess so, it looks like it has been encoded twice. Maybe the server is making it safe for displaying in a HTML document?

**Comment by MoralAlberto** [comment]
No lucky trying to solve this issue, the project has also Android and Web version, and they are capable to send accents in their stanzas (they add ```Albërto Morál``` with success in their Roster). I'm the only with this issue. 

I'm still working on that.

**Comment by MoralAlberto** [comment]
Solved in Server side.
