### ISSUE TITLE
UI Frozen dispatch_sync(storageQueue, block);

### ISSUE THREAD

**Issue by monkeyfdude** [robbiehanson/XMPPFramework#526]
Hi,

I get my UI frozen at 		

dispatch_sync(storageQueue, block); in XMPPCoreDataStorage.

Would you be able to tell me the cause of it?

**Comment by ObjColumnist** [comment]
It is likely that the storage queue is waiting on another queue so using dispatch_sync is causing a deadlock.

Typically you get this if you init a module with the main queue, rather than another queue.

**Comment by monkeyfdude** [comment]
Thank you so much for your response. I have been struggling for some time. I took example code from XMPPFramework:

    [self.xmppStream addDelegate:self delegateQueue:dispatch_get_main_queue()];
    [self.xmppRoster addDelegate:self delegateQueue:dispatch_get_main_queue()];
    [self.xmppMUC addDelegate:self delegateQueue:dispatch_get_main_queue()];

I have few clarifications please:

1) Can I change above code to dispatch_get_global_queue or should I use a CUSTOM queue?

2) Would not it cause the same problem (deadlock) with any other queue? What will change if I use custom/global queue instead of main queue? How will that fix the problem. I want/need to understand.

3) I mean I understand UI will not freeze if main queue is not used but the deadlock can still happen with any queue. Right?

4) Also, if you could tell what is the semantics of this queue? Why is this queue needed and why did the example code used main queue instead of global or custom queue?

Thank you again for your response

**Comment by monkeyfdude** [comment]
In Xcode I see:

Thread 1
Queue : com.apple.main-thread (serial)
Thread 2
Queue : com.apple.libdispatch-manager (serial)
Thread 3
Queue : XMPPRoster (serial)
Thread 5
Queue : XMPPRosterCoreDataStorage (serial)

**Comment by ObjColumnist** [comment]
So it is fine to add a delegate with the main queue (this is the typical use case) but you don't want to init modules with the main queue

e.g.
```objc
    self.xmppMUC = [[XMPPMUC alloc] initWithDispatchQueue:dispatch_get_main_queue()];
```

This queue is where all of the processing is done for the module, so you want that to be done off of the main queue.

By having the XMPPMUC module process on the main queue and delegate to the main queue it has created a deadlock. I always init modules with one of the system dispatch queues e.g. `dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0)`

**Comment by monkeyfdude** [comment]
I found this in the "Mastering the XMPPFramework" book and in YDAppDelegate.m. That was the reference code I used
```
    //ch.08
    //ROOM
    
    self.xmppRoomCoreDataStore = [XMPPRoomCoreDataStorage sharedInstance];
    self.xmppMUC = [[XMPPMUC alloc] initWithDispatchQueue:dispatch_get_main_queue()];
    //ch.08
    [self.xmppMUC addDelegate:self delegateQueue:dispatch_get_main_queue()];
```
Would you be able to confirm if it was a bug in the YDChat/Book or not?

**Comment by ObjColumnist** [comment]
It's possible that the issue only arises with certain configurations e.g. Active Modules, Hardware etc so the author didn't see any issues, but it is best practice to not use the main queue for performance reasons above everything else.

So I guess you could say it's a bug or at least not recommended :smile:

**Comment by ObjColumnist** [comment]
Is it OK to close this?
