### ISSUE TITLE
lightweight migration error with multiple core data model files(xcdatamodel)

### ISSUE THREAD

**Issue by cssmhyl** [robbiehanson/XMPPFramework#535]
I user XMPPFrame work by cocoapods:
pod 'XMPPFramework', '3.6.4'

My project has one xcdatamodel and I found several xcdatamodel in xmppframe folder.Now my app has a new version 1.1. The issue arises when upgrading from 1.0 to 1.1.It seems Core Data checks the model store on disk (created by version 1.0) and looks for the model that describes it but is unable to find a SINGLE model that defines the entire store. 
I have more than one model file in my app cause the problem?
How shoud I do?

**Comment by adozenlines** [comment]
Did you modify the models of the framework as part of your development? If you did it would have been better you defined your own models without touching the xmppframework copies.

**Comment by ObjColumnist** [comment]
The XMPPFramework (by default) has a model per storage module, which then creates one persistent store e.g. Roster has a store, Capabilities has a store etc etc

These shouldn't have interfered with your app's model/store unless something imported them.

**Comment by cssmhyl** [comment]
I delete XMPPFramework default model,and that works.
