### ISSUE TITLE
Chat records becomes empty after change device system language

### ISSUE THREAD

**Issue by mcyep** [robbiehanson/XMPPFramework#537]
Hi, good day.

My app localized in multiple language, when user change the device system language, their previous chat history becomes empty.

I found that XMPPCoreDataStorage return a different persistentStoreDirectory when user change their device system language.

**Comment by mcyep** [comment]
in XMPPCoreDataStorage.m
- (NSString *)persistentStoreDirectory 

Line 452:
[[NSBundle mainBundle] objectForInfoDictionaryKey:@"CFBundleDisplayName"] value is different if system language changed (for apps localized in multiple language with different display name)

**Comment by ObjColumnist** [comment]
I agree its a bug, the problem is fixing it might break more apps than it fixes.

Let me have a think.

**Comment by mcyep** [comment]
Suggestion fix with backward compatible
```
- (NSString *)persistentStoreDirectory
{
	NSArray *paths = NSSearchPathForDirectoriesInDomains(NSApplicationSupportDirectory, NSUserDomainMask, YES);
	NSString *basePath = ([paths count] > 0) ? paths[0] : NSTemporaryDirectory();
	NSFileManager *fileManager = [NSFileManager defaultManager];
	
	// For legacy purpose only
	NSString *appName = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"CFBundleDisplayName"];
	NSString *result  = [basePath stringByAppendingPathComponent:appName];
	if ([fileManager fileExistsAtPath:result]) {
		return result;
	}

	// For new application
	appName = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"CFBundleName"];
	result  = [basePath stringByAppendingPathComponent:(appName?appName:@"xmppframework")];
	
	if (![fileManager fileExistsAtPath:result]) {
		[fileManager createDirectoryAtPath:result withIntermediateDirectories:YES attributes:nil error:nil];
	}
	return result;
}
```

**Comment by ObjColumnist** [comment]
I went with Bundle Identifier as Apple has switched to doing this.

Thanks for reporting the issue though :+1:
