### ISSUE TITLE
GNUstep port.

### ISSUE THREAD

**Issue by AlessandroSangiuliano** [robbiehanson/XMPPFramework#551]
Hello, this is not a real issue, but much more a question for information.

I'd like to know if someone of the developers of this great framework considered to do a port on GNUstep.

GNUstep is the Cocoa free reimplementation, the license is LGPL so there are no problems with BSDL, it will be a very usefull port.

Thanks in advice for replies

**Comment by ObjColumnist** [comment]
No plans, but obviously anyone is welcome to fork the project :smile:
