### ISSUE TITLE
[feature] rfc7395 XMPP over WebSocket - implementation

### ISSUE THREAD

**Issue by dodikk** [robbiehanson/XMPPFramework#556]
Does the library support this? I can't find it anywhere - both in the wiki pages and in code.
Is this feature on the project's roadmap?

**Comment by dodikk** [comment]
https://www.rfc-editor.org/rfc/rfc7395.txt
Are there any known implementations of this RFC for iOS?

**Comment by ObjColumnist** [comment]
Hi @dodikk, the XMPPFramework doesn't support using Websockets as a transport (or anything other than a TCP Socket).
I don't know of any other iOS XMPP Implementations that support it either.

**Comment by dodikk** [comment]
Just in case anyone finds it useful. 
I've implemented a web socket client with limited features from scratch. 
https://github.com/healthjoy-ios-opensource/HLJXmppWebSocket
