### ISSUE TITLE
Can not find MACRO  NSAssert

### ISSUE THREAD

**Issue by taojigu** [robbiehanson/XMPPFramework#557]
Hi,robbiehanson

I failed to build the project because The  Macro NSAssert 

For example:
NSAssert(NO, @"Method xmppStream:willSendIQ: is no longer void (see XMPPStream.h). "
						             @"Culprit = %@", NSStringFromClass([del class]));

The error message is : use of undeclared identifer NSAssert

How I can fix it.  

Thank you.

**Comment by ObjColumnist** [comment]
This using one of the sample projects or have you imported the file into your own project?

NSAssert is a standard Objective-C macro though so I am not sure what the problem could be.
