### ISSUE TITLE
Message sent but not received. No response log.

### ISSUE THREAD

**Issue by ain1712** [robbiehanson/XMPPFramework#559]
Hi robbiehanson,

I'm trying to build an instant messaging app. I have successfully connected to the xmpp server and the receiver successfully added to my roster. However, I'm having a problem to send message. I'm pretty confident that the server is working properly as my Android team does not facing the same issue. 

I use below code to send a message. It was located in my viewcontroller.m.

    NSString *testMsg = @"text message";
    
    NSString *toId = @“xxxx@xmpp.myserver.com”;
    NSXMLElement *body = [NSXMLElement elementWithName:@"body" stringValue:testMsg];
    
    XMPPJID *to = [XMPPJID jidWithString:toId];
    XMPPMessage *message = [XMPPMessage messageWithType:@"chat" to:to];
    [message addChild:body];
    
    AppDelegate *appDel = (AppDelegate *)[[UIApplication sharedApplication] delegate];
    [[appDel xmppStream] sendElement:message];

I got the following logs, but the receiver did not receive the message.

     SEND: <message type="chat" to="xxxx@xmpp.myserver.com"><body>text message</body></message>

And that is it. Nothing else. Shouldn't I see something like below response in my log?

RECV: <message ....

Anything that I missed? How can I fix this?

Many thanks!

**Comment by ObjColumnist** [comment]
Looks fine to me, assuming that the JIDs are OK and the stream is connected.

You would only see the RECV log if you recieved any data over the stream.

**Comment by ain1712** [comment]
Any idea how can I ensure the stream is connected at that point of time?

**Comment by ObjColumnist** [comment]
Use isAuthenticated on XMPPStream.

XMPPStream has delegate callbacks for this as well.

**Comment by ain1712** [comment]
Hurm... Is authenticated too.

    AppDelegate *appDel = (AppDelegate *)[[UIApplication sharedApplication] delegate];
    if ([[appDel xmppStream] isAuthenticated])
        NSLog(@"authenticated!");
    else
        NSLog(@"not authenticated.");

Should I be check if anything went wrong with the xmpp server? Anything else that I can do to make it works?

**Comment by ObjColumnist** [comment]
Not sure what you can check on the server, maybe log in with the other user you are sending it to and see if they RECV anything.

**Comment by ain1712** [comment]
I have logged in with the receiver account and confirmed that the message received. Many thanks! 

But as sender, I still did not get any RECV. Any idea why? But yes, xmppStream didSendMessage delegate was called.

**Comment by ObjColumnist** [comment]
You are only going to RECV data if somebody sends you a message (iq or presence) or is that what you mean?
