### ISSUE TITLE
the server does not support inband registration

### ISSUE THREAD

**Issue by pokal4u** [robbiehanson/XMPPFramework#568]
Hi,

I am trying to register new user in openfire uing stophe.js, getting error "the server does not support inband registration".

My code:

$('#connect').bind('click', function () {
	var button = $('#connect').get(0);
	if (button.value == 'connect') {
	    button.value = 'disconnect';
		connection.register.connect("domain.com", errorRgister, 60, 0);
	    connection.connect($('#jid').get(0).value,
			       $('#pass').get(0).value,
			       onConnect);
	} else {
	    button.value = 'connect';
	    connection.disconnect();
	}
    });

function onConnect(status)
{
    if (status == Strophe.Status.CONNECTING) {
		log('Strophe is connecting.');
    } else if (status == Strophe.Status.REGISTER) {
        log("register!");
		connection.register.fields.username = "user";
        connection.register.fields.name = "user1";
        connection.register.fields.password = "pass123";
        connection.register.submit();
		
    } else if (status == Strophe.Status.REGISTERED) {
        log("registered!");
        connection.authenticate();
    } else if (status == Strophe.Status.CONNFAIL) {
		log('Strophe failed to connect.');
		$('#connect').get(0).value = 'connect';
    } else if (status === Strophe.Status.CONFLICT) {
        log("Contact already existed!");
    } else if (status === Strophe.Status.NOTACCEPTABLE) {
        log("Registration form not properly filled out.")
    } else if (status === Strophe.Status.REGIFAIL) {
        log("The Server does not support In-Band Registration")
    } else if (status == Strophe.Status.DISCONNECTING) {
		log('Strophe is disconnecting.');
    } else if (status == Strophe.Status.DISCONNECTED) {
		log('Strophe is disconnected.');
		$('#connect').get(0).value = 'connect';
		$('#connect').click();
    } else if (status == Strophe.Status.CONNECTED) {
		log('Strophe is connected.');

    }
}

Please find openfire server settings:

![openfire](https://cloud.githubusercontent.com/assets/498771/9079705/ba4e263a-3b6a-11e5-8197-8a1185936cc1.png)

Please help me.

THanks

**Comment by pokal4u** [comment]
response from bosh was:

<body xmlns="http://jabber.org/protocol/httpbind" xmlns:stream="http://etherx.jabber.org/streams" authid="d092ac6f" sid="d092ac6f" secure="true" requests="2" inactivity="30" polling="5" wait="60" hold="1" ack="3098283438" maxpause="300" ver="1.6"><stream:features><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>DIGEST-MD5</mechanism><mechanism>PLAIN</mechanism><mechanism>ANONYMOUS</mechanism><mechanism>CRAM-MD5</mechanism></mechanisms><compression xmlns="http://jabber.org/features/compress"><method>zlib</method></compression><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"/><session xmlns="urn:ietf:params:xml:ns:xmpp-session"/></stream:features></body>

**Comment by pokal4u** [comment]
response from bosh:

![bosh-response](https://cloud.githubusercontent.com/assets/498771/9081368/566563a4-3b79-11e5-9973-c37636f6ae0b.png)

**Comment by vitalyster** [comment]
And how XMPPFramework related to this? Strophe project is not here :)

**Comment by ObjColumnist** [comment]
As @vitalyster said its not something we are best place to help with but it looks like your server isn't advertising support for in band registration in `stream:features`

```
    <register xmlns='http://jabber.org/features/iq-register'/>
```
