### ISSUE TITLE
Correct way to set user email

### ISSUE THREAD

**Issue by mohonish** [robbiehanson/XMPPFramework#571]
Hi,

I've been having some difficulty trying to set the user email field in the user's vCard.

Below is my latest approach. Any help pointing me towards the right direction would be greatly appreciated.

```
var myvCardTemp = self.xmppvCardTempModule!.myvCardTemp

    if myvCardTemp == nil
    {
        //create a new vCardTemp and update.
    } else {
        //set values as normal
        var newvCardTemp = myvCardTemp
        var email1 = DDXMLElement(name: "USERID", stringValue: email)

        newvCardTemp.addEmailAddress(XMPPvCardTempEmail.vCardEmailFromElement(email1))

        xmppvCardTempModule!.updateMyvCardTemp(newvCardTemp)
    }
```

In my app the vCard will always be created before requiring this part hence I don't necessarily need to handle that case for now.
I'm using Swift 1.2 and XCode 6.4.

**Comment by vitalyster** [comment]
...
let email1 = DDXMLElement(name: "EMAIL")
email1.addChild(DDXMLElement(name: "USERID", stringValue: email: emailValue)
...

**Comment by mohonish** [comment]
That didn't work.
I printed the value of `newvCardTemp` before and after the `addEmailAddress` line. It prints the same as below.

    <vCard xmlns="vcard-temp"><FN>MyName</FN></vCard>

I would expect the vcard to contain elements for email but that doesn't help.

The below code does update the newvCardTemp (as is reflected in the callback `xmppvCardTempModuleDidUpdateMyvCard(...)`)

        var newvCardTemp = myvCardTemp
        let email1 = DDXMLElement(name: "EMAIL")
        email1.addChild(DDXMLElement(name: "USERID", stringValue: emailValue))
        newvCardTemp.addChild(email1)
        xmppvCardTempModule!.updateMyvCardTemp(newvCardTemp)

But I'm sure that is not the correct way, as later while retrieving the user email address, it fails. Which brings me to another question. What is the correct way to retrieve email address of the user? I'm using `myvCardTemp.emailAddresses[0] as! String` but it doesn't work. I feel my approach is all messed up here.

**Comment by ObjColumnist** [comment]
It looks like nobody got round to implementing the connivence methods on `XMPPvCardTemp` for accessing multivalve attributes such as emails.

Your second approach looks like it should work though.

**Comment by mohonish** [comment]
So what should be the correct approach to create XMPPvCardTemp objects with username, email, and photo and update them to the XMPP Server?

**Comment by ObjColumnist** [comment]
The correct approach would be to manually add the elements, like in your second comment as the convinience methods are not implemented.

Same for fetching them, you would need to loop through the child elements.

**Comment by beribas** [comment]
Hi everyone, 

I came across the same issue and added the implementation to my fork. 
You can see it in these commits:

464ca52b17df794287e0d484934b3445916e7715
e63dcdb7592bd9d8b01fd1e00e93dcaa13dee96a

Maybe it can help.

**Comment by chrisballinger** [comment]
@beribas Feel free to submit a pull request

**Comment by beribas** [comment]
Sure!
Here it is:
https://github.com/robbiehanson/XMPPFramework/pull/854
