### ISSUE TITLE
Which fork and version to use

### ISSUE THREAD

**Issue by yasirmturk** [robbiehanson/XMPPFramework#572]
Hi, there are mainly 3 forks and several versions available which are not in sync ..so i am confused which copy is most stable and should be included in production?

https://github.com/robbiehanson/XMPPFramework
https://github.com/magnetsystems/XMPPFramework
https://github.com/processOne/XMPPFramework

**Comment by ObjColumnist** [comment]
This is the original/main version, but obviously people fork the project to add their own application specific features etc

So for example, the processOne fork might have additional features related to their products and services that you might find useful.

**Comment by yasirmturk** [comment]
Yes, but for a standard user which repo should i use as the main repo doesnot have cocoapods support too..

**Comment by ObjColumnist** [comment]
Im not sure, the XMPPFramework doesn't officially support CocoaPods for a number of reasons (take a look in the issues), but the processOne fork is up to date.

**Comment by yasirmturk** [comment]
okay thanks

**Comment by yasirmturk** [comment]
and the other question was regarding migration of the coredata models used in the framework?

**Comment by ObjColumnist** [comment]
Was that in another issue? I don't think any of the models have been updated in a while.
