### ISSUE TITLE
XMPP Stream Not Connecting

### ISSUE THREAD

**Issue by vikram17000** [robbiehanson/XMPPFramework#575]
Hi - I've set up an ejabberd server on AWS and I can connect with it via other third-party clients (such as Adium and Converse.js). However, when I try to integrate the XMPPFramework in my iOS app and call the setupStream and connect methods on XMPPStream in my AppDelegate, the stream somehow does not connect.

Would folks be aware please re: what could be the issue here? If it matters, I'm using Xcode 6 / iOS 8.

Below are snapshots of my code as well ...

    - (void)setupStream
    {
        _xmppStream = [[XMPPStream alloc] init];
        [_xmppStream setHostName:@"10.xx.xx.xx"]; // Public IP of the AWS EC2 instance.
        [_xmppStream setHostPort:5222];
        [_xmppStream addDelegate:self delegateQueue:dispatch_get_main_queue()];
    }

Also, in the connect function, the below method always returns YES / success which doesnt seem right.... the 'state' member variable of _xmppStream stays put at STATE_XMPP_DISCONNECTED.

     if (![_xmppStream connectWithTimeout:5 error:&error]) {
        UIAlertView *alertView = [[UIAlertView alloc] initWithTitle:@"Error"
                                                            message:[NSString stringWithFormat:@"Can't Connect To The Server %@", [error localizedDescription]]
                                                            delegate:nil
                                                            cancelButtonTitle:@"OK"
                                                            otherButtonTitles:nil, nil];
        
        [alertView show];
        
        return NO;
    }

**Comment by neste2015** [comment]
I had similar troubles when I did not initialize the xmppRosterStorage property (managedObjectContext_roster). I just use all the code from iPhoneXMPPAppDelegate that is provided with the source code and everything works fine for me. I am using latest release and just build the code. If the /XMPPFramework-3.6.5/Xcode/iPhoneXMPP project works fine, you custom client also should work fine.

**Comment by ObjColumnist** [comment]
What is outputted to the console?

`connectWithTimeout:error:` returning `YES` just means that everything is configured to connect e.g. the domain and port is set.

**Comment by vikram17000** [comment]
Thanks Neste and Spencer... appreciate your responses. Unfortunately initializing xmppRosterStorage also doesnt seem to be helping.

Spencer: Do you mean the Xcode console - strangely, that is blank for me? Wondering if I need to set an env var or something to activate logging in the XMPP framework. Once the connection is through, I should be able to dig in further but afraid rather lost right now as the state of the xmpp stream wouldnt change from STATE_XMPP_DISCONNECTED. I'm checking in-band registration in my connect method as below, but that wouldnt succeed - believe because of this state.

        if ([_xmppStream supportsInBandRegistration]) {
                NSLog(@"Supports in band registration...");
        }

Also, here is my set-up stream code after incorporating Neste's suggestions... any thing strikes you all?

    self.xmppStream = [[XMPPStream alloc] init];
    self.xmppRosterStorage = [[XMPPRosterCoreDataStorage alloc] init];
    self.xmppRoster = [[XMPPRoster alloc] initWithRosterStorage:self.xmppRosterStorage];
    
    [self.xmppStream setHostName:@"10.**.**.**"];
    [self.xmppStream setHostPort:5222];
    
    [self.xmppRoster activate:self.xmppStream];
    [self.xmppStream addDelegate:self delegateQueue:dispatch_get_main_queue()];
    [self.xmppRoster addDelegate:self delegateQueue:dispatch_get_main_queue()];

Thanks much once again!

**Comment by ObjColumnist** [comment]
Have you implemented the following delegate methods to give you some more insight into your issue?

```objc
- (void)xmppStreamDidConnect:(XMPPStream *)sender;
- (void)xmppStreamDidDisconnect:(XMPPStream *)sender withError:(NSError *)error;
```

You need to configure CocoaLumberjack to output the to the console:

```objc
[DDLog addLogger:[DDTTYLogger sharedInstance] withLogLevel:XMPP_LOG_FLAG_SEND_RECV];
```

**Comment by vikram17000** [comment]
Thanks much, Spencer... apologies for the delay in replying but I could finally get around to fixing this. The problem was two-fold:
1. Incorrect use of username whilst sending the registration. I needed to put the domain name / IP address too.
2. Removing of the trusted_network option for ip_access in the ejabberd.yml file that prevented users not on the local server from registering a new server.

Thanks again for your inputs and for the tip on activating logging. I'll close this issue as well.
