### ISSUE TITLE
XEP-0313: Message Archive Management

### ISSUE THREAD

**Issue by chrisballinger** [robbiehanson/XMPPFramework#580]
[XEP-0313: Message Archive Management](http://xmpp.org/extensions/xep-0313.html) synchronize message history with the server. Replaces XEP-0136 with a much simpler spec. We will probably work on this and submit a PR when we're done.

> As this extension aims to make things easy for client developers, some research was made into the way clients handle history today. The resulting protocol was designed to allow for the following primary usage scenarios:

> * Automatic history synchronization between multiple clients.
Calendar-based on-demand display of historic messages in a client that doesn't keep local history.
> * So-called 'infinite' scrollback, whereby a client automatically fetches and displays historical messages naturally in the message log as the user scrolls back in time.
> * Another extension for archiving already exists in XMPP, Message Archiving (XEP-0136) [1]). However implementation experience has shown that the protocol defined therein supports rather more functionality than is typically needed for the above uses, and is significantly more effort to implement.

> This specification aims to define a much simpler and modular protocol for working with a server-side message store. Through this it is hoped to boost implementation and deployment of archiving in XMPP. It should be noted that (although not required) a server is free to implement XEP-0136 alongside this protocol if it so chooses, though a mapping between both protocols is beyond the scope of this specification.

**Comment by chrisballinger** [comment]
Oops looks like this is a dupe of https://github.com/robbiehanson/XMPPFramework/issues/348

**Comment by nguyenchiencong** [comment]
Anything new on this?
