### ISSUE TITLE
Customizing 'message' request

### ISSUE THREAD

**Issue by vikram17000** [robbiehanson/XMPPFramework#587]
Hi - I need to add additional attributes in the 'message' element / XMPP packet - example 'room_temp', plus a few others.

I've seen mixed views re: where these attributes should be added - whether directly as a sub-attribute of 'message' (i.e. parallel to 'body') or should they be added within the 'body'. For instance this post (http://stackoverflow.com/questions/26507753/how-to-add-custom-fields-in-message-elements-of-xmpp-stanza-packet) on another forum refers that keeping it parallel to 'body' is not recommended by XMPP standards. However, when I look at the section 'WorkingWithElements' in XMPPFramework itself (https://github.com/robbiehanson/XMPPFramework/wiki/WorkingWithElements), adding an attribute directly to the 'body' node is the right way forward...

Appreciate if you can opine here please...

Many thanks...

**Comment by ObjColumnist** [comment]
Custom elements should be a child of stanza, so in parallel to the body element e.g. the request/received elements defined in: http://www.xmpp.org/extensions/xep-0184.html

**Comment by vikram17000** [comment]
Thanks!
