### ISSUE TITLE
Cannot Create an XMPPConnection while the app is in Background IOS

### ISSUE THREAD

**Issue by rahulsingh2k10** [robbiehanson/XMPPFramework#592]
Hi,
 I am facing issues in creating a xmppConnection while the application suspends after 3 mins of application going to background. Let me explain in detail.
The following are the lines added in DidReceiveRemoteNotificiation Delegate method
```objc
- (void)application:(UIApplication *)application
didReceiveRemoteNotification:(NSDictionary *)userInfo
fetchCompletionHandler:(void (^)(UIBackgroundFetchResult result))completionHandler {
    if (_backgroundManager.backgroundTaskIdentifier ==  UIBackgroundTaskInvalid) {
        _backgroundTaskIdentifier = [[UIApplication sharedApplication] beginBackgroundTaskWithExpirationHandler:^ {
        [[XMPPConnectionManager sharedInstance].xmppStream disconnect];
        [[UIApplication sharedApplication] endBackgroundTask:_backgroundTaskIdentifier];
        _backgroundTaskIdentifier = UIBackgroundTaskInvalid;
    }];
        if ([XMPPConnectionManager sharedInstance].isXMPPStreamConnected) {
            [RSWritableLog writeLog:@"XMPPSTREAM CONNECTED"];
        } else {
            [RSWritableLog writeLog:@"XMPPSTREAM NOT CONNECTED"];
        }
    } 
    completionHandler(UIBackgroundFetchResultNewData);
}
```
When my application goes to background, and message is received via Push, the above method is called where we create a XMPPConnection. This works fine if we send the push just within 15-20 mins after the app goes to background. But if we send the push after 3-4 hrs later, the application does not create XMPPConnection. Could you let me know what could be the issue.

**Comment by ObjColumnist** [comment]
Where are you connecting an XMPPStream in this example?
