### ISSUE TITLE
libxmlSimu not when found manually added the frameworks

### ISSUE THREAD

**Issue by devidasm** [robbiehanson/XMPPFramework#596]
<img width="1280" alt="screen shot 2015-09-16 at 11 29 49 am" src="https://cloud.githubusercontent.com/assets/11434093/9897464/7c7891b6-5c66-11e5-8bb0-f8c8a78d322f.png">

**Comment by devidasm** [comment]
I am also tried these things 




------------------------------------------------------------------------------------------------------------
They have typo in libxmlSimu module definition. Correct path for header is:
"/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/libxml2/libxml/tree.h"
You need to forward modules in your framework pod like:
s.xcconfig = {
  'HEADER_SEARCH_PATHS' => '$(SDKROOT)/usr/include/libxml2 $(SDKROOT)/usr/include/libresolv $(PODS_ROOT)/XMPPFramework/module',
  'CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES' => 'YES',
  'OTHER_LDFLAGS' => '"$(inherited)" "-lxml2" "-objc"'
}

**Comment by Raymond26** [comment]
Having the same issue with this.

**Comment by andrey-justo-movile** [comment]
I had the same issue.
So I did roll back in the last commit https://github.com/andrey-justo-movile/XMPPFramework
You can use it in your pod file like: 
pod 'XMPPFramework', :podspec => 'https://raw.githubusercontent.com/andrey-justo-movile/XMPPFramework/3.7.2/XMPPFramework.podspec.json'

**Comment by mmrobert** [comment]
Why the writer of the .podspec file just fix the problem? How do i use the .podspec file? Just copy it into   the project folder or need to install it ?

**Comment by chrisballinger** [comment]
Sorry! Will be releasing a fix shortly, just haven't had time yet to finish
it up.

**Comment by devidasm** [comment]
My issue is fixed by adding header path of libxml and libxmlSimu

**Comment by Shrutimittal91** [comment]
hi @devidasm  Please let me know how you fixed the issues as i am also getting the error regarding libxml and libxmlsimu

**Comment by Hochman85** [comment]
Hi, is adding "XMPPFramework.podspec" supposed to fix the issue? On mine, it is not :(

Any idea?

Thanks,
Hisham

**Comment by Shrutimittal91** [comment]
@Hochman85  add below line to your podfile. It solved my problem.

pod 'XMPPFramework', :podspec => 'https://raw.githubusercontent.com/andrey-justo-movile/XMPPFramework/3.7.2/XMPPFramework.podspec.json'

**Comment by Hochman85** [comment]
@Shrutimittal91 that actually worked! Thanks a lot :)

N.B. I had to delete reference to any XMPP stuff I had added before - seems obvious but may get overlooked.
