### ISSUE TITLE
Prebind, xmppframework and openfire

### ISSUE THREAD

**Issue by jrsfiend** [robbiehanson/XMPPFramework#6]
Hi

We're trying to implement XMPP over BOSH for our product. The Strophe.js javascript library works fine for our needs on the WWW site. We request a prebind, it's delivered and then we use Strophe's 'attach' method to start our session - then we're able to update presence and send/receive messages. On the iOS side of things, we're using your XMPPFramework which includes a BOSH transport, but there's no attach method. 

I was wondering if anyone's tried prebinding (which I have working in iOS) and then using the provided SID/RID and known or provided JID to get passed authentication and be able to update presence and send/receive messages. I have the XMPP Framework sending/receiving messages fine when I authenticate to Openfire using a known username/password, but the dynamics of our systems require we use a prebind.

Any thoughts would be greatly appreciated. I've also posted more details here: http://stackoverflow.com/questions/8511974/openfire-prebind-robbiehanson-xmppframework-using-bosh-not-working

**Comment by dodikk** [comment]
Here is a more recent discussion https://github.com/robbiehanson/XMPPFramework/issues/120

**Comment by Igorsnaki** [comment]
Hi all!

Does anybody managed to implement/ find solution for XMPP Over Bosh? 
Could you please share links to libs, discussions? 

Thank you in advance.
