### ISSUE TITLE
XMPP last activity time shows in strange form. How to fix it?

### ISSUE THREAD

**Issue by orkhanalizade** [robbiehanson/XMPPFramework#600]
I have added to the Bridging file XMPPLastActivity.h file and in Swift file I did the next:

    let abc = XMPPLastActivity()
    let a = abc.sendLastActivityQueryToJID(user.jid)
    print("A is: \(a)")

but it returns me response like

     1686F740-C50C-477B-BAE2-02C897826B97
How can I return it in human readable format?

**Comment by adozenlines** [comment]
Try debugging the server response (xml) first to see what is coming back in the JID field of the xml schema.

Sean.

**Comment by vitalyster** [comment]
What exactly you want to see? This function have documentation string:
> * The returning string is the element ID of the IQ that was sent

If you want to see XML elements created by this extension, you can inspect and use methods from `XMPPIQ (LastActivity)` category

**Comment by adozenlines** [comment]
Also become very familiar with the xmpp specs & the source code you’re working with to better understand how things work.

**Comment by orkhanalizade** [comment]
I want to get response in seconds Sent from Yahoo Mail for iPhoneOn Sep 18, 2015, 18:03:41, vitalyster wrote:What exactly you want to see? This function have documentation string:



The returning string is the element ID of the IQ that was sent



If you want to see XML elements created by this extension, you can inspect and use methods from XMPPIQ (LastActivity) category

**Comment by adozenlines** [comment]
Try expanding \(a.lastActivitySeconds)

**Comment by adozenlines** [comment]
Look at the source documented headers of the include file or files.

**Comment by orkhanalizade** [comment]
I want to get response in seconds. Can I convert it to seconds or os there another function which returns me seconds value in Int?Sent from Yahoo Mail for iPhoneOn Sep 18, 2015, 18:03:07, Sean Batson wrote:Try debugging the server response (xml) first to see what is coming back in the JID field of the xml schema.

Sean.

**Comment by adozenlines** [comment]
Include this file a XMPPIQ category "XMPPIQ+LastActivity.h” and call lastActivitySeconds against “a”.

**Comment by orkhanalizade** [comment]
I've try this: 

    let xyz = XMPPIQ().lastActivitySeconds()

and it returns me: 9223372036854775807 =/

**Comment by adozenlines** [comment]
let abc = XMPPLastActivity()
let a = abc.sendLastActivityQueryToJID(user.jid)

Implement one of the protocol methods and extract the time if not already provided ...
let time : Double = a.lastActivitySeconds()

Then convert time from seconds to a user readable format.

**Comment by orkhanalizade** [comment]
`XMPPLastActivity()` doesn't have `lastActivitySeconds()`, it has `XMPPIQ()`

**Comment by adozenlines** [comment]
Here is a basic use case of the module:

import UIKit

class ViewController: UIViewController, XMPPLastActivityDelegate /* Protocol */ {

    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        
        let sendLast = XMPPLastActivity()
        
        sendLast.addDelegate(self, delegateQueue: dispatch_get_main_queue()) // Add delegate - remove on clean up
        let xmppJID  = XMPPJID.jidWithString("some_user")
        
        sendLast.sendLastActivityQueryToJID(xmppJID) // query remote resource
        
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }

// Delegate methods used to listen for feedback of sendLastActivityQueryToJID method
	
    func xmppLastActivity(sender: XMPPLastActivity!, didNotReceiveResponse queryID: String!, dueToTimeout timeout: NSTimeInterval) {
        
    }

    func xmppLastActivity(sender: XMPPLastActivity!, didReceiveResponse response: XMPPIQ!) {
        
	// Extract the seconds from response IQ
        let time = response.lastActivitySeconds()
        print("time in seconds \(time)")
        // do something with the time in seconds
        
    }
    
    func numberOfIdleTimeSecondsForXMPPLastActivity(sender: XMPPLastActivity!, queryIQ iq: XMPPIQ!, currentIdleTimeSeconds idleSeconds: UInt) -> UInt {
        return 30;
    }
}


Add to the XMPPFramework.h file

#import “XMPPLastActivity.h"

Add to the XMPP.h file

#import "XMPPIQ+Lastactivity.h"

**Comment by orkhanalizade** [comment]
it returns me ` 'ContactListTableViewController' does not conform to protocol 'XMPPLastActivityDelegate'`. Why?

**Comment by adozenlines** [comment]
Because the three delegate methods of that protocol are required methods.

You must implement:

    func xmppLastActivity(sender: XMPPLastActivity!, didNotReceiveResponse queryID: String!, dueToTimeout timeout: NSTimeInterval) {
        
    }

    func xmppLastActivity(sender: XMPPLastActivity!, didReceiveResponse response: XMPPIQ!) {
        
	// Extract the seconds from response IQ
        let time = response.lastActivitySeconds()
        print("time in seconds \(time)")
        // do something with the time in seconds
        
    }
    
    func numberOfIdleTimeSecondsForXMPPLastActivity(sender: XMPPLastActivity!, queryIQ iq: XMPPIQ!, currentIdleTimeSeconds idleSeconds: UInt) -> UInt {
        return 30;
    }
}

**Comment by orkhanalizade** [comment]
yes, it's gone! One more question, must I use this delegate exactly in JSQMessage Controller or can in tableView ContactList too? Because in the second case it did not print anything

**Comment by adozenlines** [comment]
Give these two free books from Apple iBooks a read over, they will assist you with various aspects of swift & obj-c

Check out this book on iBooks

Using Swift with Cocoa and Objective-C (Swift 2)
Apple Inc.
                                                                              (20)
Programming, Books, Computers & Internet
Jun 2, 2014
View Item
 <https://xp.apple.com/report/2/its_mail_sf?emailType=share_epubBook&lang=en_us&eventType=linkClick&responseType=redirect&redirectUrl=https://itunes.apple.com/ca/book/using-swift-cocoa-objective/id888894773?mt=11>
Swift is a new object-oriented programming language for iOS, OS X, and watchOS app development. It is designed to seamlessly integrate with Cocoa, Cocoa Touch, and Objective-C, allowing you to use the same familiar classes, patterns, and practices to build apps. Swift makes working with Cocoa and Objective-C safer, faster, easier, and more fun. 

This book provides:
– An overview of a Swift Xcode project
– Design patterns and best practices for working with Cocoa, Objective-C, and C
– Step–by–step instructions to use Swift and Objective-C in the same app
– Strategies to migrate your Objective-C code to Swift
You have not been added to any email lists.
Copyright © 2015 Apple Inc.


Check out this book on iBooks

The Swift Programming Language (Swift 2)
Apple Inc.
                                                                              (107)
Programming, Books, Computers & Internet
Jun 2, 2014
View Item
 <https://xp.apple.com/report/2/its_mail_sf?emailType=share_epubBook&lang=en_us&eventType=linkClick&responseType=redirect&redirectUrl=https://itunes.apple.com/ca/book/swift-programming-language/id881256329?mt=11>
Swift is a new programming language for creating iOS, OS X, and watchOS apps. Swift builds on the best of C and Objective-C, without the constraints of C compatibility. Swift adopts safe programming patterns and adds modern features to make programming easier, more flexible, and more fun. Swift’s clean slate, backed by the mature and much-loved Cocoa and Cocoa Touch frameworks, is an opportunity to reimagine how software development works.

This book provides:
- A tour of the language.
- A detailed guide delving into each language feature.
- A formal reference for the language.
You have not been added to any email lists.
Copyright © 2015 Apple Inc.

**Comment by adozenlines** [comment]
You can use it (delegate & protocols) anywhere once your modules have access to a stream and you have access to a singleton reference of a particular module to avoid duplication

**Comment by orkhanalizade** [comment]
thanks for the books! I'll read all of them!

But why then I do not get my print in the logs?

**Comment by adozenlines** [comment]
Add break points to the three delegate methods to see which method is being called or use a simple print statement to also see if they're being called.

But take a look at the objective-c version of the iPhone sample to see how the modules are implemented, how references are attained via other classes but to modules and try reproducing that in swift.

One way might be to attempt rewriting the iPhone objective-c sample in swift as an exercise...

**Comment by orkhanalizade** [comment]
No one calls. In my `XMPPFramework-umbrella.h` file I have `#import "XMPPLastActivity.h"`. On the `XMPP.h file` I've added `#import "XMPPIQ+Lastactivity.h"` line. In my tableView Controller, when I print all my users I've added 3 delegate lines - but nothing. I do not have any prints from all of 3 these functions =/

**Comment by adozenlines** [comment]
Do you have access to an existing public XMPPStream reference? if you do activate the XMPPLastActivity module reference against your stream reference.

**Comment by orkhanalizade** [comment]
You mean in Openfire, from Web-side? 

So sorry, I did not understand you correctly =/

**Comment by orkhanalizade** [comment]
I use XMPPStream for connecting to XMPP. If you want I can share with you with my file

**Comment by adozenlines** [comment]
sample appdelegate snippet

import UIKit

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?

    var queryLastActivity: XMPPLastActivity?
    var xmppStream: XMPPStream?
    
    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        // Override point for customization after application launch.
        
        xmppStream = XMPPStream()
        
        
        queryLastActivity = XMPPLastActivity ()
        queryLastActivity!.activate(xmppStream!)
        
        return true
    }
}

sample viewcontroller snippet

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        
        let xmppJID  = XMPPJID.jidWithString("some_user")
        AppDelegate().queryLastActivity!.addDelegate(self, delegateQueue: dispatch_get_main_queue())
        
        AppDelegate().queryLastActivity!.sendLastActivityQueryToJID(xmppJID)
        
    }

**Comment by orkhanalizade** [comment]
Nothing again =/ Look at my code. Other things are right, but just it =/

**Comment by adozenlines** [comment]
Are using the processone/xmpp-messenger-ios example project?

**Comment by orkhanalizade** [comment]
yes, I am. Something wrong?

**Comment by adozenlines** [comment]
Nope - all is good, just gives me a different perspective to your problem vs the stock iPhone sample from the framework.

**Comment by orkhanalizade** [comment]
I think we did right, I mean activating module. Can you help me with it, please?

**Comment by adozenlines** [comment]
ok let me grab a copy of the projects and try to implement it based on the Process one approach

**Comment by orkhanalizade** [comment]
Sure! I'm waiting for you! Keep me informed

**Comment by adozenlines** [comment]
Ok take a peek here https://github.com/adozenlines/xmpp-messenger-ios/commit/44364a174f1a1fe98abbdd1ac0a1a337889e96ea

Added OneLastActivity.swift

ChatViewController was modified

**Comment by orkhanalizade** [comment]
Thank you very much! But did not get you error `fatal error: unexpectedly found nil while unwrapping an Optional value` in

func xmppLastActivity(sender: XMPPLastActivity!, didReceiveResponse response: XMPPIQ!) {
        didMakeLastCallCompletionBlock!(sender: response)   
}

? I got =/

**Comment by orkhanalizade** [comment]
@adozenlines Can you help me with this problem, please?

**Comment by adozenlines** [comment]
hey let me take a peek, will get back to you before end of day...

**Comment by orkhanalizade** [comment]
@adozenlines I tried another way, without OneLastActivity.swoft file. I just inputed these 3 functions into my ContactsController, also added your lines to my OneChat.swift, but it doesn't return me anything. It even doesn't runs when I use my app. I also added to my `viewDidLoad` lines

`abc = XMPPIQ()
  print(abc.lastActivitySeconds)`

but it returns me empty `<eq></eq>`

**Comment by adozenlines** [comment]
Take a look at these changes https://github.com/adozenlines/xmpp-messenger-ios/commit/2e5fc5a9b5df3a64240e697588edec6679a488c5

**Comment by orkhanalizade** [comment]
@adozenlines it doesn't print anything =/ I've added 

    OneLastActivity.sendLastActivityQueryToJID(recipient.jidStr, sender: OneChat.sharedInstance.xmppLastActivity) { (sender, error) -> Void in
            if let error = error {
               print(error)
            }
            else if let timeInSeconds = sender?.lastActivitySeconds() {
                print("Time is \(timeInSeconds)")
            }
        }
`

but it doesn't print anything, even error

**Comment by adozenlines** [comment]
Sorry here is the fix
https://github.com/adozenlines/xmpp-messenger-ios/commit/4278ffe844db0eb8575a298900ae92b1be2f42f7

**Comment by orkhanalizade** [comment]
@adozenlines it prints `Time is 9223372036854775807` =/

**Comment by adozenlines** [comment]
Well you now have to decide what you're going to do with it ... Google NSDate

**Comment by orkhanalizade** [comment]
@adozenlines so is it correct response? And why it prints just for one user?

**Comment by orkhanalizade** [comment]
@adozenlines but something `9223372036854775807` wrong here, no? It's too long!

**Comment by orkhanalizade** [comment]
@adozenlines thank you very much!!!

**Comment by adozenlines** [comment]
The return value is relative to the user being queried for example, has the user ever logged in the server, how long ago was the last login does the server return such information...

**Comment by orkhanalizade** [comment]
Sorry, can I ask you something?

Why when I call

    OneLastActivity.sendLastActivityQueryToJID(user, sender: OneChat.sharedInstance.xmppLastActivity) { (sender, error) -> Void in

in

    override func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> onlineUserCell {

it doesn't call this(your) func of last activity. It calls just for the first time, when it loading. Later when I try reloadData() it doesn't call lastActivity func, but it calls `cellForRowAtIndexPath` func.

What's the problem? @adozenlines

**Comment by adozenlines** [comment]
Have look here 852f1c7 <https://github.com/adozenlines/xmpp-messenger-ios/commit/852f1c78727d7763888f722c9ceb6a93784c9125> and your table view will need to switch their table view cell from custom to subtitle in story boards if not already done.

**Comment by orkhanalizade** [comment]
@adozenlines yes, it works, but:

for example I have 4 offline contacts. It changes label.text just for 2 users from my list. So it looks like:

    1-user: last seen ...
    2-user: empty
    3-user: empty
    4-user: last seen ...

it appears just when I scroll my tableView to top(drag it to top) and leave it appears. Just in this case. For the first time it doesn't show anything =/

**Comment by adozenlines** [comment]
It just means the data isn't available at that point in time, the quickest fix will be to have a timer to reload the table view cell every 15 seconds but lastactivity is really meant to be used in one off single calls, as seen in whatsapp, Facebook messenger during the initial conversation.

**Comment by orkhanalizade** [comment]
@adozenlines I tried it:

    var timer = NSTimer.scheduledTimerWithTimeInterval(10, target: self, selector: "reloadTable", userInfo: nil, repeats: true)
    
    func reloadTable() {
        print("reload")
        self.tableView.reloadData()
    }

it reloads table, but it doesn't help me. I need to drag to top and leave my tableView many times for printing last activity labels for contacts. At first load it shows me just for 1 user. 

May be in code we need to change something?

**Comment by orkhanalizade** [comment]
@adozenlines are you here?

**Comment by orkhanalizade** [comment]
@adozenlines I looked, and in your code a client doesn't update label value. You need to drag tableView to top and leave to update they values. How can I fix it?

**Comment by adozenlines** [comment]
I would recommend posting future questions to the ProcessOne team directly as this is not a xmppframework issue nor project.

Cheers!
