### ISSUE TITLE
Duplicated <received> XMPP Delivery receipts received to Client once stream management is enabled

### ISSUE THREAD

**Issue by vickyrappier** [robbiehanson/XMPPFramework#601]
Hello Robbiehanson,

I have to enable stream management with following code in setupstream function as given in your example

    //Stream Management
    xMPPStreamManagement = [[XMPPStreamManagement alloc] init];
    [self.xMPPStreamManagement requestAck];
    [self.xMPPStreamManagement automaticallyRequestAcksAfterStanzaCount:1 orTimeout:0];
    [self.xMPPStreamManagement automaticallySendAcksAfterStanzaCount:1 orTimeout:0];
    [self.xMPPStreamManagement setAutoResume:YES];
    [xMPPStreamManagement   addDelegate:self delegateQueue:dispatch_get_main_queue()];
    [self.xMPPStreamManagement  activate:xmppStream];

And done below line in XMPPDidAuthenticate: once the XMPP go online is send to server, since writing the below function in setupstream function don't work to get me stream management callbacks (double confirmed).

 [self.xMPPStreamManagement enableStreamManagementWithResumption:YES maxTimeout:0];

Once I have enabled this I get multiple stanza response for the <received> calls for the same chat_element_id , due to this my chat traffic is very high and laggy chat with delayed ticks and blue ticks responses. Also the performance is slowed as the response count for number of chats keeps growing.

Pasting my client logs for your reference 

  `SEND: <?xml version='1.0'?>
  SEND: <stream:stream xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' version='1.0' to='company.domain.com'>
  RECV: <stream:stream xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" id="4091724384" from="company.domain.com" version="1.0" stream1:lang="en"/>
  RECV: <stream:features xmlns:stream="http://etherx.jabber.org/streams"><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism><mechanism>SCRAM-SHA-1</mechanism></mechanisms><register xmlns="http://jabber.org/features/iq-register"/><sm xmlns="urn:xmpp:sm:3"/></stream:features>
  SEND: <auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="SCRAM-SHA-1">GFGDGDFGFDGFDGDF34234234234324324234242342</auth>
  RECV: <challenge xmlns="urn:ietf:params:xml:ns:xmpp-sasl">EWEQWEqweqweqeWDUMMYQWQEQWEQWEQWewq</challenge>
  SEND: <response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">DUMMYEREWRWEREWREWRWERWEREWRWErewrwe==</response>
  RECV: <success xmlns="urn:ietf:params:xml:ns:xmpp-sasl">weqeqweqweqwewqewe</success>
  SEND: <stream:stream xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' version='1.0' to='company.domain.com'>
  RECV: <stream:stream xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" id="2884175902" from="company.domain.com" version="1.0" stream1:lang="en"/>
  RECV: <stream:features xmlns:stream="http://etherx.jabber.org/streams"><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"/><session xmlns="urn:ietf:params:xml:ns:xmpp-session"/><register xmlns="http://jabber.org/features/iq-register"/><sm xmlns="urn:xmpp:sm:3"/></stream:features>
  SEND: <iq type="set" id="8DC6D8F9-68FA-474F-96AB-D3133E3B55FA"><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"><resource>iOS</resource></bind></iq>`
 

*Also get this Ack 'a' and Request 'r' stanzas with same h values multiple times*

  `RECV: <r xmlns="urn:xmpp:sm:3"/>
  SEND: <a xmlns="urn:xmpp:sm:3" h="1"/>
  SEND: <a xmlns="urn:xmpp:sm:3" h="1"/>
  SEND: <a xmlns="urn:xmpp:sm:3" h="2"/>
  SEND: <a xmlns="urn:xmpp:sm:3" h="2"/>`

*This is repeating for every message send *

 ` RECV: <stream:features xmlns:stream="http://etherx.jabber.org/streams"><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism><mechanism>SCRAM-SHA-1</mechanism></mechanisms><register xmlns="http://jabber.org/features/iq-register"/><sm xmlns="urn:xmpp:sm:3"/></stream:features>`

*Repeated <received> stanza callbacks for same message Id*

 `RECV: <message xmlns="jabber:client" from="abc@company.domain.com/qqq" to="def@company.domain.com/qqq" lang=""><received xmlns="urn:xmpp:receipts" id="CNV-1442828911809"/></message>
  RECV: <r xmlns="urn:xmpp:sm:3"/>
  RECV: <message xmlns="jabber:client" from="abc@company.domain.com/qqq" to="pqr@company.domain.com/qqq" lang=""><received xmlns="urn:xmpp:receipts" id="CNV-1442828911809"/></message>
  RECV: <r xmlns="urn:xmpp:sm:3"/>
  RECV: <message xmlns="jabber:client" from="abc@company.domain.com/qqq" to="pqr@company.domain.com/qqq" lang=""><received xmlns="urn:xmpp:receipts" id="CNV-1442828911809"/></message>
  RECV: <r xmlns="urn:xmpp:sm:3"/>
  RECV: <message xmlns="jabber:client" from="abc@company.domain.com/qqq" to="abc@company.domain.com/qqq" lang=""><received xmlns="urn:xmpp:receipts" id="CNV-1442828911809"/></message>
  RECV: <r xmlns="urn:xmpp:sm:3"/>
  RECV: <message xmlns="jabber:client" from="abc@company.domain.com/qqq" to="abc@company.domain.com/qqq" lang=""><received xmlns="urn:xmpp:receipts" id="CNV-1442828911809"/></message>
  RECV: <r xmlns="urn:xmpp:sm:3"/>
  RECV: <message xmlns="jabber:client" from="abc@company.domain.com/qqq" to="abc@company.domain.com/qqq" lang=""><received xmlns="urn:xmpp:receipts" id="CNV-1442828911809"/></message>
  RECV: <r xmlns="urn:xmpp:sm:3"/>
  RECV: <message xmlns="jabber:client" from="abc@company.domain.com/qqq" to="abc@company.domain.com/qqq" lang=""><received xmlns="urn:xmpp:receipts" id="CNV-1442828911809"/></message>`

Appreciate if you can let me know why this is happening. This is occurring only if i enable stream management.

**Comment by vickyrappier** [comment]
I also observed that 

- (void)xmppStream:(XMPPStream *)sender didReceiveMessage:(XMPPMessage *)message
{
    if([message hasReceiptRequest])
    {        
        if(self.autoSendMessageDeliveryReceipts)
        {
            XMPPMessage *generatedReceiptResponse = [message generateReceiptResponse];
            [sender sendElement:generatedReceiptResponse];
            
        }
    }
}

Is called several times in the XEP 0184 - XMPPDeliveryReceipts.m class Line #122

**Comment by vickyrappier** [comment]
Closing this as this was caused since I am calling ADDDElegete:(self) on main_thread .... twice due to some example reference.

**Comment by sharda1111** [comment]
@vickyrappier I am also facing this problem please suggest me what can i do for repeat stanza.

**Comment by StefanSourcico** [comment]
Anybody solved this issue? I am also getting duplicate messages since I've enabled stream management.

**Comment by StefanSourcico** [comment]
Ok i got it, to fix duplicate messages you need to implement this module in the place where you setup your xmpp stream:     
[self.xmppStreamManagement automaticallySendAcksAfterStanzaCount:1 orTimeout:0.4];
