### ISSUE TITLE
Does XMPPFramework support Users Groups option?

### ISSUE THREAD

**Issue by orkhanalizade** [robbiehanson/XMPPFramework#617]
Hi, I want to ask about users groups(not a Group Chat, MUC). Does this framework support this option?

For example, I putted my friends into groups: Friends, Colleges, Family, etc. Can I get these groups list and members lists with this framework?

**Comment by max-potapov** [comment]
Hi. Are you looking for this XEP: http://xmpp.org/extensions/xep-0083.html ?

**Comment by orkhanalizade** [comment]
But in the XMPPFramework/Extensions there is not such folder. So, how can use this XEP in my project? Any ideas or advices? @max-potapov

**Comment by max-potapov** [comment]
This XEP is unimplemented in XMPPFramework and requires XEP-0049 on a server side.
