### ISSUE TITLE
Saving Chat history using XEP - 0136

### ISSUE THREAD

**Issue by obaidjawad** [robbiehanson/XMPPFramework#63]
I'm working on the Chat history archiving on server side, so I came across this XEP 0136 so I just want a clarification that is this really possible like saving the users chat history on server side and retreiving it upon the client request in iPhone using the XEP 0136 documentation as mentioned?

You answer will be greatly appreciated. Thank  you.

**Comment by caipivara** [comment]
@obaidjawad can you share how you setup the history fetch?
