### ISSUE TITLE
Deleting chat from XMPPMessageStorage

### ISSUE THREAD

**Issue by orkhanalizade** [robbiehanson/XMPPFramework#632]
I cannot delete chat from the XMPPMessageStorage. Is it a bug?

When I try this:

    let moc = OneMessage.sharedInstance.xmppMessageStorage?.mainThreadManagedObjectContext
		let entityDescription = NSEntityDescription.entityForName("XMPPMessageArchiving_Message_CoreDataObject", inManagedObjectContext: moc!)
		let request = NSFetchRequest()
		let predicateFormat = "bareJidStr like %@ "
		
		let predicate = NSPredicate(format: predicateFormat, user.jidStr)
		request.predicate = predicate
		request.entity = entityDescription
			
		do {
			let results = try moc?.executeFetchRequest(request)
			for message in results! {
                print("Message is: \(message)")
				moc?.deleteObject(message as! NSManagedObject)
			}
		} catch _ {
		}

it deletes my messages(I see it in logs), but when I relaunch my app again, these messages appears again. What's wrong here? Can anyone help me, please?

**Comment by adozenlines** [comment]
Start by checking your server message retention settings or the options around message management on the server.
—OR—
You need to save “save” on the moc to commit the changes but do this without the Xcode debugger.

**Comment by orkhanalizade** [comment]
Damn it! I absolutely forgot about it!
Thanks! You really saved my nerves
