### ISSUE TITLE
XMPPResourceCoreData object returns nil on asking for resoursewithJID and stream parameter function

### ISSUE THREAD

**Issue by vicky1787** [robbiehanson/XMPPFramework#633]
Hello Team,

I am trying to get the resource object from the XMPP CoreData to check if the presence is unavailable then request last activity query. 

Also I see the object in the core data in XMPPRoster table for resource I get the XMPPResourceStorage object nil on fetching the resource with given function. On research I found that the predicate is checking as jidStr == and not like hence my jid passed is abc@dev.server.com and the resource that was added was abc@dev.server.com/IOS. This two won't match ever.

Now my question and confusion is that when i add this item to roster I don't know the /resource part of the user hence I just add the JID by XMPP addUserToRoster function. 

Kindly help me wth your expert advice how to go around this issue.

If there is a LIKE Clause It can be okay in the below code of XMPPCoreDataStorageClause

```
NSPredicate *predicate;
if (stream == nil)
    predicate = [NSPredicate predicateWithFormat:@"jidStr == %@", fullJIDStr];
else
    predicate = [NSPredicate predicateWithFormat:@"jidStr == %@ AND streamBareJidStr == %@",
                 fullJIDStr, [[self myJIDForXMPPStream:stream] bare]];
```

**Comment by vickyrappier** [comment]
If there is a LIKE Clause It can be okay in the below code of XMPPCoreDataStorageClause

	NSPredicate *predicate;
	if (stream == nil)
		predicate = [NSPredicate predicateWithFormat:@"jidStr == %@", fullJIDStr];
	else
		predicate = [NSPredicate predicateWithFormat:@"jidStr == %@ AND streamBareJidStr == %@",
					 fullJIDStr, [[self myJIDForXMPPStream:stream] bare]];

**Comment by vickyrappier** [comment]
When I add user to Roster I am adding without resource and when even fetching the user I cant get full JID that i can then pass to this resourcewithJID function. Please help

**Comment by adozenlines** [comment]
Don't do what you're doing, Refer to the iPhoneXMPP sample which show the three basic states of Available, Away & Offline (RootViewController). Then look at implementing XEP-0012 available in the extensions folder of project.

**Comment by vickyrappier** [comment]
Hello Sean, 

Thanks for your information , do you mean that I need to rely not he XMPPUserCoreDataStorageObject object, but there is no column that is giving me current information like the ResourceEntity table.

Well after careful observation I check that the sectionNum column is something the fetch result is sorting the items as offline, online, away. 

Do I need to check this column value to request for the last seen. I am using my custom core data for other things hence for the presence and other information I am planning to use the existing core data objects and sources.

Please let me know where i can study the sectionNum types. Appreciate your help once again.

**Comment by vickyrappier** [comment]
I checked this : https://github.com/robbiehanson/XMPPFramework/pull/158 but need your advice for exact values now.

**Comment by vickyrappier** [comment]
switch (section)
		{
			case 0  : return @"Available";
			case 1  : return @"Away";
			default : return @"Offline";
		}
 Is this the latest

**Comment by adozenlines** [comment]
Implement the xep 0012 and make the call to send last activity for jid. The response will be the time last seen for the user. The core data tables are for aspects of the framework unrelated to what you need.

**Comment by vicky1787** [comment]
Thanks Sean,

I always get the last seen 0 even though user declares offline. We are
trying to find the cause as this is not happening with thirdpartclient
declaring offline not quitting the app.

I did as you said in the sectionNum value check and its fine to ask for the
last seen or show online status. Only problem still remains is when the user
goes offline he still is shown online for some time in the Roaster
sectionNum Value.

Thanks,
Regards,
Vicky S Dhas


From:  Sean Batson notifications@github.com
Reply-To:  robbiehanson/XMPPFramework
<reply+00a9e1ab2066334cba8bdfd65fddb1c5318476be3fe0fab292cf00000001126d5c269
2a169ce07117804@reply.github.com>
Date:  Wednesday, 25 November 2015 at 7:23 PM
To:  robbiehanson/XMPPFramework XMPPFramework@noreply.github.com
Cc:  Vicky Dhas vickydhas@rappier.com
Subject:  Re: [XMPPFramework] XMPPResourceCoreData object returns nil on
asking for resoursewithJID and stream parameter function (#633)

Implement the xep 0012 and make the call to send last activity for jid. The
response will be the time last seen for the user. The core data tables are
for aspects of the framework unrelated to what you need.

Sent from my iPhone

> On Nov 24, 2015, at 9:31 PM, Vicky Dhas (Rappier Pte Ltd)
> notifications@github.com wrote:
> 
> switch (section)
> {
> case 0 : return @"Available";
> case 1 : return @"Away";
> default : return @"Offline";
> }
> Is this the latest
> 
> 
> Reply to this email directly or view it on GitHub.


Reply to this email directly or view it on GitHub
<https://github.com/robbiehanson/XMPPFramework/issues/633#issuecomment-15957
6899> .

**Comment by adozenlines** [comment]
So you have implemented the XEP 0012 module similar to how the other modules have been implemented during the XMPP boot strap process, you have a reference or access to the module from the calling class via the send last activity method and its delegate methods are returning zero seconds or some kind of error. Zero seconds usually means the user is still online server side or the server isn't always sending the correct info.

Print or break point on what the XMPPLastActivityDelegate protocol methods are returning.

**Comment by vickyrappier** [comment]
Hi Sean,

Yes as per the information I have implemented the xmpplastactivity module
and also get the didreceivelastactivity response and sometimes
didnotreceivelastactivity callbacks but what I observe is on making the
third party client go offline I get exact value in seconds parameter as
1, 2,30 seconds ... Clients like Adium and swift for example.

But if I declare stream offline in appdidresignactive I get other end as
offline notified but when he fetches the last activity it gets seconds
value 0 always for at least 5,6minutes and suddenly after some time it
starts getting correct time but after a while.

But this same thing as mentioned is not happened with third party clients.

Also tried to completely disconnect xmpp connection rather just making
client offline presence sent but no success.

Can you highlight why this is happening.

Thanks

Vicky

On Wednesday, 25 November 2015, Sean Batson <notifications@github.com>
wrote:

> So you have implemented the XEP 0012 module similar to how the other
> modules have been implemented during the XMPP boot strap process, you have
> a reference or access to the module from the calling class via the send
> last activity method and its delegate methods are returning zero seconds or
> some kind of error. Zero seconds usually means the user is still online
> server side or the server isn't always sending the correct info.
>
> Print or break point on what the XMPPLastActivityDelegate protocol methods
> are returning.
>
>
> > On Nov 25, 2015, at 7:19 AM, Vicky Dhas (Rappier Pte Ltd) <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > Thanks Sean,
> >
> > I always get the last seen 0 even though user declares offline. We are
> > trying to find the cause as this is not happening with thirdpartclient
> > declaring offline not quitting the app.
> >
> > I did as you said in the sectionNum value check and its fine to ask for
> the
> > last seen or show online status. Only problem still remains is when the
> user
> > goes offline he still is shown online for some time in the Roaster
> > sectionNum Value.
> >
> > Thanks,
> > Regards,
> > Vicky S Dhas | Project Manager
> > Contact: +65 9183 9203
> > Skype: vickydhas | LinkedIn:
> > <https://www.linkedin.com/pub/vicky-dhas/13/aa2/543> vickydhas
> > <https://www.linkedin.com/pub/vicky-dhas/13/aa2/543>
> > Email:vickydhas@rappier.com
> <javascript:_e(%7B%7D,'cvml','Email:vickydhas@rappier.com');>
> >
> > Please consider the impact to the environment before printing this email
> >
> > This e-mail is confidential and may also be privileged. If you are not
> the
> > intended recipient, please notify us immediately by replying to this
> message
> > and then delete it from your system. You should not copy or use it for
> any
> > purpose, nor disclose its contents to any other person. Thank you.
> >
> >
> > From: Sean Batson <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > Reply-To: robbiehanson/XMPPFramework
> >
> <reply+00a9e1ab2066334cba8bdfd65fddb1c5318476be3fe0fab292cf00000001126d5c269
> > 2a169ce07117804@reply.github.com
> <javascript:_e(%7B%7D,'cvml','2a169ce07117804@reply.github.com');>>
> > Date: Wednesday, 25 November 2015 at 7:23 PM
> > To: robbiehanson/XMPPFramework <XMPPFramework@noreply.github.com
> <javascript:_e(%7B%7D,'cvml','XMPPFramework@noreply.github.com');>>
> > Cc: Vicky Dhas <vickydhas@rappier.com
> <javascript:_e(%7B%7D,'cvml','vickydhas@rappier.com');>>
> > Subject: Re: [XMPPFramework] XMPPResourceCoreData object returns nil on
> > asking for resoursewithJID and stream parameter function (#633)
> >
> > Implement the xep 0012 and make the call to send last activity for jid.
> The
> > response will be the time last seen for the user. The core data tables
> are
> > for aspects of the framework unrelated to what you need.
> >
> > Sent from my iPhone
> >
> > > On Nov 24, 2015, at 9:31 PM, Vicky Dhas (Rappier Pte Ltd)
> > <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > >
> > > switch (section)
> > > {
> > > case 0 : return @"Available";
> > > case 1 : return @"Away";
> > > default : return @"Offline";
> > > }
> > > Is this the latest
> > >
> > > ‹
> > > Reply to this email directly or view it on GitHub.
> > >
> >
> > ‹
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/robbiehanson/XMPPFramework/issues/633#issuecomment-15957
> > 6899> .
> >
> >
> >
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/robbiehanson/XMPPFramework/issues/633#issuecomment-159591512
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robbiehanson/XMPPFramework/issues/633#issuecomment-159615250>
> .
>


-- 
Sent from my iPhone

**Comment by vickyrappier** [comment]
Hello Sean,

I suspect that this is related to me not declaring the Offline declaration to server properly.

Observing something in the app the Phone when pressed @HOME  button goes offline then offline is well declared and last seen works like charm.

But when the App is removed from memory by swipe and exit the offline is not declared properly and hence the offline and last seen screws up.

Please can you advice with your expertise how to handle the Quit app.

**Comment by rappier** [comment]
Hi Sean,

Issue exist when even I have declared offline to server and by this time when I declare the other users are offline , what should be the behaviour the Client 2 when comes online should happen.

1) Do XMPP Server flush all the roaster entries presence to the user that came online.
2) Do Client 2 have to ask the presence of all users in his roaster or probe the presence explicitly to server when entering his chat screen.

Reason because the Client 1 went offline before Client 2 when offline So the last presence Client 1 have is online for that user but when he is back he still showing that Client online. Since the presence was not notified to him while online.

Can you help me how to poll this issue. The last seen issue linked to this is when i check the SectionNum value in my XMPPUserCoreDataObject the value for the Client 2 ==0 even though he is offline for long time.

Am i missing any flow. Please help.

Regards,
Vicky
