### ISSUE TITLE
What's license of XMPPFramework ?

### ISSUE THREAD

**Issue by fu7mu4** [robbiehanson/XMPPFramework#674]
copying.txt tells licenses of other open source software instead of license of XMPPFramework . Please tell me the license of XMPPFramework.

**Comment by farion** [comment]
Due to the podspec it is BSD.
https://github.com/robbiehanson/XMPPFramework/blob/master/XMPPFramework.podspec

**Comment by fu7mu4** [comment]
thanks for your reply, I understand,
