### ISSUE TITLE
Phone Contacts are not adding to Roaster first time?

### ISSUE THREAD

**Issue by bintu1234** [robbiehanson/XMPPFramework#685]
HI I am using xmpp Framework i am facing one issue like 
My Flow is like 
1)signup then sync Contacts from phone 
2)list contacts in one tableview.

first time when i signup and sync contacts the contacts are not showing in list even in openfire server.when i quit my app and reopen then sync contacts then working fine(showing in openfire server) 
and also at the time of signin also same issue when i login with existing user first time not showing any Contacts.

here is my implementation

for contacts syn i just use abaddress book which is working fine then i am adding evry list to xmppRosterlike below
`[[self appDelegate] addNewBuddyToMyAccount:tempNumber withNickName:[[tempContactList objectAtIndex:i] fullname]];`

`-(BOOL)addNewBuddyToMyAccount:(NSString *)buddyUserID  withNickName:(NSString *)nickName{
    
    
    NSString * buddyNameJID = [NSString stringWithFormat:@"%@@harjits-mac-mini-2.local",buddyUserID];
    
    XMPPJID *jid = [XMPPJID jidWithString:buddyNameJID];
    [[self xmppRoster] acceptPresenceSubscriptionRequestFrom:jid andAddToRoster:YES];
    [[self xmppRoster] addUser:jid withNickname:nickName];
    
    return YES;
}`

but where i am missing if any body face this issue please help me

**Comment by rv7284** [comment]
@bintu1234 Hey, I'm stuck with contact sync part in my iOS app. Can you help me out on how to achieve that?
