### ISSUE TITLE
Module KissXML not found

### ISSUE THREAD

**Issue by Artheyn** [robbiehanson/XMPPFramework#688]
Hi,

The exact issue is 

**XMPPSASLAuthentication.h** line 2
**"Module KissXML not found"**

To explain it more precisely, here is my Pod structure:

- **Conversation framework**, which uses XMPPFramework, declared in a private Pod repo and exposing this podspec:

```
Pod::Spec.new do |s|
 (...)
  s.dependency 'XMPPFramework'
end
```

Here no version is set as I doesn't want to use the ProcessOne fork because I need the latest version of Lumberjack in the XMPP Core. I will precise the original repository in my Main application Podfile, like detailed below.

- Main app with a Podfile looking like this:

```
source 'https://github.com/CocoaPods/Specs.git'
source 'ssh://git@github.com/private-specs-registry.git'

platform :ios, '8.0'
use_frameworks!

workspace 'MainApp'

# MainAppPods
def main_app_pods

    # Here I precise that I want to use the original repo of XMPPFramework (needed because I don't want to use the ProcessOne fork)
    pod 'XMPPFramework', git: 'https://github.com/robbiehanson/XMPPFramework'

    # Internal Conversation framework which uses XMPPFramework
    pod 'Conversation', '0.0.1'

end

target 'Messenger' do
    project 'Messenger'

    main_app_pods
end

pre_install do |installer|
    # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
    def installer.verify_no_static_framework_transitive_dependencies; end
end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            # To avoid "Undefined symbols for architecture" at build time.
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            # XMPPFramework is not bitcode compatible... We need to deactive that.
            # PR still open (2016/02/02) https://github.com/robbiehanson/XMPPFramework/issues/562
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        end
    end

    installer_representation.pods_project.build_configuration_list.build_configurations.each do |configuration|
      # To avoid "Undefined symbols for architecture" at build time for the Pods project.
      configuration.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
end
```

In my main application

First, when I do a `pod install` I have some warnings (I don't know if it's relevant for my issue):

```bash
Pod installation complete! There are 14 dependencies from the Podfile and 29 total pods installed.

[!] Can't merge user_target_xcconfig for pod targets: ["libxml_module", "Core", "Providers"]. Boolean build setting CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES has different values.

[!] Can't merge user_target_xcconfig for pod targets: ["libxml_module", "Core", "Providers"]. Boolean build setting CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES has different values.
```

And then when I try to build my main app I got this following error:

```
XMPPSASLAuthentication.h (line 2)
- Module KissXML not found
```

If you find some time to unlock me it will be really great.

![screen shot 2016-02-26 at 17 43 10](https://cloud.githubusercontent.com/assets/6149725/13358616/7c7e23fe-dcb0-11e5-81e5-8724064e4043.png)

**Comment by chrisballinger** [comment]
Try deleting the lines

`config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'`

**Comment by Artheyn** [comment]
Hi Chris,

Many thanks for your quick reply. Unfortunately I get the same Cocoapods warnings and the same compiling issue even after I deleted these lines (please see the attached image).

I have also upgraded my Conversation Framework pod spec (one which holds the XMPP reference) and add these two lines:

```ruby
  s.ios.frameworks = 'Foundation', 'UIKit', 'XMPPFramework'

  s.xcconfig = { 'HEADER_SEARCH_PATHS' => '$(SDKROOT)/usr/include/libxml2 $(PODS_ROOT)/XMPPFramework/module', 'ENABLE_BITCODE' => 'NO'}
end
```

FYI: I'm using **Xcode 7.2.1** and **Cocoapods 1.0.0.beta.4** (also tried with beta 3 but still the same issue).

I wonder if this issue is not thrown because I don't link to an official Pod (with a version) in my Conversation Framework podspec and so I'm forced to redefined the dependency in my main app project Podfile by adding a line pointing to the right repository:

```ruby
# MainAppPods
def main_app_pods
    pod 'XMPPFramework', git: 'https://github.com/robbiehanson/XMPPFramework'
(...)

end
```

Thanks for your time and your help.

Alexandre.

**Comment by Artheyn** [comment]
Another information: My Conversation Framework is developed and built in a separate integration project and this integration project, which directly includes the Conversation Framework source files and which link directly the XMPPFramework pod in his Podfile, compiles like a charm. It's only when I try to import my Conversation Framework in another project using a Podspec that it fails.

If it can help, here is my Headers Search Path of my two Pods dependencies:

![capture d ecran 2016-02-27 a 22 48 17](https://cloud.githubusercontent.com/assets/6149725/13375629/34e64706-dda5-11e5-8865-3b0147894483.png)
![capture d ecran 2016-02-27 a 22 49 22](https://cloud.githubusercontent.com/assets/6149725/13375630/350caa2c-dda5-11e5-91e4-825258929087.png)

**Comment by Artheyn** [comment]
Hi @chrisballinger ,

Sorry to bother you again, but I just built an example to point out my issue.
In fact, **the issue appears when using cocoapods 1.0.0.beta.4** (all previous 1.0.0.beta versions are working well).

Could you please follow this instructions to reproduce my issue?

1 - Clone this repository https://github.com/Artheyn/XMPPMainApp and open the XMPPMainApp.xcworkspace

2 - Select `Generic iOS Device` for the build target device

3 - Install cocoapods 1.0.0.beta.3

  `sudo gem install cocoapods -v 1.0.0.beta.3 --pre`

4 - Install pods
  `pod install`

5 - Build the XMPPMainApp project --> You should have a **BUILD SUCCEEDED**

6 - Install cocoapods 1.0.0.beta.4 or 1.0.0.beta.5
  `sudo gem install cocoapods -v 1.0.0.beta.4 --pre`

7 - Install pods
  `pod install`
  
8 - Clean and build the XMPPMainApp --> You should have a **BUILD FAILED** with this error:
    `XMPPFramework/Authentication/XMPPSASLAuthentication.h:2:9: Module 'KissXML' not found`


To explain the context again I have a Main application that uses a private Pod, the Conversation Module, that uses internally XMPPFramework.

**Main App** -> **Conversation Module** -> **XMPPFramework**

My Conversation Module is on a private repository with his own podspec file from [this repository](https://github.com/Artheyn/XMPPPods1.0.0Beta4) and available trough cocoapods using a [private pod repository](https://github.com/Artheyn/ArtheynSpecsRegistry/tree/master/XMPPPods1.0.0Beta4/0.0.1)


`XMPPPods1.0.0Beta4/Podfile`

```
Pod::Spec.new do |s|
  s.name = 'XMPPPods1.0.0Beta4'
  s.version = '0.0.1'
  s.license = 'Copyright'
  s.summary = 'Test compilation of module that embed XMPPFramework.'
  s.homepage = 'https://github.com/Artheyn/XMPPPods1.0.0Beta4'
  s.authors = { 'Me' => 'artheyn@gmail.com' }
  s.source = { :git => 'https://github.com/Artheyn/XMPPPods1.0.0Beta4.git', :tag => 'v0.0.1' }
  s.ios.deployment_target = '8.0'
  s.source_files = "XMPPPods1.0.0Beta4/Sources/**/*.{swift}"
  s.resources = "XMPPPods1.0.0Beta4/Resources/**/*.{xcassets,pdf,png,jpeg,jpg,storyboard,xib,otf}"
  s.requires_arc = true
  s.dependency 'XMPPFramework'

  s.xcconfig = {
    'HEADER_SEARCH_PATHS' => '$(inherited) $(SDKROOT)/usr/include/libxml2 $(PODS_ROOT)/KissXML/libxml $(SDKROOT)/usr/include/libresolv',
    'LIBRARY_SEARCH_PATHS' => '"$(PODS_ROOT)/XMPPFramework/Vendor/libidn"',
    'OTHER_LDFLAGS' => '"-lxml2"', 'ENABLE_BITCODE' => 'NO',
    'OTHER_CFLAGS' => "$(inherited) -DDDXML_LIBXML_MODULE_ENABLED=1",
    'OTHER_SWIFT_FLAGS' => "$(inherited) -DDDXML_LIBXML_MODULE_ENABLED"
  }
end
```

And my main app requires my Conversation Module in his Podfile (and resolves the XMPPFramework dependency of my module by requiring also the XMPPFramework repository in his Podfile):

`XMPPMainApp/Podfile`

```
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Artheyn/ArtheynSpecsRegistry.git'
platform :ios, '8.0'
use_frameworks!


target 'XMPPMainApp' do
    pod 'XMPPPods1.0.0Beta4', :git => 'https://github.com/Artheyn/XMPPPods1.0.0Beta4', :branch => 'master'
    pod 'XMPPFramework', :git => 'https://github.com/robbiehanson/XMPPFramework'
end
```

**It works with cocoapods 1.0.0.beta versions including the 1.0.0.beta.3 and throws a `KissXML not found` error since the 1.0.0.beta.4 version.**


Thanks for your help.
Alexandre.

**Comment by Artheyn** [comment]
@chrisballinger Any idea? Should I open an issue in the Cocoapods repository?

**Comment by chrisballinger** [comment]
@Artheyn Very strange, it definitely seems like a CocoaPods issue if it was working in beta3 and all of a sudden doesn't work in beta4. Have you tried beta6?

**Comment by Artheyn** [comment]
@chrisballinger Thanks for your reply!

Yup... Same issue with beta6... When I check the CHANGELOG.md file of Cocoapods between beta3 and beta4 I can't find very relevant information. I will still investigate and if I can't figure it out I will open an issue on the Cocoapods repository.

Thanks for your help :)

**Comment by Artheyn** [comment]
I've retested with Cocoapods 1.0.1 and all seems ok. Thanks.

**Comment by jffiorillo** [comment]
I'm getting this issue with Cocoapods 1.0.1. when updating from 3.6.6 to pod 'XMPPFramework', :git => "https://github.com/robbiehanson/XMPPFramework.git", :branch => 'master'
