### ISSUE TITLE
Objects are not getting saved on the first time

### ISSUE THREAD

**Issue by arturmalek** [robbiehanson/XMPPFramework#691]
Hey there, 

im using XMPP Framework in a project, i really like the Framework, great stuff ! 

Im using XMPPFramework for a chat application and i got a problem regarding
the core data storage. 
When i install the app for the first time and write messages, these written messages
are gone, if i start the app another time. 
I think, there might be a problem in the configuration of the MOC.

Do somebody have/had similar problems ? 

Any advice or hints would be appreciated! 

Best regards,

Artur

**Comment by hemant3370** [comment]
@arturmalek Did you solve this? I am facing a similar problem.

**Comment by arturmalek** [comment]
Hey @hemant3370 ,

i found out, that this problem only occurred, when i started the app on the simulator. 
It doesn´t happen on devices.

Best regards,

Artur
