### ISSUE TITLE
XEP-0313 support

### ISSUE THREAD

**Issue by nguyenchiencong** [robbiehanson/XMPPFramework#696]
XEP-0313 support?

**Comment by Nyco** [comment]
Maybe we ([Erlang Solutions](https://www.erlang-solutions.com/products/mongooseim.html), makers of the [MongooseIM](https://github.com/esl/MongooseIM) XMPP server) can contribute [XEP-0313: Message Archive Management](http://xmpp.org/extensions/xep-0313.html).

**Comment by chrisballinger** [comment]
Fixed in #733
