### ISSUE TITLE
Unable to delete roster of length less than saveThreshold (500)

### ISSUE THREAD

**Issue by CW-CZ-PiyushSharma** [robbiehanson/XMPPFramework#701]
Hi ,

Can you please help me with this scenario.

SaveThreshold default is 500 in the XMPPFramework whereas my roster length is 50.

			if (++unsavedCount >= saveThreshold) // THis doesnt get called ever.
			{
				[self save];
				unsavedCount = 0;
			}

I am afraid if i change default value of saveThreshold to 1 (In my app a user can have only 1 contact ) there would be lot of memory n CPU work that would cause App to crash. Is it true? 

How should i handle delete of roster with only 1 contact.

**Comment by vitalyster** [comment]
`saveThreshold` is milliseconds count, not roster items
