### ISSUE TITLE
New users not getting saved in CoreData

### ISSUE THREAD

**Issue by CW-CZ-PiyushSharma** [robbiehanson/XMPPFramework#712]
I am receiving the rosterItem for NewUsers but when i am trying to fetch full list of roster, the Newly added users is not present in the list sometimes.
I am trying to fetch only those users with Subscription 'Both' and a particular Group name.
The New User is not getting saved in the Group even on receiving proper fields.

I am unable to find out the cause of this inconsistency.

**Comment by davidah3** [comment]
Are you fetching users list after the - (void)xmppRosterDidEndPopulating:(XMPPRoster *)sender delegate is fired?
