### ISSUE TITLE
Stream Management delegate methods not called

### ISSUE THREAD

**Issue by ravenjam** [robbiehanson/XMPPFramework#716]
Hi,

I'm using XMPPFramework and implementing stream management feature. In didAuthenticate method I did:

```
self.xmppSMManager = [[XMPPStreamManagement alloc] initWithStorage:[[XMPPStreamManagementMemoryStorage alloc] init]];

[self.xmppSMManager addDelegate:self delegateQueue:dispatch_get_main_queue()];

[self.xmppSMManager enableStreamManagementWithResumption:YES maxTimeout:600];
```

However the delegate methods:

```
- (void)xmppStreamManagement:(XMPPStreamManagement *)sender wasEnabled:(DDXMLElement *)enabled;

- (void)xmppStreamManagement:(XMPPStreamManagement *)sender wasNotEnabled:(DDXMLElement *)failed;
```

are never called.

I also added delegate protocol in header. Has anyone experienced similar problem? What's the solution?

**Comment by davidah3** [comment]
Try to activate SM after enable stream management :
`[self.xmppSMManager activate:xmppStream];`

Optionally you can use this line for automatic request acks before activation:
`[xmppStreamManagement automaticallyRequestAcksAfterStanzaCount:5 orTimeout:5.0f];`

**Comment by ravenjam** [comment]
@davidah3 Thank you, yea I saw your comments late and just figured it out by myself. You are absolutely correctly and thank you for answering the question! Closing this.

**Comment by zerox92** [comment]
Just incase anyone else faces this issue in future, stream management has to be enabled after `XMPPStream` is authenticated which is according to XEP-0198.

**Comment by shubham1164** [comment]
Hi Ravenjam/Zerox92, 
Please share the complete code for stream management in XMPPFramework in Swift language. I have used the below code after didAuthenticate method, no delegates are being called for XMPPStreamManagement:

//Code for XMPPStreamManagement
        streamManagement = XMPPStreamManagement(storage: XMPPStreamManagementMemoryStorage()
        streamManagement.addDelegate(self, delegateQueue: DispatchQueue.main)
        streamManagement.autoResume = true
        streamManagement.enable(withResumption: true, maxTimeout: 0)
        streamManagement.requestAck()
        streamManagement.activate(stream)
        streamManagement.requestAck()

//Code for stream
xmppRoster = XMPPRoster(rosterStorage: xmppRosterStorage)
        stream = XMPPStream()
        stream.addDelegate(self, delegateQueue: DispatchQueue.main)
        xmppRoster.activate(stream)
        stream.myJID = XMPPJID(string: "100007@localhost1")
        stream.hostName = "192.168.1.168"
        stream.hostPort = 5222
        //stream.authenticate(withPassword: "pass")
        do {
            try stream.connect(withTimeout: 60000)
        }
        catch {
            print("error occured in connecting")
        }

I am calling both the above in separate method call rom button after auth is done. Pleas help

**Comment by skipper570** [comment]
@shubham1164 I have exactly the same problem.
