### ISSUE TITLE
Show roster in Flight mode (offline)

### ISSUE THREAD

**Issue by seidju** [robbiehanson/XMPPFramework#723]
Hi everyone.
I'm developing simple messaging app using XMPPFramework. So after roster is fetched, it stores in CoreData, but when i disable network (or setup flight mode), i can't see any of the users, that were fetched. I found *.sqlite file, and after i terminate app it stores roster items, but when i startup application it clears, and because that there's no network it didn't re-fetch.
I also check autoClearAllUsersAndResources = false, but it didn't help

Thanks for any help!

**Comment by davidah3** [comment]
In fact, one thing you can do is inherit XMPPRosterStorage protocol, overwrite methods and store contacts in the way you serve.

**Comment by seidju** [comment]
Well, it's my mistake. I should set `autoRemovePreviousDatabaseFile = NO`, to prevent re-create roster storage at start up

**Comment by brunoguerios** [comment]
@seidju You should reopen this issue since the documentation says `autoRemovePreviousDatabaseFile` is `false` by default. I took quite some time to figure out the issue because I was trusting the documentation =/
