### ISSUE TITLE
When I receive offline messages , the value of the Body of the message is to " ????"

### ISSUE THREAD

**Issue by segunlee** [robbiehanson/XMPPFramework#728]
When I receive offline messages , the value of the Body of the message is to " ??????" .
"??????" is Korean Language (한글메시지)
XMPP Server is Openfire Server

Someone help me. 

This is receive message from XMPPFramework
`<message xmlns="jabber:client" type="chat" to="TO_HERE" id="353ED491-A83B-4DFE-90A8-312A3FBD1DDF" from="FROM_HERE">
<body>??????</body>
<request xmlns="urn:xmpp:receipts"/>
<delay xmlns="urn:xmpp:delay" from="SERVER" stamp="2016-05-23T08:50:51.039Z"/>
</message>`

**Comment by chrisballinger** [comment]
This may be a unicode error from OpenFire

**Comment by IOSDeveloperProgrammer** [comment]
@segunlee  @chrisballinger I'm having same problem . Did you find solution. But here my issue is: i could not receive offline message . Please help me in this issue.
