### ISSUE TITLE
feature-not-implemented 501 ERROR?

### ISSUE THREAD

**Issue by bintu1234** [robbiehanson/XMPPFramework#741]
@drodriguez @chrisballinger Hi I am working with the XMPP Framework. I'm facing one issue while I'm Connecting I'm getting bellow error 

`<iq type="error" to="manager.iserver" id="302-3697"><query xmlns="jabber:iq:version"/><error type="cancel" code="501"><feature-not-implemented xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></iq>
2016-06-04 06:33:24:603[11365:e03] RECV: <message xmlns="jabber:client" from="manager.iserver" to="9156224887@iserver/Resourcer"><body>You are using an invalid client, and therefore will be disconnected. Please ask your system administrator for client choices.</body></message>`
How to resolve it Please help me if any body knows about this issue.
And also I'm getting Policy-Violation error If any body knows about Below error please help me 1
` <stream:error xmlns:stream="http://etherx.jabber.org/streams"><policy-violation xmlns="urn:ietf:params:xml:ns:xmpp-streams"/></stream:error>`

**Comment by drodriguez** [comment]
@bintu1234 it is very rude mentioning people randomly, specially with a poorly written issue that lacks of the proper research on your part.

Anyway, the error is telling you what to do: `Please ask your system administrator for client choices`. The system administrator is someone related to the server you are trying to connect, not the library you are trying to use. Please, review whatever documentation you have available for that server and contact them if you still have problems, explaining them what you have tried and what haven't worked.

**Comment by bintu1234** [comment]
@drodriguez  sorry for your inconvenience,But I don't have enough guide.And thanks for the replay

**Comment by MadBurea** [comment]
but what to do with this error.

 **RECV: <iq xmlns="jabber:client" type="error" id="page1" to="Burea@ip-999-31-53-77.ec2.internal/8i0h8q6jiq"><error code="501" type="cancel"><feature-not-implemented xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></iq>**

There is not specific error is there. i m confused with this don't know why occur as this error occur while fetching hsitory from openFire using XMPP.

Please help

**Comment by shoaibhassanWhizpool** [comment]
@MadBurea , @bintu1234 did you find any solution for 

> error code="501" type="cancel"
> feature-not-implemented xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"

as i am also facing same problem while implementing VOIP over ejabberd server.

**Comment by Atulakabari** [comment]
mongooseim -XMPP:-
when we test using one to one chat message then it is working fine. but when I try to create a group then getting error "NOT Authorized"

------------------Server  log ----------------------
<error code='501' type='cancel'><feature-not-implemented xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/></error></iq>">>

I am facing issues with group chat.so can you please advice me for the same.
thanks

**Comment by kiran4991** [comment]
I am facing same issue while sending one to one chat
