### ISSUE TITLE
iOS XMPP - Socket closed when app is suspended or the device is locked

### ISSUE THREAD

**Issue by sudhakar-nataraj** [robbiehanson/XMPPFramework#744]
I am creating a live chat app for the support team agents, who connects with the website visitors through XMPP. We are using Openfire and have implemented Workgroup Queue extension XEP-0142 in the iOS app, using XMPPFramework. We are using Fastpath Webchat in the website.

The issue is, when the app is suspended sometime after the user minimised it or when the device screen is locked, the socket is closed, stream gets disconnected and so the chat gets disconnected. The temporary MUC room created for the particular chat (by the Fastpath) shows that the agent is left and the chat room is also closed. We want the chat to continue without closing, so that when the agent from iOS can reconnect when reopening the app. We want the chat to be disconnected only when the app is terminated. 

I have checked in lot of websites and couldn't find a proper solution, at least the solution I could understand. We are not using any background services like VOIP.

**Comment by chrisballinger** [comment]
You will need to implement XEP-0357, however, I'm not sure if any servers
support it for group chats yet.

**Comment by sudhakar-nataraj** [comment]
thanks for the response, @chrisballinger .. I have already implemented the push notifications using a custom openfire plugin APNS and is working fine when the chat is active. My only issue is that when the app is suspended or device is locked, the present chat in which the agent involves, shows that the agent has left the conversation and closes the chat room. This is because the socket and the stream is getting disconnected..

My requirement is, when the app is suspended or device is locked, I need the chat to be alive, so that the agent can rejoin the chat room, when he connects again from the app..

**Comment by chrisballinger** [comment]
You may want to look into XEP-0198 with a very long timeout

On Fri, Jun 10, 2016 at 10:29 AM, sudhakar-nataraj <notifications@github.com

**Comment by sudhakar-nataraj** [comment]
I tried implementing the session management with a very long timeout, but as XMPPFramework iOS supports only basic ack feature, but not the resumption, the timeout is changed to 0 by default.

**Comment by sudhakar-nataraj** [comment]
We couldn't get any support from Openfire yet. Is there any alternative solution available? How does the IMs work in iOS, with this disconnection problem?

**Comment by chrisballinger** [comment]
You may wish to change your backend implementation. There isn't too much more you can do from the client end if you've implemented XEP-0198 and XEP-0357.

You may want to investigate Prosody or ejabberd instead.
