### ISSUE TITLE
Notifications?

### ISSUE THREAD

**Issue by bintu1234** [robbiehanson/XMPPFramework#749]
HI I am working with xmpp Framework working fine.Now I want to know is there any way to get the Notifications when my app is  in inactive state(Terminated). I know with push Notifications we can achieve that .But i want with out using push notification can we achieve this in ios.Please help me

**Comment by chrisballinger** [comment]
Look into XEP-0357

**Comment by bintu1234** [comment]
@chrisballinger  Thanks for the replay.But I didn't find this XEP-0357.How to import this extention into my project

**Comment by chrisballinger** [comment]
This is not exactly a support forum to help you write your project, however
this use case should be covered in the documentation.
