### ISSUE TITLE
xmppStream didReceiveMessage not works correctly

### ISSUE THREAD

**Issue by ITArtist** [robbiehanson/XMPPFramework#752]
Hello.

There are some problems in iOS 9.

My "xmppStream: didReceiveMessage" not works before sending some messages.

When my app launched, it receives some offline messages- but after, no messages are received.

For example, when I send empty message to someone, now the stream gets messages,
but before sending message, app doesn't get any messages.

On the other hands, "xmppStream: didReceivePresence" works correctly.

Any advice? Thank you.

**Comment by adozenlines** [comment]
Take a good look at the name of the method it is responsible for receiving messages only and not the sending of message. Study the entire codebase for the framework to know how it works instead of assuming how it works.

**Comment by ITArtist** [comment]
@adozenlines 
Thank you for your advice, but I think you don't understand what I asked

My detail problem is the below:

A: iOS Client, B: Spark Client

--- When App launched,

A: 
[O] Got offline messages through "xmppStream: didReceiveMessage" function
[O] Got presence
[O] God buddy list through roster delegate

--- When 'B' sent message to A

[X] Got realtime messages through "xmppStream: didReceiveMessage" function

--- When 'B' went offline

[O] Got presence

--- When 'A' sent message to B

[O] messages are sent A to B

--- Now 'B' sent message to A *** PROBLEM POINT ***

[O] Got realtime messages through "xmppStream: didReceiveMessage" function



Once A sent message to B, everything works perfectly, but before, A cannot receive message...

**Comment by adozenlines** [comment]
If the last steps are always reproducible try increasing the log level of the framework and look for errors.

**Comment by IOSDeveloperProgrammer** [comment]
@ITArtist  @adamvduke  Hi, I having same problem. A is offline/online , B is offline and send message to user A. and when user A comes into online/offline, it must receive all messages that were sent by user B during offline messages. How can i receive these messages. i'm totally stuck on this issue. Please help if any one knows this solution. Thanks

**Comment by RollingGoron** [comment]
That's not how offline messages work. User A is online and sends messages to User B, who is offline. When User B signs on, he will receive the message that User A sent.

**Comment by IOSDeveloperProgrammer** [comment]
@RollingGoron  i'm updated question once check pls
