### ISSUE TITLE
Vendor folder file is missing

### ISSUE THREAD

**Issue by taojeff** [robbiehanson/XMPPFramework#755]
Hello, I today on the git download the XMPPFramework you upload.When I opened the iPhonedemo I haven't found the Vendor folder file
![db5a361b-bb04-478c-ae12-10066b0d820c](https://cloud.githubusercontent.com/assets/19642626/16475227/7eadd4f6-3eaf-11e6-9e6d-4a40731b8cf6.png)

**Comment by chrisballinger** [comment]
Use CocoaPods
