### ISSUE TITLE
mistakenly use of NSPrivateQueueConcurrencyType

### ISSUE THREAD

**Issue by simpzan** [robbiehanson/XMPPFramework#76]
http://stackoverflow.com/questions/11436358/nsprivatequeueconcurrencytype-context-can-only-operate-within-performblock

when creating -managedObjectContext of XMPPCoreDataStorage. NSPrivateQueueConcurrencyType type is not correct here. NSPrivateQueueConcurrencyType context can only used with -performBlock...
the old NSConfinementConcurrencyType is appropriate for your code.
check up the doc: http://developer.apple.com/library/mac/#releasenotes/DataManagement/RN-CoreData/_index.html

the following is quoted from apple doc: http://developer.apple.com/library/ios/#releasenotes/General/WhatsNewIniPhoneOS/Articles/iOS5.html

"When sending messages to a context created with a queue association, you must use the performBlock: or performBlockAndWait: method if your code is not already executing on that queue (for the main queue type) or within the scope of a performBlock... invocation (for the private queue type). Within the blocks passed to those methods, you can use the methods of NSManagedObjectContext freely. "

**Comment by idoza** [comment]
NSConfinementConcurrencyType is first deprecated on iOS 9.
How can we replace it considering this issue ?
