### ISSUE TITLE
How can I get a path of the database?

### ISSUE THREAD

**Issue by orkhanalizade** [robbiehanson/XMPPFramework#773]
I want to get a path of the database where all contacts, messages and etc. save.

How can I get this path?

**Comment by andresinaka** [comment]
@orkhanalizade if you just need this for debug purposes just set a breakpoint in: `- (NSString *)persistentStoreDirectory` from `XMPPCoreDataStorage` and check what's the returned value. 

If you need this for some other purpose maybe you can extend your `XMPPCoreDataStorage.m` subclass and override: `- (void)willCreatePersistentStoreWithPath:(NSString *)storePath options:(NSDictionary *)theStoreOptions'. You will have your path there.

**Comment by orkhanalizade** [comment]
@andresinaka thanks! I'll try it!
