### ISSUE TITLE
Why I cannot get my own VCard?

### ISSUE THREAD

**Issue by orkhanalizade** [robbiehanson/XMPPFramework#784]
I'm using this function to get my own VCard, but in response I get this error:

    namespace warning : xmlns: URI vcard-temp is not absolute
    <vCard xmlns="vcard-temp" version="2.0" prodid="-//HandGen//NONSGML vGen v1.0//E

My function:

    public func getMyVCard() {
        print("My full data: \(OneChat.sharedInstance.xmppStream!.myJID.full())")
        let iq: DDXMLElement = DDXMLElement.elementWithName("iq") as! DDXMLElement
        iq.addAttributeWithName("from", stringValue: "\(OneChat.sharedInstance.xmppStream!.myJID.full())")
        iq.addAttributeWithName("type", stringValue: "get")
        iq.addAttributeWithName("id", stringValue: "v1")
        
        let vCardXML: DDXMLElement = DDXMLElement(name: "vCard", xmlns: "vcard-temp") as! DDXMLElement
        iq.addChild(vCardXML)
        
        OneChat.sharedInstance.xmppStream?.sendElement(iq)
        print(iq)
    }

Can anyone help me with it?

**Comment by appstershipra** [comment]
I am also facing the same problem. Can anyone help me out on this?

**Comment by MaikoHermans** [comment]
@orkhanalizade Did you ever fix this? I'm also not able to obtain my card
