### ISSUE TITLE
didReceiveInvitation() is not being called in XMPPFramework and Swift 2

### ISSUE THREAD

**Issue by TheEngineerz** [robbiehanson/XMPPFramework#786]
Any expert can give me 2 minutes only ?

Here on this link

http://stackoverflow.com/questions/38895012/didreceiveinvitation-is-not-being-called-in-xmppframework-and-swift-2

**Comment by andresinaka** [comment]
Solved on StackOverflow. We can close this!

**Comment by TheEngineerz** [comment]
Yes thanks
