### ISSUE TITLE
Could not build module 'XMPPFramework'

### ISSUE THREAD

**Issue by x3mall1986** [robbiehanson/XMPPFramework#787]
After update XMPPFramework with 
`pod 'XMPPFramework', :git => "https://github.com/robbiehanson/XMPPFramework.git", :branch => 'master'`

<img width="1182" alt="2016-08-12 15 54 55" src="https://cloud.githubusercontent.com/assets/1582648/17622934/07cd6c20-60a6-11e6-939e-cdbcb27d67e8.png">

**Comment by chrisballinger** [comment]
Can you figure out why it doesnt build? Xcode version, etc?

Check the build logs for more detailed output, especially for XMPPFramework itself

**Comment by x3mall1986** [comment]
Project compile with this error succeful, 
xCode 7.3, iOS 9.3.4

I was cleaning the project and delivered data but it did not help

**Comment by x3mall1986** [comment]
For pod 'XMPPFramework' only, there is no this error

**Comment by chrisballinger** [comment]
What are the error logs

**Comment by x3mall1986** [comment]
There is no error logs, project compile succeful, but not work autocomplete for XMPPFramework class
<img width="1439" alt="2016-08-14 09 00 25" src="https://cloud.githubusercontent.com/assets/1582648/17647549/980a39a0-61fd-11e6-91c7-6ef2107111ca.png">

**Comment by x3mall1986** [comment]
https://groups.google.com/forum/#!topic/xmppframework/vyx1TE5iYmc

**Comment by mudox** [comment]
I came across the same issue. 
Replacing `@import XMPPFramework;` with `#import "XMPPFramework/XMPPFramework.h"` removed the warning.

**Comment by progn** [comment]
I have the same issue. It happen after I updated cocoapods to the new version (1.0.1). 
So, I just remove 1.0.1 and install 0.39, and now it works!

http://stackoverflow.com/questions/37233445/install-old-cocoapods

**Comment by x3mall1986** [comment]
Downgrade to pod 0.39 doesn't solve the problem.
I solve the problem by adding` #import <XMPPFramework/XMPPFramework-umbrella.h>`

**Comment by JasonYaoSiXu** [comment]
@progn  it does not work: [!] The `Specs` repo requires CocoaPods 1.0.0 -  (currently using 0.39.0)

**Comment by flyweights** [comment]
i too!
