### ISSUE TITLE
Is XMPPFramework changes Vcard locally on Vcard updating?

### ISSUE THREAD

**Issue by orkhanalizade** [robbiehanson/XMPPFramework#797]
Is XMPPFramework changes Vcard locally on Vcard updating?

Because I update my own Vcard, then retrieving in and see that information has been changed. But another users see my old Vcard.

How can I update it for other users too, when I change my Vcard?

**Comment by GKrishna1** [comment]
The other users should be able to fetch your vcard like this:

`    XMPPvCardCoreDataStorage *xmppvCardStorage = [[XMPPvCardCoreDataStorage alloc] initWithInMemoryStore];
    XMPPvCardTempModule *xmppvCardTempModule = [[XMPPvCardTempModule alloc] initWithvCardStorage:xmppvCardStorage];
    [xmppvCardTempModule activate:[self xmppStream]];
    [xmppvCardTempModule addDelegate:self delegateQueue:dispatch_get_main_queue()];
    [xmppvCardTempModule vCardTempForJID:<your_jid> shouldFetch:YES];
`

**Comment by orkhanalizade** [comment]
@GKrishna1  Thank you!
It works, but again, it takes some time to get up to date vCards. So still I cannot get new vCards immediately. May be I need to do something more?

**Comment by orkhanalizade** [comment]
@GKrishna1  I think it stores those data in local memory, because when I remove the app and install again it fetches new data. So I need to update local storage data
