### ISSUE TITLE
'XMPPFramework/XMPPFramework.h' file not found

### ISSUE THREAD

**Issue by loyalwind** [robbiehanson/XMPPFramework#805]
XMPPFramework/XMPPFramework.h file not found ,but my project have this file . i manage XMPPFramework by using cocoapods ! why XMPPFramework/XMPPFramework.h and  XMPPFramework/XMPPRoom.h  etc file not found?

**Comment by x3mall1986** [comment]
1. Show, plz, your pod's file
2. Which version of cocoapods you are using?

**Comment by loyalwind** [comment]
after i try again pod install ,the probleom is resolved ,but also thank you for you reply ！
