### ISSUE TITLE
pod not working

### ISSUE THREAD

**Issue by AzeemKhan123** [robbiehanson/XMPPFramework#811]
Getting this error
Pre-downloading: `XMPPFramework` from `https://github.com/robbiehanson/XMPPFramework.git`, branch `master`
[!] Unable to satisfy the following requirements:
- `KissXML (~> 5.1.2)` required by `XMPPFramework/Core (3.7.0)`
None of your spec sources contain a spec satisfying the dependency: `KissXML (~> 5.1.2)`.

This is my Pod File
target '*****' do
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
pod 'XMPPFramework', :git => "https://github.com/robbiehanson/XMPPFramework.git", :branch => 'master'
pod 'Google/SignIn'
pod 'OpenCV', '2.4.9'
end

I really need help how to run this. I have tried cocopod 1.0.1 as well as 1.1.0.rc.2. I get same error.

**Comment by codeliujun** [comment]
how to resolve it  ~~~~~~

**Comment by chrisballinger** [comment]
`pod repo update`
`pod install`
