### ISSUE TITLE
Crashing on xmlNodePtr rootCopy = xmlCopyNode(root, 2);

### ISSUE THREAD

**Issue by abbas-mulani** [robbiehanson/XMPPFramework#812]
Crashing application on following line (XMPPParser.m)

`xmlNodePtr rootCopy = xmlCopyNode(root, 2);`

Can anyone please help me to resolve this issue.

**Comment by chrisballinger** [comment]
I'm gonna guess that root is NULL. I suggest you put a breakpoint there and
try to figure out why its NULL.

**Comment by ilei131** [comment]
I have the same problem. How to fix?

**Comment by chrisballinger** [comment]
@abbas-mulani @ilei131 Please post a full traceback. This can probably be resolved by checking for NULL and aborting, but I need more information.

**Comment by ilei131** [comment]
iOS10 crash occasionally,iOS 9 is OK.

**Comment by ilei131** [comment]
I find the reason. I have modified xmppparser.m before, but I forget to reset it. I have added the following code:
"xmlFreeNs(attrNs);".  Now I remove it, no more crash!
