### ISSUE TITLE
Saving contacts from XMPPRoster

### ISSUE THREAD

**Issue by x3mall1986** [robbiehanson/XMPPFramework#816]
Hello!
After restarting the application, while in XMPPStream is not connected to the network, then XMPPUserCoreDataStorageObject in XMPPRoster absent and appears only when XMPPStream online. Is it possible to store contacts and get them when XMPPStream Offline or should I create a new database and copy XMPPUserCoreDataStorageObject it?

Thanks in advance for your help.

**Comment by seidju** [comment]
I faced the same issue before and I couldn't get it work properly at the end, so I ended up with creating my own CoreData base.

**Comment by vickydhas** [comment]
XMPPFramework by rights have been designed with legacy XMPP Chat and not mobile friendly activities as its business logic may differ from app to app.

Hence as @seidju did please create your own database schema in core data and use the chat mechanism and manage the contacts.

You can close this issue as its not relevant to XMPP Framework error.
