### ISSUE TITLE
3.7.0 pod release

### ISSUE THREAD

**Issue by CraigLn** [robbiehanson/XMPPFramework#818]
Hello, 

I was curious what your timeline is for the cutting the tag for the 3.7.0 pod release?

Thank you!

**Comment by chrisballinger** [comment]
Good question. I think there are some issues that still need to be
resolved, but the current release is so outdated that I should probably
push one out soon.

The other issue is that all of the subspecs need to be linted individually
and it takes _forever_.

**Comment by ProjectLane** [comment]
Thank you for the response.  

Is there a way I can track the remaining issues, so I can better estimate when a new release can be expected?

Thanks again!

**Comment by MingLoan** [comment]
hi.
I would like to build my own framework based on XMPPFramework, but I can't find a way to add your framework via cocoa pods to my podspec since pod spec won't support things like :branch => '...'
I am waiting for the new release to start my work. 
Could I know when can the release will be there.

**Comment by chrisballinger** [comment]
It is difficult to publish new pod versions due to the large number of
subspecs. I think it is time to reevaluate whether or not it is valuable to
have subspecs in the first place, and just include everything.
