### ISSUE TITLE
Could not build Objective-C module 'XMPPFramework' and XMPPvCardTempCoreDataStorageObject.h:13:9: 'XMPPvcardTemp.h' file not found

### ISSUE THREAD

**Issue by JasonYaoSiXu** [robbiehanson/XMPPFramework#838]
I use Swift
This is my pod file:
  platform :ios, '9.0'
  use_frameworks!

target 'XMPP_Test' do
  pod 'XMPPFramework', :git => "https://github.com/robbiehanson/XMPPFramework.git", :branch => 'master'
end

My cocoa pods version is: 1.0.1
My Xcode version is: 8.1
Deployment Target is: iOS 10.1

**Comment by JasonYaoSiXu** [comment]
A xi ba, i solve the problem, i update my cocoa pods version to 1.1.1.

**Comment by JasonYaoSiXu** [comment]
But use other computer it does't work for me.

**Comment by zaq42** [comment]
Xcode (8.3 beta) reports (for 3.7.0): Non-portable path to file "XMPPvCardTemp.h"; specified path differs in case from file name on disk (in file XMPPvCardTempCoreDataStorageObject.h)

On disk, there's a capital C:  XMPPvCardTemp, but the above file has a lower case c:

#import "XMPPvcardTemp.h"
