### ISSUE TITLE
MUCLIGHT - Chat delivery receipt not received.

### ISSUE THREAD

**Issue by vickydhas** [robbiehanson/XMPPFramework#839]
Hello Team,

Is there no support for the chat delivery receipt for for the MUCLight chat message stanza's. 

I am able to get the chat states <received> for the single chat but not for the MUC Light group message type == "groupchat".

**Comment by vickydhas** [comment]
Hello Robbie, any update on this as I am unable to get the delivered <received> tag for the muc light module messages. Is this limitation on the server ??

**Comment by zaidshaikh112** [comment]
hi  vickydhas 
have you resolved this please let if any one can help us

**Comment by vickydhas** [comment]
We never enabled the chat delivery receipt for the MUC Light, as it was an innovation project. The delivery receipt is only possible as of now in the Single Chat so closing this issue discussion. If any advancement from the MongooseIM server guys and XMPP Robbiehanson side support we can discuss this more.
