### ISSUE TITLE
How to extend XMPPMessageArchiving_Message_CoreDataObject?

### ISSUE THREAD

**Issue by brunoguerios** [robbiehanson/XMPPFramework#843]
I'm currently trying to extend the archived message's NSManagedObject in order to add a couple new attributes, but I'm finding it not that easy to do.

I was trying not to fork the repo and customize the code, but I'll go with that if I'm not able to find a simpler solution.

Is it possible to be done only with extensions or should I subclass? If I do have to subclass, should I only subclass XMPPMessageArchivingCoreDataStorage and provide a custom XMPPMessageArchiving_Message_CoreDataObject?

Could anyone provide some simple steps or at least point me in the right direction?

**Comment by adozenlines** [comment]
You cannot modify those files without updating the coredata uml schema via xcode.

**Comment by brunoguerios** [comment]
I imagined I'd have to provide another NSManagedObject subclass, but I was hoping I could somehow extend or subclass XMPPMessageArchivingCoreDataStorage so it would use my model instead.

The only way I see it working is by either forking the repo or providing a custom XMPPMessageArchivingCoreDataStorage to XMPPMessageArchiving, which would mean rewriting the whole class.

**Comment by adozenlines** [comment]
The implementation is based on xmpp standards and doing what you're suggesting is going against the standard and asking for trouble when the server and client tries to send the data. If you have a requirement implement that requirement separately and allow either the delegate of the archive provide you the feedback or use a fetchrequestcontroller to join the message archive entity with your entity implementation to feed the intended UI.

**Comment by brunoguerios** [comment]
I don't want to change anything on the messaging standards itself, but I do want to populate my entity to properly feed the UI.
Even though the ideia of essentially having every message duplicated in my app doesn't seem ideal, I think I'll go with your suggestion of using a NSFetchedResultsController to join the message archive entity with my custom entity. This way I'll benefit from all the logic implemented in the archiving class and I'll simply add some more to it.
Thanks for the discussion @adozenlines
