### ISSUE TITLE
Can Someone send Swift 3 compatible code.

### ISSUE THREAD

**Issue by niladri-1437** [robbiehanson/XMPPFramework#852]
I have developed a project on swift 3. While adding this library causing framework issue. Can some please send swift 3 compatible code?

**Comment by ChanchalW** [comment]
Hi am also facing issues in swift 3.1. My project show 263 error in framework.

**Comment by chrisballinger** [comment]
@ChanchalW  This framework works with any version of Swift, including Swift 3. XMPPFramework is written entirely in Objective-C.
