### ISSUE TITLE
How to delete or Exit Particular Group using XMPP in iOS

### ISSUE THREAD

**Issue by shraddha-patel-1891** [robbiehanson/XMPPFramework#857]
Currently i am making chat application and i required to delete group.

For delete group i tried 2 solution but its not work.

1st solution i applied as follow :-
xmppRoomStorage = [[XMPPRoomMemoryStorage alloc] init];
XMPPJID *roomJid = [XMPPJID jidWithString:self.strnameofgroup];
_xmppRoom = [[XMPPRoom alloc] initWithRoomStorage:xmppRoomStorage jid:roomJid];
[_xmppRoom removeDelegate:self delegateQueue:dispatch_get_main_queue()];
[_xmppRoom deactivate];
[_xmppRoom leaveRoom];

2nd solution i applied as follow :-

1st fetch all members of the group and then all members leave from manually but it also not working.

NSXMLElement *query = [NSXMLElement elementWithName:@"query" xmlns:@"http://jabber.org/protocol/muc#admin"];
NSXMLElement *item = [NSXMLElement elementWithName:@"item"];
[item addAttributeWithName:@"affiliation" stringValue:@"member"];
[item addAttributeWithName:@"jid" stringValue:@"jid to remove"];
[query addChild:item];
XMPPIQ *RemoveUser = [[XMPPIQ alloc] initWithType:@"set" to:[XMPPJID jidWithString:[NSString stringWithFormat:@"%@@%@",dialuser2,kSIPDomain]] elementID:@"some random id" child:query];
[SharedAppDelegate.xmppStream sendElement:RemoveUser];

So please help me if any solution for delete particular group.

Thanks

**Comment by shravanteegala** [comment]
I have same problem.

**Comment by reddydayakar06** [comment]
even am also facing the same issue, did anyone solve this issue?
if solved please share the solution.

**Comment by bacancy-jigar** [comment]
@shraddha-patel-1891  have you found the solution?

**Comment by shraddha-patel-1891** [comment]
No, I have not found a solution for exit group.

**Comment by jaganGanesan** [comment]
I am also facing same issue. My issue was member need to exit from group. I tried lot of code, it's not working. if any one have solution for this, please share here. it's helpful for me
