### ISSUE TITLE
How to get New Subject name of the Room in ios using XMPP

### ISSUE THREAD

**Issue by shraddha-patel-1891** [robbiehanson/XMPPFramework#863]
i changed Subject name using following code

if ([newRoomSubject length] == 0) return;

NSXMLElement *subject = [NSXMLElement elementWithName:@"subject" stringValue:newRoomSubject];

XMPPMessage *message = [XMPPMessage message];
[message addAttributeWithName:@"to" stringValue:Roomjid];
[message addAttributeWithName:@"type" stringValue:@"groupchat"];
[message addAttributeWithName:@"id" stringValue:[SharedAppDelegate.xmppStream generateUUID]];

[message addChild:subject];

[SharedAppDelegate.xmppStream sendElement:message];

NSXMLElement * x = [XMPPElement elementWithName:@"x" xmlns:@"jabber:x:data"];
[x addAttributeWithName:@"type" stringValue:@"submit"];

[xmppRoom fetchConfigurationForm];

Using above code change the subject of the room but not get the new subject of the room.

if any one have code or other information then please share with me.

Thanks

**Comment by vitalyster** [comment]
You should not fetch configuration form, room name/description from configuration form != room subject. As [XEP-0045](https://xmpp.org/extensions/xep-0045.html#subject-mod) say, you MUST receive plain message with new subject automatically.

**Comment by shraddha-patel-1891** [comment]
Thank you for giving me answer.
 i tried your solution and its working for me.
