### ISSUE TITLE
Duplicate interface definition for class XMPPMessageArchiveManagement

### ISSUE THREAD

**Issue by miguelpenades** [robbiehanson/XMPPFramework#871]
Seems that when installing XMPPFramework from CocoaPods you can face this "duplicate interface definition for class XMPPMessageArchiveManagement"

I think it happens because XMPPMessageArchiveManagement imports "XMPPFramework.h" and XMPPFramework.h imports again XMPPMessageArchiveManagement.h class.

It would be enough replacing all imports in XMPPFramework.h from:
#import "XMPPMessageArchiveManagement.h"
to:
#import <XMPPFramework/XMPPMessageArchiveManagement.h>

Thanks for the great framework by the way!

**Comment by chrisballinger** [comment]
Ah thanks for the report. I'll change the imports in `XMPPMessageArchiveManagement.h` because there's no reason for importing `XMPPFramework.h` there, only `XMPP.h`.
