### ISSUE TITLE
Change Read Me suggesting to use master

### ISSUE THREAD

**Issue by chrispolson-si** [robbiehanson/XMPPFramework#872]
There are 165 commits since the last proper version. Recommending the use of master is not desirable for various reasons. Users of the framework will get new individual commits every time they do a pod install. There needs to be more frequent specific versions that can be referenced, or maintained, etc. Users of the framework can't have new commits to the framework pouring in at random times.

**Comment by chrisballinger** [comment]
It was difficult to do a proper release until very recently, and some compromises had to be made. Master was recommended because there were many problems with the old podspec (and it actually points to a fork), but a proper release wasn't quite ready.

**Comment by chrisballinger** [comment]
fixed
