### ISSUE TITLE
Duplicate interface definition for class 'xxx' after using use_frameworks! in podfile

### ISSUE THREAD

**Issue by eddyCais** [robbiehanson/XMPPFramework#877]
<img width="909" alt="2017-02-23 3 03 15" src="https://cloud.githubusercontent.com/assets/17877178/23248244/56100f92-f9d9-11e6-9ed6-49f4b1467cd8.png">

**Comment by bztylzy** [comment]
After pod install open the .xcworkspace and import:

import XMPPFramework      // swift
@import XMPPFramework;   //objective-c

**Comment by chrisballinger** [comment]
@eddyCais Thanks for the report. The import should be changed to:

`#import "XMPPRoomMessage.h"`

I should do an audit to make sure there are no other imports like that.

**Comment by chrisballinger** [comment]
Fixed in 4beeabb
