### ISSUE TITLE
Join MUC with an iPhone that contains a smiley in the device name

### ISSUE THREAD

**Issue by Bcow7** [robbiehanson/XMPPFramework#879]
Hi guys,

I just found a small issue. When I'm try to join a MUC with an iPhone that contains a smiley in the device name, it doesn't work. When I remove the smiley, everything works fine!

By "device name", I mean the parameter : _Settings>General>About>Name_

Cheers

**Comment by chrisballinger** [comment]
Does the MUC code in XMPPFramework use your device name, or is that in your code? This might be a problem with libxml.

**Comment by Bcow7** [comment]
Hi @chrisballinger ,

You're right! I was calling this method in my code
`[myRoom joinRoomUsingNickname:[[UIDevice currentDevice] name] history:history];`

And I wasn't handling Emojis in the nickname, so I added this in my code :
```
#include <unicode/utf8.h>
@implementation NSString (EmojiExtension)
- (NSString *)stringByRemovingEmoji {
    NSData *d = [self dataUsingEncoding:NSUTF8StringEncoding allowLossyConversion:NO];
    if(!d) return nil;
    const char *buf = d.bytes;
    unsigned int len = (unsigned int)[d length];
    char *s = (char *)malloc(len);
    unsigned int ii = 0, oi = 0; // in index, out index
    UChar32 uc;
    while (ii < len) {
        U8_NEXT_UNSAFE(buf, ii, uc);
        if(0x2100 <= uc && uc <= 0x26ff) continue;
        if(0x1d000 <= uc && uc <= 0x1f77f) continue;
        U8_APPEND_UNSAFE(s, oi, uc);
    }
    return [[NSString alloc] initWithBytesNoCopy:s length:oi encoding:NSUTF8StringEncoding freeWhenDone:YES];
}
@end

```
I call 

`[myRoom joinRoomUsingNickname:[[[UIDevice currentDevice] name] stringByRemovingEmoji] history:history];`

and it works fine! So I update the code in XMPPFramework to handle this case and I created a pull request.
