### ISSUE TITLE
How to implement Group exit in ios  

### ISSUE THREAD

**Issue by shraddha-patel-1891** [robbiehanson/XMPPFramework#890]
Hello,
i will implement Group exit Functionlity.In this i assign any one member of the group Privilege change member to owner.it's working proper but now 1 group has 2 owners.
so how to remove previous owner of the Room?
any one have idea then please help me.

Thanks.

**Comment by JayMehta711** [comment]
Hello @shraddha-patel-1891 
Have you idea how to fetch all messages of group? 
it would be great if you help me.
