### ISSUE TITLE
How to send and receive Audio and Video immediatly in ios Using XMPP latest vesrion

### ISSUE THREAD

**Issue by shraddha-patel-1891** [robbiehanson/XMPPFramework#894]
I am currently making chat app using xmpp framwork.

For image,audio,video sending i am using XEP-0047: In-Band Bytestreams(ibb).

ibb is working proper for image sending and receiving but audio and video sending take too much time for sending and receiving.

**For Video sending code :**

videoData = [NSData dataWithContentsOfURL:videourl];;
NSString *videoStr=[videoData base64EncodedStringWithOptions:0];

NSXMLElement *message = [NSXMLElement elementWithName:@"message"];

[message addAttributeWithName:@"type" stringValue:@"set"];
[message addAttributeWithName:@"id" stringValue:@"ANY_ID_NAME"];
[message addAttributeWithName:@"from" stringValue:[[self xmppStream] myJID].full];
[message addAttributeWithName:@"to" stringValue:dictionary[@"to"]];
[message addAttributeWithName:@"chattype" stringValue:@"singlechat"];

NSXMLElement *data=[NSXMLElement elementWithName:@"data"];
[data addAttributeWithName:@"xmlns" stringValue:@"http://jabber.org/protocol/ibb"];
[data addAttributeWithName:@"seq" stringValue:@"0"];
[data addAttributeWithName:@"sid" stringValue:@"Stream0002"];

[data setStringValue:videoStr];

NSXMLElement *xmlmediatype=[NSXMLElement elementWithName:@"mediatype"];
[xmlmediatype setStringValue:@"video"];

[message addChild:xmlmediatype];
[message addChild:data];

[[self xmppStream] sendElement:message];

**For Audio sending code :**

NSData *dataAudio = [NSData dataWithContentsOfFile:filepath];
NSString *audioStr=[dataAudio base64EncodedStringWithOptions:0];

NSXMLElement *message = [NSXMLElement elementWithName:@"message"];

[message addAttributeWithName:@"type" stringValue:@"set"];
[message addAttributeWithName:@"id" stringValue:@"ANY_ID_NAME"];
[message addAttributeWithName:@"from" stringValue:[[self xmppStream] myJID].full];
[message addAttributeWithName:@"to" stringValue:dictionary[@"to"]];
[message addAttributeWithName:@"chattype" stringValue:@"singlechat"];

NSXMLElement *data=[NSXMLElement elementWithName:@"data"];
[data addAttributeWithName:@"xmlns" stringValue:@"http://jabber.org/protocol/ibb"];
[data addAttributeWithName:@"seq" stringValue:@"0"];
[data addAttributeWithName:@"sid" stringValue:@"Stream0002"];

[data setStringValue:audioStr];

NSXMLElement *xmlmediatype=[NSXMLElement elementWithName:@"mediatype"];
[xmlmediatype setStringValue:@"audio"];

[message addChild:xmlmediatype];
[message addChild:data];

[[self xmppStream] sendElement:message];
so any one have idea or code snippest to send audio and video like whats app then please help me.

Thanks

**Comment by JayMehta711** [comment]
Hello @shraddha-patel-1891 
Would you please help me how to send images and other multimedia file using XMPP Framework ?
If we used xep-0047 then both the  users should  be online (active) for file transfer ?
I am developing app in Swift 3.0 and ejabber server 
Thanks,

**Comment by shraddha-patel-1891** [comment]
Hello jay ,
i have given share image code snippiest.First upload image or other media on server.After successfully upload image or other media on server share url of media or display image or media using this url. 

-(void)upLoadImage:(UIImage*)uploadImage
{
JSQPhotoMediaItem *photoItem = [[JSQPhotoMediaItem alloc] initWithImage:uploadImage];

JSQMessage *photoMessage = [JSQMessage messageWithSenderId:[self.collectionView.dataSource senderId]
                                               displayName:[self.collectionView.dataSource senderDisplayName]
                                                     media:photoItem];
 float imageSize,imageClarity=1.0f;
NSData *imageData;

do {
   imageData = UIImageJPEGRepresentation(uploadImage,imageClarity);
    
    imageSize=([imageData length]/1024);
    imageClarity=imageClarity-0.1;
    
    NSLog(@"Size of Image(Kb):%lu",([imageData length]/1024));
} while ((imageSize>100.0f)&&(imageClarity>=0.05f));

NSString *urlString = @"http://YOUR UPLOAD URL";
NSString *filename = @"image";
NSMutableURLRequest *request= [[NSMutableURLRequest alloc] init] ;
[request setURL:[NSURL URLWithString:urlString]];
[request setHTTPMethod:@"POST"];
NSString *boundary = @"---------------------------14737809831466499882746641449";
NSString *contentType = [NSString stringWithFormat:@"multipart/form-data; boundary=%@",boundary];
[request addValue:contentType forHTTPHeaderField: @"Content-Type"];
NSMutableData *postbody = [NSMutableData data];
[postbody appendData:[[NSString stringWithFormat:@"\r\n--%@\r\n",boundary] dataUsingEncoding:NSUTF8StringEncoding]];
[postbody appendData:[[NSString stringWithFormat:@"Content-Disposition: form-data; name=\"image\"; filename=\"%@.jpg\"\r\n", filename] dataUsingEncoding:NSUTF8StringEncoding]];
[postbody appendData:[[NSString stringWithString:@"Content-Type: application/octet-stream\r\n\r\n"] dataUsingEncoding:NSUTF8StringEncoding]];
[postbody appendData:[NSData dataWithData:imageData]];
[postbody appendData:[[NSString stringWithFormat:@"\r\n--%@--\r\n",boundary] dataUsingEncoding:NSUTF8StringEncoding]];
[request setHTTPBody:postbody];
NSError *error;
NSData *returnData = [NSURLConnection sendSynchronousRequest:request returningResponse:nil error:&error];
NSString *str = [[NSString alloc] initWithData:returnData encoding:NSUTF8StringEncoding];
NSMutableDictionary *dict=[NSJSONSerialization JSONObjectWithData:[str dataUsingEncoding:NSUTF8StringEncoding] options:kNilOptions error:nil];


if (!error)
        {
          if([[dict objectForKey:@"success"] isEqualToString:@"200"])
          {
            [self.demoData.messages addObject:photoMessage];
              
              
              XMPPMessage *XMPPmessage = [XMPPMessage messageWithType:@"chat" to:self.chatJID];
              [XMPPmessage addBody:[dict objectForKey:@"bigurl"]];
              [[BBXMPPTool sharedInstance].xmppStream sendElement:XMPPmessage];
              
              
              
              
              
              NSDictionary *dictData = [[NSUserDefaults standardUserDefaults] dictionaryForKey:@"imageHistoryDict"];
              
              NSData *data;
              if([[dict objectForKey:@"bigurl"] hasSuffix:@".png"])
              {
                  data=UIImagePNGRepresentation(uploadImage);
              }else
              {
                  data=UIImageJPEGRepresentation(uploadImage, 1.0);
              }

              
              
              if([dictData count]<1)
              {
                  NSLog(@"dictionary Empty");
                  _chatImageHistory=[[NSMutableDictionary alloc] init];
                  [_chatImageHistory setObject:data forKey:[dict objectForKey:@"bigurl"]];
                  
                  
                  [[NSUserDefaults standardUserDefaults] setObject:_chatImageHistory forKey:@"imageHistoryDict"];
                  
              }else
              {
                  _chatImageHistory=[dictData mutableCopy];
                  
                  [_chatImageHistory setObject:data forKey:[dict objectForKey:@"bigurl"]];
                  
                  NSDictionary *dictionary=[_chatImageHistory copy];
                  [[NSUserDefaults standardUserDefaults] setObject:dictionary forKey:@"imageHistoryDict"];
              }
              

              
              
              NSString *count= [Chat fetchUnreadMessageCount:_chatJID.user];
              NSDictionary *dict2;
              if((![count isEqualToString:@"-1"])&&(count))
              {
                  int uCount=count.intValue+1;
                  dict2=[[BBXMPPTool sharedInstance] userName:_chatJID.user lastMessage:@"📷Image" messageTime:[NSDate date] uReadMessageCount:[NSString stringWithFormat:@"%d",uCount] userNickName:self.userNickName];
                  
              }else
              {
                  dict2=[[BBXMPPTool sharedInstance] userName:_chatJID.user lastMessage:@"📷Image" messageTime:[NSDate date] uReadMessageCount:@"-1" userNickName:self.userNickName];
              }
              
              
              
              
              [Chat insertIntoDB:dict2];

              
              
              
              
              
                   [self finishSendingMessageAnimated:YES];
          }
    
        }
        else{
            NSLog(@"%@",error);
            
        }
}
Thanks.

**Comment by JayMehta711** [comment]
Hello @shraddha-patel-1891 ,
Thank you for replay to me. Can we send image using XMPPIncomingFileTransfer & XMPPOutgoingFileTransfer ?, this is good way to send images and other multimedia objects.
Would you share chat app link that you develop ,if this fine for you?
