### ISSUE TITLE
发送一条群消息,会走多次- (void)xmppRoom:(XMPPRoom *)sender didReceiveMessage:(XMPPMessage *)message fromOccupant:(XMPPJID *)occupantJID代理方法

### ISSUE THREAD

**Issue by kivenZheng** [robbiehanson/XMPPFramework#895]
加入房间代码如下`-(void)joinRoomWithRoomID:(XMPPJID *)roomId nickName:(NSString *)nickName {
    NSXMLElement *p = [NSXMLElement elementWithName:@"history"];
    [p addAttributeWithName:@"maxchars" stringValue:@"0"];// 不获取
    //创建房间
    self.xmppRoom = [[XMPPRoom alloc] initWithRoomStorage:[XMPPRoomCoreDataStorage sharedInstance] jid:roomId dispatchQueue:dispatch_get_main_queue()];
    //设置参数和代理
    [self.xmppRoom addDelegate:self delegateQueue:dispatch_get_main_queue()];
    
    //激活
    [self.xmppRoom activate:[XMPPManager sharedManager].xmppStream];
    
    //加入房间  如果房间存在就加入房间，如果不存在则创建房间
    [self.xmppRoom joinRoomUsingNickname:nickName history:p];
}`,
发送群聊消息代码如下`-(void)senRoomMessageWithRoomID:(XMPPJID *)roomId message:(NSString *)message {
    NSXMLElement *body = [NSXMLElement elementWithName:@"body"];
    [body setStringValue:message];
    //生成XML消息文档
    NSXMLElement *mes = [NSXMLElement elementWithName:@"message"];
    //消息类型
    [mes addAttributeWithName:@"type" stringValue:@"groupchat"];
    //发送给谁
    [mes addAttributeWithName:@"to" stringValue:roomId.full];
    //由谁发送
    [mes addAttributeWithName:@"from" stringValue:[XMPPManager sharedManager].myJID.full];
   
    
    //组合
    [mes addChild:body];
    //发送消息
    //    [[XMPPManager sharedManager].xmppStream sendElement:mes];
    
    [self.xmppStream sendElement:mes];
}
`
代理方法如下:`- (void)xmppRoom:(XMPPRoom *)sender didReceiveMessage:(XMPPMessage *)message fromOccupant:(XMPPJID *)occupantJID{
    
    NSLog(@"收到群消息 %@**************%@",message.body,occupantJID);
}`

控制台打印如下:`2017-03-29 09:58:13.713276 XMPPChat[837:306453] 你好啊
2017-03-29 09:58:13.726937 XMPPChat[837:306453] 收到群消息 你好啊**************1000@conference.localhost/我是9999
2017-03-29 09:58:13.834064 XMPPChat[837:306453] 收到群消息 你好啊**************1000@conference.localhost/我是9999`

每进入房间一次,发一条消息,在- (void)xmppRoom:(XMPPRoom *)sender didReceiveMessage:(XMPPMessage *)message fromOccupant:(XMPPJID *)occupantJID代理方法里就会多走一遍,请问这个问题应该怎么解决?谢谢

**Comment by KivenZheng** [comment]
已解决
