### ISSUE TITLE
XEP-0016: Privacy Lists

### ISSUE THREAD

**Issue by jasanchezsa** [robbiehanson/XMPPFramework#90]
Hello, I want to create a list of blocked users and refuse to communicate with them. I use the XMPP extension XEP-0016 and initialize:

<pre>
<code>
- (void)setupXMPPPrivacy
{
    NSLog((@"%s [Line %d] "), __PRETTY_FUNCTION__, __LINE__);
    //Init XMPPPrivacy List
    //xmppPrivacy = [[XMPPPrivacy alloc] init];
    xmppPrivacy = [[XMPPPrivacy alloc] initWithDispatchQueue:dispatch_get_main_queue()];
    //Activate xmpp modules
    [xmppPrivacy activate:xmppStream];
    //Delegate XMPPPrivacy
    [xmppPrivacy addDelegate:self delegateQueue:dispatch_get_main_queue()];
}
</code>
</pre>

Then attempt to block a user as follows:

<pre>
<code>
- (void)privacyBlock
{
    XMPPPrivacy *privacy = [[XMPPPrivacy alloc] init];
    NSXMLElement *privacyElement = [XMPPPrivacy privacyItemWithType:@"jid" value:@"charlie@chat.com" action:@"deny" order:0];
    [XMPPPrivacy blockIQs:privacyElement];
    [XMPPPrivacy blockMessages:privacyElement];
    [XMPPPrivacy blockPresenceIn:privacyElement];
    [XMPPPrivacy blockPresenceOut:privacyElement]; 
    NSLog(@"-------> PRIVACY ELEMENT: %@", privacyElement);
   
    NSArray *arrayPrivacy = [[NSArray alloc] initWithObjects:privacyElement, nil];
    [privacy setListWithName:@"test" items:arrayPrivacy];
}
</code>
</pre>

Do not get it to work the method setListWithName, when I run this code the application crash. I tried to use the methods: setDefaultListName and setActiveListName but it is the same, although no difference between these methods.

https://github.com/robbiehanson/XMPPFramework/blob/master/Extensions/XEP-0016/XMPPPrivacy.m

Not if I have to configure anything else about XMPPPrivacy. I am missing.

Thank you very much. Sorry for my English.

**Comment by vishaldeshai** [comment]
@arshadkc As per your i have implemented in iOS but after reconnect privacy setting will be reset.

is there any reason??

thanks in advance.
