### ISSUE TITLE
Missing required attribute 'id' in IQ stanzas

### ISSUE THREAD

**Issue by nixxcode** [robbiehanson/XMPPFramework#908]
According to the [XMPP core specification](https://tools.ietf.org/html/rfc6120#section-8.2.3)

> 1.  The 'id' attribute is REQUIRED for IQ stanzas.

IQ stanzas sent by XMPPFramework do not (all) comply with this requirement, causing certain servers to reject the requests.

For example, calling `-[XMPPStream registerWithPassword:error:]` against ejabberd version 17.01 results in the following exchange:
```
SEND: <iq type="set"><query xmlns="jabber:iq:register">
        <username>user1234</username><password>secret</password>
      </query></iq>

RECV: <iq xmlns="jabber:client" type="error">
        <query xmlns="jabber:iq:register">
          <username>user1234</username><password>secret</password>
        </query>
        <error code="400" type="modify">
          <bad-request xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/>
          <text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">
            Missing attribute 'id' in tag &lt;iq/&gt; qualified by namespace 'jabber:client'
          </text>
        </error>
      </iq>
```

**Comment by chrisballinger** [comment]
Thanks for the report! Would you mind auditing the framework for missing ids and creating a list of methods that need to be fixed? ...Or even better creating a pull request?

**Comment by nixxcode** [comment]
Sure @chrisballinger I can create a pull request to address this.

There are two broad approaches, which do you prefer?
1. Ensure all code creates IQs using `XMPPIQ` and modify it to create an elementID if not passed in
2. Leave `XMPPIQ` alone and update any offending code that creates and sends IQ stanzas

I prefer option 1 but am not sure which is a better fit for XMPPFramework's style

**Comment by mohanmoorthy** [comment]
@chrisballinger  @nixxcode  Any update on this? 

thanks in advance.

**Comment by hamdullahshah** [comment]
@nixxcode what's would be the temporary solution for that ?

**Comment by adozenlines** [comment]
Download the latest framework code.

**Comment by vatsal1992** [comment]
i'm using `pod 'XMPPFramework'` to get latest code.
and 
This is my code to Register

```
    XMPPJID* jid = [XMPPJID jidWithString:self.username];
    [xmppStream setMyJID:jid];
    NSError* regError;
    [xmppStream registerWithPassword:self.password error:&regError];
```

but in delegate i always receive this error...
