### ISSUE TITLE
How i Implement XEP-0363 http file upload or image sharing in my IOS XMPP Client. 

### ISSUE THREAD

**Issue by shravanteegala** [robbiehanson/XMPPFramework#909]
Hi,
I Added XEP-0363 Extension for my iOS Xmpp Project. But how i upload the image or file . using these Extension.
Plz give me sample code in Objective-C . or swift.
Please Help me.

**Comment by chrisballinger** [comment]
Sorry, this isn't a support forum, it is for tracking bugs and discussing code improvements. There is already some documentation and unit tests for the XEP-0363 module, but perhaps it could use more thorough coverage.

I suggest you re-read this to get started: https://xmpp.org/extensions/xep-0363.html
