### ISSUE TITLE
How to Create Group Chat(MUC) in IOS .

### ISSUE THREAD

**Issue by shravanteegala** [robbiehanson/XMPPFramework#921]
I am developing a chat app in iOS. In XMPP server (Ejabberd in this case,I have enabled MUC ). I have registered a user and now trying to create a chatroom using an registered user. 
but its not created ChatRoom(groupName) in server and not added to roster list .
Any one please help me.
iam using below code:

XMPPRoomMemoryStorage *roomMemory = [[XMPPRoomMemoryStorage alloc]init];
    // XMPPJID  *roomJID = [XMPPJID jidWithString:@"chat@conference.lasonic.local"];
    
    XMPPJID  *roomJID = [XMPPJID jidWithString:@"chatTeegala@conference.vmailu.com"];
    
    self.xmppRoom = [[XMPPRoom alloc] initWithRoomStorage:roomMemory
                                                      jid:roomJID
                                            dispatchQueue:dispatch_get_main_queue()];
    [self.xmppRoom activate:[BBXMPPTool sharedInstance].xmppStream];
    [self.xmppRoom addDelegate:self delegateQueue:dispatch_get_main_queue()];
    
    [[BBXMPPTool sharedInstance].xmppStream addDelegate:self
                   delegateQueue:dispatch_get_main_queue()];
    [self.xmppRoom joinRoomUsingNickname:[self createUUID]
                                 history:nil
                                password:nil];
    
   // [self.xmppRoom fetchConfigurationForm];

**Comment by warisappify** [comment]
@shravanteegala If your issue is resolved then kindly help others.
