### ISSUE TITLE
The app in the background, iOS9 can receive messages, iOS10 not receive.

### ISSUE THREAD

**Issue by xjlove** [robbiehanson/XMPPFramework#937]
_xmppStream.enableBackgroundingOnSocket = YES;Has already been set up

**Comment by xjlove** [comment]
Into the front desk, message immediately came over

**Comment by vitalyster** [comment]
Background sockets were forbidden in iOS 10

**Comment by xjlove** [comment]
No.My old projects in iOS10 background can be received IM message.Don't know where changed recently, lead to close not to.So I want to ask next to configure?

**Comment by vitalyster** [comment]
your "old project" receives push notifications? Even if you will made some tricy configuration for backgrounding sockets, it will be rejected by appstore

**Comment by xjlove** [comment]
Not rejected.We have a VOIP function project.Before the background also can walk - (void) xmppStream: (xmppStream *) sender didReceiveMessage: (XMPPMessage *) message this method.In this method of local notifications.Now in the background, this approach doesn't work.If they haven't set up?

**Comment by vitalyster** [comment]
There is an official Apple statement: backgrounding sockets will not work anymore, except you are uses older SDK - https://developer.apple.com/library/content/qa/qa1938/_index.html#//apple_ref/doc/uid/DTS40017564

**Comment by xjlove** [comment]
My XMPP SDK has always been old..Never upgrade...

**Comment by xjlove** [comment]
Mean, access your new XMPP now, under the iOS 10, no matter what happens.Program in the background, not kill, XMPP doesn't go @ "- (void) xmppStream: (xmppStream *) sender didReceiveMessage: (XMPPMessage *) message" this method?

**Comment by chrisballinger** [comment]
Your question has been answered but it seems like you don't believe the answer. You should look at XEP-0357 and PushKit.
