### ISSUE TITLE
sometimes jid resource changed as random string

### ISSUE THREAD

**Issue by edsgershao** [robbiehanson/XMPPFramework#985]
I set jid  with resource when xmpp connect, but sometimes the jid resource in openfire changed as random  string.  I add resource when send element still exist this issue. does any body occur this problem, how to solve it
![xmpp_resource](https://user-images.githubusercontent.com/12269799/31602113-97d81536-b221-11e7-9e39-de4be962136a.png)

![image](https://user-images.githubusercontent.com/12269799/31602122-a442a160-b221-11e7-9a96-e39c2eb44b15.png)

**Comment by edsgershao** [comment]
`- (BOOL) connectWithHost:(NSString*)host port:(UInt16)port account:(NSString *) account error:(NSError **)errorPtr {
    XLOG_WARNING(@"connect Host=%@ port=%d", host, port);
    if (host.length > 0) {
        [_xmppStream setHostName:host];
    }
    if (port > 0) {
        [_xmppStream setHostPort:port];
    }
    
    if (_xmppStream.isConnected) {
        XLOG_WARNING(@"xmpp connect but stream is connected");
        [self disconnect];
    }
    if (![_xmppStream isDisconnected]) {
        XLOG_WARNING(@"xmpp connect but stream is connected");
        return YES;
    }
    NSString *jidDomain = [[MFNetworkConfig sharedInstance] jidDomain];

    NSString *jidString = [NSString stringWithFormat:@"%@@%@/mobile", account, jidDomain];
    XMPPJID *jid = [XMPPJID jidWithString:jidString];
    [_xmppStream setMyJID:jid];
    

    BOOL success = [_xmppStream connectWithTimeout:MFLongConnectionConnectTimeout error:errorPtr];
    XLOG_WARNING(@"XMPPStream connectWithTimeout %@, %@", (success ? @"YES" : @"NO"), *errorPtr);
    return success;
}`

**Comment by vitalyster** [comment]
That is expected, server is able to change your resource, you can check final JID (`XMPPStream myJID`) after authentication in `xmppStreamDidAuthenticate:sender` callback of `XMPPStreamDelegate`

**Comment by edsgershao** [comment]
@vitalyster thanks for your advice. I will print the call stack trace when resource changed(when xmpp-bind,setMyJID_setByClient,setMyJID_setByServer).

**Comment by fengzhonglingluandeduanfa** [comment]
I have the same problem, has it been solved
